-- 00279 — Contenu des preuves attendues ISO 27001 (modèle mutualisé).
-- (1) Preuves canoniques (evidence_items) dédupliquées ; (2) liens par contrôle
-- (evidence_catalog.evidence_item_id). 2-4 preuves par mesure.

insert into public.evidence_items (framework_id, name, description, kind)
select '00000000-0000-0000-0000-000000000010', t.name, t.descr, t.kind
from (values
  ('Politique de sécurité de l''information', 'Prouve que la politique est définie, approuvée par la direction, publiée et communiquée.', 'policy'),
  ('Preuve de communication de la politique', 'Prouve la diffusion et la prise de connaissance par le personnel et les parties intéressées.', 'record'),
  ('Historique de revue de la politique', 'Prouve la revue à intervalles planifiés ou lors de changements majeurs.', 'record'),
  ('Matrice des rôles et responsabilités SSI (RACI)', 'Prouve l''attribution formelle des rôles et responsabilités de sécurité.', 'document'),
  ('Lettres de nomination RSSI et responsables sécurité', 'Prouve la désignation formelle des personnes responsables.', 'record'),
  ('Organigramme du SMSI', 'Prouve la structure et les lignes de reporting de la sécurité.', 'document'),
  ('Matrice de séparation des tâches', 'Prouve l''identification des tâches et responsabilités conflictuelles et leur séparation.', 'document'),
  ('Politique de contrôle d''accès', 'Prouve l''intégration de la séparation des tâches dans les droits d''accès.', 'policy'),
  ('Extrait des profils et habilitations applicatifs', 'Prouve l''absence de cumul de droits incompatibles dans les systèmes.', 'config'),
  ('Comptes rendus de revue de direction', 'Prouve l''engagement de la direction et le suivi de l''application de la politique.', 'record'),
  ('Engagements de la direction (lettre d''engagement, objectifs SMSI)', 'Prouve que la direction exige le respect des règles de sécurité par le personnel.', 'document'),
  ('Liste des contacts autorités compétentes', 'Prouve l''identification des autorités pertinentes (CERT, régulateur, police, protection des données) et leurs coordonnées.', 'document'),
  ('Procédure de contact avec les autorités', 'Prouve les conditions et responsables des contacts avec les autorités.', 'document'),
  ('Procédure de gestion des incidents', 'Prouve l''intégration des notifications aux autorités dans la gestion des incidents.', 'document'),
  ('Liste des groupes d''intérêt et abonnements', 'Prouve l''adhésion à des forums, associations ou listes de diffusion spécialisés en sécurité.', 'record'),
  ('Preuves de participation (conférences, forums, newsletters)', 'Prouve l''implication effective dans la veille et le partage avec la communauté sécurité.', 'record'),
  ('Procédure de veille sur les menaces', 'Prouve le processus de collecte, d''analyse et de diffusion du renseignement sur les menaces.', 'document'),
  ('Rapports ou bulletins de veille menaces', 'Prouve la collecte et l''analyse effectives (CERT, CTI, éditeurs).', 'record'),
  ('Registre des risques', 'Prouve la prise en compte des menaces identifiées dans l''appréciation des risques.', 'record'),
  ('Méthodologie de gestion de projet intégrant la sécurité', 'Prouve que les exigences de sécurité sont intégrées dans le cycle de vie des projets.', 'document'),
  ('Analyses de risques de projets', 'Prouve l''évaluation des risques de sécurité sur des projets échantillonnés.', 'record'),
  ('Checklist ou jalons de sécurité de projet', 'Prouve la validation de la sécurité aux jalons des projets.', 'record'),
  ('Inventaire des actifs', 'Prouve l''identification et la tenue à jour des informations et actifs associés avec leurs propriétaires.', 'record'),
  ('Procédure de gestion de l''inventaire des actifs', 'Prouve les règles d''identification, de propriété et de mise à jour de l''inventaire.', 'document'),
  ('Chartes (confidentialité, utilisateur)', 'Prouve que les règles d''utilisation acceptable sont formalisées et acceptées par les utilisateurs.', 'document'),
  ('Politique d''utilisation acceptable des actifs', 'Prouve les règles d''usage des informations et actifs (messagerie, internet, mobiles, supports).', 'policy'),
  ('Preuves d''acceptation par les utilisateurs', 'Prouve la signature ou l''acceptation des règles par le personnel.', 'record'),
  ('Procédure de départ et de mobilité du personnel', 'Prouve le processus de restitution des actifs en fin de contrat ou de changement de poste.', 'document'),
  ('Fiches de restitution des actifs signées', 'Prouve la restitution effective des équipements, badges et supports par échantillon de départs.', 'record'),
  ('Procédure de classification de l''information', 'Prouve le schéma de classification de l''information selon confidentialité, intégrité et disponibilité.', 'document'),
  ('Registre ou exemples d''informations classifiées', 'Prouve l''application effective de la classification aux informations.', 'record'),
  ('Procédure de marquage des informations', 'Prouve les règles de marquage et d''étiquetage selon la classification.', 'document'),
  ('Exemples de documents ou supports marqués', 'Prouve l''application effective du marquage.', 'record'),
  ('Politique de transfert de l''information', 'Prouve les règles de transfert sécurisé (messagerie, échange de fichiers, supports physiques).', 'policy'),
  ('Accords de transfert d''information avec les tiers', 'Prouve les règles convenues de transfert avec les parties externes (NDA, accords d''échange).', 'document'),
  ('Configuration du chiffrement des échanges', 'Prouve les moyens techniques de protection des transferts (TLS, SFTP, chiffrement messagerie).', 'config'),
  ('Matrice d''accès par profil', 'Prouve l''application du besoin d''en connaître et du moindre privilège.', 'document'),
  ('Procédure de gestion du cycle de vie des identités', 'Prouve les processus de création, modification et suppression des identités.', 'document'),
  ('Liste des comptes et identités (annuaire)', 'Prouve l''unicité des identités et l''absence de comptes orphelins ou génériques non maîtrisés.', 'config'),
  ('Demandes d''arrivée et de départ échantillonnées', 'Prouve l''exécution effective du cycle de vie des identités.', 'record'),
  ('Politique de mots de passe et d''authentification', 'Prouve les exigences de robustesse, de renouvellement et d''authentification forte.', 'policy'),
  ('Configuration de la politique de mots de passe et de MFA', 'Prouve l''application technique des règles d''authentification dans les systèmes.', 'config'),
  ('Procédure d''attribution des secrets d''authentification', 'Prouve la remise sécurisée et la réinitialisation des secrets.', 'document'),
  ('Procédure de provisionnement et de révocation des droits', 'Prouve le processus d''attribution, de modification et de retrait des droits d''accès.', 'document'),
  ('Revues périodiques des droits d''accès', 'Prouve la revue régulière des droits par les propriétaires d''actifs.', 'record'),
  ('Demandes d''accès et de révocation échantillonnées', 'Prouve l''autorisation préalable et la révocation effective des droits.', 'record'),
  ('Politique fournisseurs', 'Prouve les exigences de sécurité définies pour la relation avec les fournisseurs.', 'policy'),
  ('Liste et classification des fournisseurs', 'Prouve l''identification des fournisseurs ayant accès aux informations et leur criticité.', 'record'),
  ('Appréciations de risques fournisseurs', 'Prouve l''évaluation des risques liés aux fournisseurs avant engagement.', 'record'),
  ('Clauses de sécurité contractuelles fournisseurs', 'Prouve l''inclusion d''exigences de sécurité dans les accords avec les fournisseurs.', 'document'),
  ('Contrats ou accords fournisseurs échantillonnés', 'Prouve la présence effective de clauses de sécurité, de confidentialité et d''audit.', 'record'),
  ('Exigences de sécurité de la chaîne d''approvisionnement TIC', 'Prouve les exigences imposées aux fournisseurs TIC et à leurs sous-traitants.', 'document'),
  ('Évaluation des risques de la chaîne d''approvisionnement', 'Prouve l''analyse des risques liés aux produits et services TIC.', 'record'),
  ('Rapports de suivi et de revue des fournisseurs', 'Prouve la surveillance régulière des niveaux de service et de sécurité des fournisseurs.', 'record'),
  ('Comptes rendus de comités de pilotage fournisseurs', 'Prouve les revues périodiques et le traitement des écarts.', 'record'),
  ('Procédure de gestion des changements fournisseurs', 'Prouve la maîtrise des changements de services et de leurs impacts sécurité.', 'document'),
  ('Politique d''utilisation des services cloud', 'Prouve les exigences d''acquisition, d''utilisation et de sortie des services cloud.', 'policy'),
  ('Registre des services cloud et responsabilités partagées', 'Prouve l''identification des services cloud utilisés et la répartition des responsabilités.', 'record'),
  ('Attestations de sécurité des fournisseurs cloud', 'Prouve les garanties du fournisseur (ISO 27001, SOC 2, rapports d''audit).', 'record'),
  ('Organisation de la cellule de gestion des incidents', 'Prouve la désignation de l''équipe de réponse et des contacts d''astreinte.', 'document'),
  ('Grille de classification et d''escalade des incidents', 'Prouve les critères de gravité et les circuits d''escalade.', 'document'),
  ('Registre des incidents', 'Prouve l''évaluation et la catégorisation de chaque événement de sécurité.', 'record'),
  ('Critères de qualification des événements', 'Prouve les règles de décision pour qualifier un événement en incident.', 'document'),
  ('Dossiers d''incidents échantillonnés', 'Prouve la traçabilité des actions de réponse et de clôture.', 'record'),
  ('Rapports de retour d''expérience post-incident', 'Prouve l''analyse des causes et les enseignements tirés des incidents.', 'record'),
  ('Plan d''actions correctives issues des incidents', 'Prouve la mise en œuvre d''améliorations pour réduire la récurrence.', 'record'),
  ('Procédure de collecte et de préservation des preuves', 'Prouve les règles d''identification, collecte et conservation des preuves numériques.', 'document'),
  ('Registre de chaîne de traçabilité des preuves', 'Prouve l''intégrité et la traçabilité des preuves collectées lors d''incidents.', 'record'),
  ('Plan de continuité d''activité (PCA)', 'Prouve la planification du maintien de la sécurité de l''information en cas de perturbation.', 'document'),
  ('Plan de gestion de crise', 'Prouve les dispositions de gouvernance et de communication en situation de crise.', 'document'),
  ('Analyse d''impact sur l''activité (BIA)', 'Prouve l''identification des exigences de sécurité à maintenir pendant la perturbation.', 'document'),
  ('Plan de reprise informatique (PRA) et objectifs RTO/RPO', 'Prouve la définition des exigences de reprise des systèmes TIC.', 'document'),
  ('Rapports de tests PCA/PRA', 'Prouve la vérification périodique de la capacité de continuité des TIC.', 'record'),
  ('Registre des exigences légales et réglementaires', 'Prouve l''identification et la mise à jour des exigences légales, réglementaires et contractuelles applicables.', 'record'),
  ('Procédure de veille réglementaire', 'Prouve le processus de suivi des évolutions applicables.', 'document'),
  ('Évaluation de conformité aux exigences applicables', 'Prouve la vérification de la prise en compte de ces exigences.', 'record'),
  ('Politique de protection de la propriété intellectuelle', 'Prouve les règles de respect des licences et droits de propriété intellectuelle.', 'policy'),
  ('Registre des licences logicielles', 'Prouve l''inventaire des licences acquises et leur utilisation conforme.', 'record'),
  ('Procédure de contrôle des logiciels installés', 'Prouve la maîtrise des logiciels non autorisés ou non licenciés.', 'document'),
  ('Politique de conservation et de protection des enregistrements', 'Prouve les durées de conservation et la protection contre perte, altération ou accès non autorisé.', 'policy'),
  ('Calendrier de conservation des enregistrements', 'Prouve les durées par type d''enregistrement conformément aux exigences légales.', 'document'),
  ('Configuration de sauvegarde et d''archivage', 'Prouve la protection technique des enregistrements.', 'config'),
  ('Politique de protection des données à caractère personnel', 'Prouve les règles de protection de la vie privée conformes à la réglementation applicable.', 'policy'),
  ('Registre des traitements de DCP', 'Prouve l''identification des traitements et des finalités des données personnelles.', 'record'),
  ('Désignation du DPO ou correspondant et déclarations à l''autorité', 'Prouve la gouvernance de la protection des données et les formalités réglementaires.', 'record'),
  ('Rapports d''audit interne SMSI', 'Prouve la revue indépendante de l''approche de sécurité par audit interne à intervalles planifiés.', 'record'),
  ('Rapports d''audit externe ou de certification', 'Prouve la revue indépendante par un tiers qualifié.', 'record'),
  ('Programme d''audit', 'Prouve la planification des revues indépendantes.', 'document'),
  ('Rapports de vérification de conformité aux politiques', 'Prouve les contrôles réguliers du respect des politiques et normes par les responsables.', 'record'),
  ('Revues techniques de conformité (durcissement, configurations)', 'Prouve la vérification de la conformité technique des systèmes.', 'record'),
  ('Procédures d''exploitation documentées', 'Prouve la documentation des procédures opérationnelles et leur disponibilité pour le personnel concerné.', 'document'),
  ('Registre de gestion documentaire (versions, validation)', 'Prouve la maîtrise des versions et l''approbation des procédures.', 'record'),
  ('Procédure de vérification des antécédents', 'Prouve que des vérifications proportionnées au risque sont définies avant embauche.', 'document'),
  ('Échantillon de dossiers de recrutement avec vérifications', 'Prouve l''application effective des vérifications (casier, références, diplômes) sur des recrutements récents.', 'record'),
  ('Procédures RH (arrivée, mutation, départ)', 'Prouve l''intégration de la sélection dans le processus RH global.', 'document'),
  ('Modèle de contrat de travail avec clauses de sécurité', 'Prouve que les contrats imposent des responsabilités de sécurité de l''information.', 'document'),
  ('Contrats signés (échantillon)', 'Prouve que les clauses sont effectivement signées par le personnel.', 'record'),
  ('Plan de sensibilisation et formation', 'Prouve l''existence d''un programme planifié de sensibilisation et de formation.', 'document'),
  ('Registre des participations aux formations', 'Prouve la réalisation effective des sessions et la couverture du personnel.', 'record'),
  ('Supports de formation et résultats d''évaluation', 'Prouve le contenu dispensé et l''efficacité de la sensibilisation.', 'document'),
  ('Procédure disciplinaire sécurité', 'Prouve que les sanctions en cas de violation de la politique de sécurité sont définies et formalisées.', 'policy'),
  ('Règlement intérieur intégrant les sanctions', 'Prouve l''opposabilité des sanctions au personnel.', 'document'),
  ('Registre des cas disciplinaires liés à la sécurité', 'Prouve l''application du processus lors de violations avérées.', 'record'),
  ('Checklists de départ signées', 'Prouve la restitution des actifs, le retrait des accès et le rappel des obligations de confidentialité.', 'record'),
  ('Clauses de confidentialité post-emploi', 'Prouve la persistance des obligations après la fin du contrat.', 'document'),
  ('Modèle d''accord de confidentialité (NDA)', 'Prouve l''existence d''un modèle reflétant les besoins de protection de l''information.', 'document'),
  ('NDA signés (employés, tiers)', 'Prouve la signature effective par le personnel et les parties externes.', 'record'),
  ('Politique de télétravail et d''accès à distance', 'Prouve que les règles de sécurité du travail à distance sont définies.', 'policy'),
  ('Configuration VPN et authentification forte à distance', 'Prouve la mise en oeuvre technique de la sécurisation des accès distants.', 'config'),
  ('Liste des télétravailleurs autorisés', 'Prouve que le télétravail est autorisé et encadré.', 'record'),
  ('Procédure de signalement des événements de sécurité', 'Prouve que le canal et les modalités de signalement sont définis et connus.', 'document'),
  ('Registre des événements et incidents signalés', 'Prouve que les signalements sont effectivement reçus et traités.', 'record'),
  ('Plan des zones sécurisées', 'Prouve la définition des périmètres et zones de sécurité physique.', 'document'),
  ('Rapport de visite des périmètres physiques', 'Prouve l''intégrité des barrières (portes, clôtures, murs) sur site.', 'record'),
  ('Registre des accès physiques', 'Prouve la traçabilité des entrées dans les locaux et zones sensibles.', 'record'),
  ('Liste des habilitations d''accès physique', 'Prouve que les droits d''accès aux locaux sont attribués et revus.', 'record'),
  ('Procédure d''accueil et d''accompagnement des visiteurs', 'Prouve le contrôle des visiteurs et des tiers.', 'document'),
  ('Inventaire des clés et badges des locaux', 'Prouve la maîtrise des moyens de fermeture des bureaux et salles.', 'record'),
  ('Politique du poste de travail et bureau propre', 'Prouve les règles de protection des espaces de travail.', 'policy'),
  ('Cartographie des caméras et dispositifs de surveillance', 'Prouve la couverture de surveillance des zones sensibles.', 'document'),
  ('Procédure de conservation et revue des enregistrements vidéo', 'Prouve la gestion des enregistrements et leur revue.', 'policy'),
  ('Journaux d''alarmes et rapports de levée de doute', 'Prouve la détection et le traitement des intrusions.', 'record'),
  ('Analyse des risques physiques et environnementaux', 'Prouve l''identification des menaces (incendie, inondation, foudre) sur les sites.', 'document'),
  ('Rapports de vérification des équipements anti-incendie', 'Prouve la maintenance des détecteurs, extincteurs et systèmes d''extinction.', 'record'),
  ('Plan d''évacuation et comptes rendus d''exercices', 'Prouve la préparation aux sinistres.', 'record'),
  ('Procédure de travail en zone sécurisée', 'Prouve que les règles applicables en zone sécurisée sont définies.', 'policy'),
  ('Configuration du verrouillage automatique de session', 'Prouve la mise en oeuvre technique de l''écran vide.', 'config'),
  ('Rapports de contrôles de bureau propre', 'Prouve la vérification effective du respect de la politique.', 'record'),
  ('Plan d''implantation des équipements et salles techniques', 'Prouve le positionnement sécurisé des équipements sensibles.', 'document'),
  ('Politique des équipements mobiles et hors site', 'Prouve que les règles de protection des actifs hors des locaux sont définies.', 'policy'),
  ('Configuration du chiffrement et de l''effacement à distance des postes mobiles', 'Prouve la protection technique des équipements nomades.', 'config'),
  ('Procédure de gestion des supports amovibles', 'Prouve les règles de classification, usage, transport et destruction des supports.', 'policy'),
  ('Configuration de blocage des ports USB et supports amovibles', 'Prouve le contrôle technique de l''usage des supports.', 'config'),
  ('Registre des supports de stockage et de leur mise au rebut', 'Prouve la traçabilité du cycle de vie des supports.', 'record'),
  ('Schéma des alimentations électriques et télécoms (onduleurs, groupe électrogène)', 'Prouve la redondance et la protection contre les coupures.', 'document'),
  ('Rapports de test des onduleurs et du groupe électrogène', 'Prouve le bon fonctionnement des services généraux de secours.', 'record'),
  ('Plan de maintenance des équipements', 'Prouve l''entretien planifié des installations de soutien.', 'document'),
  ('Plan de câblage et schéma de brassage', 'Prouve la cartographie et la protection des câbles réseau et électriques.', 'document'),
  ('Rapport d''inspection des locaux techniques et baies', 'Prouve la protection physique des câbles et des accès aux baies.', 'record'),
  ('Rapports d''intervention et contrats de maintenance', 'Prouve la réalisation de la maintenance préventive et corrective par du personnel autorisé.', 'record'),
  ('Procédure de mise au rebut et de réutilisation du matériel', 'Prouve que l''effacement sécurisé avant rebut ou réutilisation est défini.', 'policy'),
  ('Certificats d''effacement ou de destruction', 'Prouve l''effacement effectif des données avant sortie du matériel.', 'record'),
  ('Politique de sécurité des terminaux (postes et mobiles)', 'Définit les exigences de sécurité applicables aux postes de travail et appareils mobiles (chiffrement, verrouillage, MDM, BYOD).', 'policy'),
  ('Export de la console MDM / gestion des postes', 'Prouve l''application effective des configurations de sécurité sur le parc de terminaux.', 'config'),
  ('Procédure de gestion des comptes à privilèges', 'Décrit l''attribution, l''approbation, la revue et le retrait des droits privilégiés.', 'document'),
  ('Liste des comptes à privilèges', 'Recense les comptes administrateurs avec leur justification et leur titulaire.', 'record'),
  ('Rapport de revue des droits d''accès', 'Prouve la revue périodique des droits privilégiés.', 'record'),
  ('Registre des habilitations / matrice des accès', 'Documente les droits d''accès attribués par rôle et par ressource.', 'record'),
  ('Configuration des permissions sur les ressources sensibles', 'Montre la restriction effective des accès aux données sensibles (ACL, partages).', 'config'),
  ('Liste des accès aux dépôts de code source', 'Montre les utilisateurs et droits (lecture/écriture) sur les dépôts de code.', 'record'),
  ('Configuration de protection des branches et du dépôt', 'Prouve les contrôles techniques (revues obligatoires, MFA, branches protégées).', 'config'),
  ('Politique de gestion des mots de passe / authentification', 'Fixe les exigences de robustesse, de MFA et de gestion des secrets.', 'policy'),
  ('Configuration de l''authentification multifacteur', 'Prouve l''activation du MFA sur les accès critiques et distants.', 'config'),
  ('Paramètres de la politique de mots de passe (annuaire/IdP)', 'Montre les règles techniques appliquées (longueur, verrouillage, complexité).', 'config'),
  ('Plan de capacité', 'Planifie les besoins en ressources (stockage, CPU, bande passante) selon la croissance prévue.', 'document'),
  ('Rapports de suivi de la capacité et des performances', 'Montrent l''utilisation réelle des ressources et les seuils d''alerte.', 'record'),
  ('Politique anti-malware', 'Définit les protections contre les codes malveillants et les responsabilités associées.', 'policy'),
  ('Console antivirus / EDR : couverture et état des mises à jour', 'Prouve le déploiement et la mise à jour des protections sur le parc.', 'config'),
  ('Rapport des détections et traitements de malwares', 'Montre les alertes détectées et leur traitement.', 'record'),
  ('Rapports de gestion des vulnérabilités', 'Prouvent les scans réguliers, la priorisation et le suivi des corrections.', 'record'),
  ('Procédure de gestion des vulnérabilités et des correctifs', 'Décrit la veille, l''évaluation et les délais de correction.', 'document'),
  ('Rapport de conformité des correctifs (patch management)', 'Montre le niveau d''application des correctifs sur les systèmes.', 'record'),
  ('Standards de configuration sécurisée (durcissement)', 'Définissent les configurations de référence pour systèmes, réseaux et applications.', 'document'),
  ('Rapport de conformité aux configurations de référence', 'Prouve la conformité des systèmes aux baselines et les écarts traités.', 'record'),
  ('Procédure de gestion des changements', 'Encadre la modification des configurations.', 'document'),
  ('Procédure de suppression sécurisée des informations', 'Définit les méthodes d''effacement et les durées de conservation applicables.', 'document'),
  ('Certificats / PV de destruction ou d''effacement', 'Prouvent l''effacement effectif de données ou supports.', 'record'),
  ('Politique de masquage et pseudonymisation des données', 'Définit les cas et techniques de masquage des données sensibles.', 'policy'),
  ('Preuve de configuration du masquage (extraits anonymisés)', 'Montre l''application effective du masquage ou de la pseudonymisation.', 'config'),
  ('Politique de prévention des fuites de données', 'Définit les règles de protection contre l''exfiltration d''informations.', 'policy'),
  ('Configuration des outils DLP / contrôles de sortie', 'Prouve les règles DLP actives (messagerie, web, supports amovibles).', 'config'),
  ('Rapport des incidents et alertes DLP', 'Montre la détection et le traitement des tentatives de fuite.', 'record'),
  ('Politique de sauvegarde', 'Définit périmètre, fréquence, rétention et protection des sauvegardes.', 'policy'),
  ('Rapports de tests de restauration', 'Prouvent la capacité à restaurer les données sauvegardées.', 'record'),
  ('Journaux d''exécution des sauvegardes', 'Montrent le succès ou l''échec des sauvegardes planifiées.', 'record'),
  ('Architecture de redondance et de haute disponibilité', 'Décrit les composants redondés et les mécanismes de bascule.', 'document'),
  ('Rapports de tests de bascule (failover)', 'Prouvent le fonctionnement effectif de la redondance.', 'record'),
  ('Journaux d''activité système', 'Preuves de la collecte des événements de sécurité et d''activité.', 'record'),
  ('Journaux d''administration', 'Tracent les actions des administrateurs et opérateurs.', 'record'),
  ('Politique de journalisation et de conservation des logs', 'Définit les événements journalisés, leur protection et durée de rétention.', 'policy'),
  ('Procédure de surveillance et de détection d''anomalies', 'Définit les périmètres surveillés, seuils et circuits d''escalade.', 'document'),
  ('Configuration des outils de supervision / SIEM', 'Prouve les règles de détection et d''alerte actives.', 'config'),
  ('Rapports d''alertes et de revue de surveillance', 'Montrent le traitement des alertes détectées.', 'record'),
  ('Configuration NTP des systèmes', 'Prouve la synchronisation des horloges sur une source de temps de référence.', 'config'),
  ('Document d''architecture de la source de temps', 'Décrit les serveurs de temps de référence utilisés.', 'document'),
  ('Liste des utilitaires privilégiés autorisés', 'Recense les outils système à privilèges et leurs utilisateurs habilités.', 'record'),
  ('Procédure de contrôle des utilitaires privilégiés', 'Définit les restrictions d''usage et la journalisation associée.', 'document'),
  ('Procédure d''installation de logiciels', 'Définit les règles et approbations pour installer des logiciels en production.', 'document'),
  ('Liste des logiciels autorisés (liste blanche)', 'Recense les logiciels approuvés sur les systèmes opérationnels.', 'record'),
  ('Schéma d''architecture réseau', 'Décrit la topologie réseau et les dispositifs de protection.', 'document'),
  ('Configuration des pare-feu et équipements réseau', 'Prouve les règles de filtrage et de protection appliquées.', 'config'),
  ('Rapport de revue des règles de filtrage', 'Montre la revue périodique des règles pare-feu.', 'record'),
  ('Contrats et SLA des services réseau', 'Définissent niveaux de service et exigences de sécurité des fournisseurs réseau.', 'document'),
  ('Rapports de suivi des SLA fournisseurs réseau', 'Prouvent le contrôle des niveaux de service et de sécurité fournis.', 'record'),
  ('Plan de cloisonnement réseau', 'Décrit la segmentation en zones (VLAN, DMZ) et les flux autorisés.', 'document'),
  ('Configuration des VLAN et règles inter-zones', 'Prouve la mise en œuvre effective du cloisonnement.', 'config'),
  ('Politique de filtrage web', 'Définit les catégories de sites bloquées et les règles d''accès à Internet.', 'policy'),
  ('Configuration du proxy / passerelle de filtrage web', 'Prouve le filtrage actif des accès Internet.', 'config'),
  ('Politique de chiffrement', 'Définit les algorithmes, usages et gestion des clés cryptographiques.', 'policy'),
  ('Procédure de gestion des clés cryptographiques', 'Décrit la génération, le stockage, la rotation et la révocation des clés.', 'document'),
  ('Configuration du chiffrement en transit et au repos', 'Prouve l''application effective du chiffrement (TLS, disques, bases).', 'config'),
  ('Procédure de développement sécurisé', 'Définit les règles de sécurité à chaque phase du cycle de développement.', 'policy'),
  ('Preuves d''application du SDLC sécurisé (jalons, revues)', 'Montrent la mise en œuvre des étapes de sécurité sur des projets réels.', 'record'),
  ('Spécifications d''exigences de sécurité applicatives', 'Documentent les exigences de sécurité identifiées pour les applications.', 'document'),
  ('Analyse de risques applicative', 'Justifie les exigences de sécurité retenues pour chaque application.', 'record'),
  ('Principes d''architecture et d''ingénierie sécurisées', 'Formalisent les principes de sécurité dès la conception.', 'document'),
  ('Dossiers d''architecture de sécurité de systèmes', 'Montrent l''application des principes sur des systèmes concrets.', 'record'),
  ('Standard de codage sécurisé', 'Fixe les bonnes pratiques de codage et la prévention des vulnérabilités.', 'document'),
  ('Rapports d''analyse statique / revue de code', 'Prouvent l''application des pratiques de codage sécurisé.', 'record'),
  ('Plan de tests de sécurité', 'Définit les tests de sécurité à réaliser avant mise en production.', 'document'),
  ('Rapports de tests d''intrusion et de tests de sécurité', 'Prouvent la réalisation des tests et le traitement des constats.', 'record'),
  ('PV de recette incluant la sécurité', 'Atteste l''acceptation formelle avec critères de sécurité.', 'record'),
  ('Contrat avec exigences de sécurité pour le développement externalisé', 'Formalise les obligations de sécurité du prestataire de développement.', 'document'),
  ('Rapports de revue et d''acceptation des livrables externalisés', 'Prouvent le contrôle de la sécurité du code livré par le sous-traitant.', 'record'),
  ('Schéma des environnements dev / test / production', 'Décrit la séparation des environnements.', 'document'),
  ('Matrice d''accès par environnement', 'Montre les droits distincts selon les environnements.', 'record'),
  ('Registre des changements', 'Trace les changements réalisés avec leurs approbations.', 'record'),
  ('Comptes rendus du comité de changements (CAB)', 'Prouvent l''évaluation et la validation des changements significatifs.', 'record'),
  ('Procédure de protection des données de test', 'Définit les règles de sélection, d''anonymisation et de suppression des données de test.', 'document'),
  ('Preuve d''anonymisation des jeux de données de test', 'Montre que les données de test n''exposent pas de données réelles.', 'record'),
  ('Procédure de planification des audits techniques', 'Encadre les tests et audits techniques sur les systèmes en production.', 'document'),
  ('Accords d''audit et périmètres autorisés', 'Prouvent l''autorisation préalable et la limitation du périmètre d''audit.', 'record')
) as t(name, descr, kind)
where not exists (select 1 from public.evidence_items ei where ei.framework_id = '00000000-0000-0000-0000-000000000010' and ei.name = t.name);

insert into public.evidence_catalog (control_id, evidence_item_id, name, description, is_required, kind, sort_order)
select c.id, ei.id, r.name, r.descr, r.is_req, r.kind, r.ord
from (values
  ('A.5.1', 'Politique de sécurité de l''information', 'Prouve que la politique est définie, approuvée par la direction, publiée et communiquée.', true, 'policy', 1),
  ('A.5.1', 'Preuve de communication de la politique', 'Prouve la diffusion et la prise de connaissance par le personnel et les parties intéressées.', false, 'record', 2),
  ('A.5.1', 'Historique de revue de la politique', 'Prouve la revue à intervalles planifiés ou lors de changements majeurs.', false, 'record', 3),
  ('A.5.2', 'Matrice des rôles et responsabilités SSI (RACI)', 'Prouve l''attribution formelle des rôles et responsabilités de sécurité.', true, 'document', 1),
  ('A.5.2', 'Lettres de nomination RSSI et responsables sécurité', 'Prouve la désignation formelle des personnes responsables.', true, 'record', 2),
  ('A.5.2', 'Organigramme du SMSI', 'Prouve la structure et les lignes de reporting de la sécurité.', false, 'document', 3),
  ('A.5.3', 'Matrice de séparation des tâches', 'Prouve l''identification des tâches et responsabilités conflictuelles et leur séparation.', true, 'document', 1),
  ('A.5.3', 'Politique de contrôle d''accès', 'Prouve l''intégration de la séparation des tâches dans les droits d''accès.', false, 'policy', 2),
  ('A.5.3', 'Extrait des profils et habilitations applicatifs', 'Prouve l''absence de cumul de droits incompatibles dans les systèmes.', false, 'config', 3),
  ('A.5.4', 'Comptes rendus de revue de direction', 'Prouve l''engagement de la direction et le suivi de l''application de la politique.', true, 'record', 1),
  ('A.5.4', 'Politique de sécurité de l''information', 'Prouve que la direction exige l''application de la politique.', false, 'policy', 2),
  ('A.5.4', 'Engagements de la direction (lettre d''engagement, objectifs SMSI)', 'Prouve que la direction exige le respect des règles de sécurité par le personnel.', false, 'document', 3),
  ('A.5.5', 'Liste des contacts autorités compétentes', 'Prouve l''identification des autorités pertinentes (CERT, régulateur, police, protection des données) et leurs coordonnées.', true, 'document', 1),
  ('A.5.5', 'Procédure de contact avec les autorités', 'Prouve les conditions et responsables des contacts avec les autorités.', true, 'document', 2),
  ('A.5.5', 'Procédure de gestion des incidents', 'Prouve l''intégration des notifications aux autorités dans la gestion des incidents.', false, 'document', 3),
  ('A.5.6', 'Liste des groupes d''intérêt et abonnements', 'Prouve l''adhésion à des forums, associations ou listes de diffusion spécialisés en sécurité.', true, 'record', 1),
  ('A.5.6', 'Preuves de participation (conférences, forums, newsletters)', 'Prouve l''implication effective dans la veille et le partage avec la communauté sécurité.', false, 'record', 2),
  ('A.5.7', 'Procédure de veille sur les menaces', 'Prouve le processus de collecte, d''analyse et de diffusion du renseignement sur les menaces.', true, 'document', 1),
  ('A.5.7', 'Rapports ou bulletins de veille menaces', 'Prouve la collecte et l''analyse effectives (CERT, CTI, éditeurs).', true, 'record', 2),
  ('A.5.7', 'Registre des risques', 'Prouve la prise en compte des menaces identifiées dans l''appréciation des risques.', false, 'record', 3),
  ('A.5.8', 'Méthodologie de gestion de projet intégrant la sécurité', 'Prouve que les exigences de sécurité sont intégrées dans le cycle de vie des projets.', true, 'document', 1),
  ('A.5.8', 'Analyses de risques de projets', 'Prouve l''évaluation des risques de sécurité sur des projets échantillonnés.', true, 'record', 2),
  ('A.5.8', 'Checklist ou jalons de sécurité de projet', 'Prouve la validation de la sécurité aux jalons des projets.', false, 'record', 3),
  ('A.5.9', 'Inventaire des actifs', 'Prouve l''identification et la tenue à jour des informations et actifs associés avec leurs propriétaires.', true, 'record', 1),
  ('A.5.9', 'Procédure de gestion de l''inventaire des actifs', 'Prouve les règles d''identification, de propriété et de mise à jour de l''inventaire.', false, 'document', 2),
  ('A.5.10', 'Chartes (confidentialité, utilisateur)', 'Prouve que les règles d''utilisation acceptable sont formalisées et acceptées par les utilisateurs.', true, 'policy', 1),
  ('A.5.10', 'Politique d''utilisation acceptable des actifs', 'Prouve les règles d''usage des informations et actifs (messagerie, internet, mobiles, supports).', true, 'policy', 2),
  ('A.5.10', 'Preuves d''acceptation par les utilisateurs', 'Prouve la signature ou l''acceptation des règles par le personnel.', false, 'record', 3),
  ('A.5.11', 'Procédure de départ et de mobilité du personnel', 'Prouve le processus de restitution des actifs en fin de contrat ou de changement de poste.', true, 'document', 1),
  ('A.5.11', 'Fiches de restitution des actifs signées', 'Prouve la restitution effective des équipements, badges et supports par échantillon de départs.', true, 'record', 2),
  ('A.5.11', 'Inventaire des actifs', 'Prouve la mise à jour de l''affectation des actifs après restitution.', false, 'record', 3),
  ('A.5.12', 'Procédure de classification de l''information', 'Prouve le schéma de classification de l''information selon confidentialité, intégrité et disponibilité.', true, 'document', 1),
  ('A.5.12', 'Registre ou exemples d''informations classifiées', 'Prouve l''application effective de la classification aux informations.', false, 'record', 2),
  ('A.5.13', 'Procédure de marquage des informations', 'Prouve les règles de marquage et d''étiquetage selon la classification.', true, 'document', 1),
  ('A.5.13', 'Procédure de classification de l''information', 'Prouve le lien entre niveaux de classification et marquage.', false, 'document', 2),
  ('A.5.13', 'Exemples de documents ou supports marqués', 'Prouve l''application effective du marquage.', true, 'record', 3),
  ('A.5.14', 'Politique de transfert de l''information', 'Prouve les règles de transfert sécurisé (messagerie, échange de fichiers, supports physiques).', true, 'policy', 1),
  ('A.5.14', 'Accords de transfert d''information avec les tiers', 'Prouve les règles convenues de transfert avec les parties externes (NDA, accords d''échange).', true, 'document', 2),
  ('A.5.14', 'Configuration du chiffrement des échanges', 'Prouve les moyens techniques de protection des transferts (TLS, SFTP, chiffrement messagerie).', false, 'config', 3),
  ('A.5.15', 'Politique de contrôle d''accès', 'Prouve les règles de contrôle d''accès physique et logique fondées sur les exigences métier et de sécurité.', true, 'policy', 1),
  ('A.5.15', 'Matrice d''accès par profil', 'Prouve l''application du besoin d''en connaître et du moindre privilège.', false, 'document', 2),
  ('A.5.16', 'Procédure de gestion du cycle de vie des identités', 'Prouve les processus de création, modification et suppression des identités.', true, 'document', 1),
  ('A.5.16', 'Liste des comptes et identités (annuaire)', 'Prouve l''unicité des identités et l''absence de comptes orphelins ou génériques non maîtrisés.', true, 'config', 2),
  ('A.5.16', 'Demandes d''arrivée et de départ échantillonnées', 'Prouve l''exécution effective du cycle de vie des identités.', false, 'record', 3),
  ('A.5.17', 'Politique de mots de passe et d''authentification', 'Prouve les exigences de robustesse, de renouvellement et d''authentification forte.', true, 'policy', 1),
  ('A.5.17', 'Configuration de la politique de mots de passe et de MFA', 'Prouve l''application technique des règles d''authentification dans les systèmes.', true, 'config', 2),
  ('A.5.17', 'Procédure d''attribution des secrets d''authentification', 'Prouve la remise sécurisée et la réinitialisation des secrets.', false, 'document', 3),
  ('A.5.18', 'Procédure de provisionnement et de révocation des droits', 'Prouve le processus d''attribution, de modification et de retrait des droits d''accès.', true, 'document', 1),
  ('A.5.18', 'Revues périodiques des droits d''accès', 'Prouve la revue régulière des droits par les propriétaires d''actifs.', true, 'record', 2),
  ('A.5.18', 'Demandes d''accès et de révocation échantillonnées', 'Prouve l''autorisation préalable et la révocation effective des droits.', false, 'record', 3),
  ('A.5.19', 'Politique fournisseurs', 'Prouve les exigences de sécurité définies pour la relation avec les fournisseurs.', true, 'policy', 1),
  ('A.5.19', 'Liste et classification des fournisseurs', 'Prouve l''identification des fournisseurs ayant accès aux informations et leur criticité.', true, 'record', 2),
  ('A.5.19', 'Appréciations de risques fournisseurs', 'Prouve l''évaluation des risques liés aux fournisseurs avant engagement.', false, 'record', 3),
  ('A.5.20', 'Clauses de sécurité contractuelles fournisseurs', 'Prouve l''inclusion d''exigences de sécurité dans les accords avec les fournisseurs.', true, 'document', 1),
  ('A.5.20', 'Contrats ou accords fournisseurs échantillonnés', 'Prouve la présence effective de clauses de sécurité, de confidentialité et d''audit.', true, 'record', 2),
  ('A.5.20', 'Politique fournisseurs', 'Prouve le cadre exigeant ces clauses.', false, 'policy', 3),
  ('A.5.21', 'Exigences de sécurité de la chaîne d''approvisionnement TIC', 'Prouve les exigences imposées aux fournisseurs TIC et à leurs sous-traitants.', true, 'document', 1),
  ('A.5.21', 'Clauses de sécurité contractuelles fournisseurs', 'Prouve la propagation des exigences de sécurité aux sous-traitants.', true, 'document', 2),
  ('A.5.21', 'Évaluation des risques de la chaîne d''approvisionnement', 'Prouve l''analyse des risques liés aux produits et services TIC.', false, 'record', 3),
  ('A.5.22', 'Rapports de suivi et de revue des fournisseurs', 'Prouve la surveillance régulière des niveaux de service et de sécurité des fournisseurs.', true, 'record', 1),
  ('A.5.22', 'Comptes rendus de comités de pilotage fournisseurs', 'Prouve les revues périodiques et le traitement des écarts.', false, 'record', 2),
  ('A.5.22', 'Procédure de gestion des changements fournisseurs', 'Prouve la maîtrise des changements de services et de leurs impacts sécurité.', false, 'document', 3),
  ('A.5.23', 'Politique d''utilisation des services cloud', 'Prouve les exigences d''acquisition, d''utilisation et de sortie des services cloud.', true, 'policy', 1),
  ('A.5.23', 'Registre des services cloud et responsabilités partagées', 'Prouve l''identification des services cloud utilisés et la répartition des responsabilités.', true, 'record', 2),
  ('A.5.23', 'Attestations de sécurité des fournisseurs cloud', 'Prouve les garanties du fournisseur (ISO 27001, SOC 2, rapports d''audit).', false, 'record', 3),
  ('A.5.24', 'Procédure de gestion des incidents', 'Prouve le processus défini de gestion des incidents, avec rôles et responsabilités.', true, 'document', 1),
  ('A.5.24', 'Organisation de la cellule de gestion des incidents', 'Prouve la désignation de l''équipe de réponse et des contacts d''astreinte.', true, 'document', 2),
  ('A.5.24', 'Grille de classification et d''escalade des incidents', 'Prouve les critères de gravité et les circuits d''escalade.', false, 'document', 3),
  ('A.5.25', 'Registre des incidents', 'Prouve l''évaluation et la catégorisation de chaque événement de sécurité.', true, 'record', 1),
  ('A.5.25', 'Critères de qualification des événements', 'Prouve les règles de décision pour qualifier un événement en incident.', true, 'document', 2),
  ('A.5.25', 'Procédure de gestion des incidents', 'Prouve le cadre d''évaluation des événements.', false, 'document', 3),
  ('A.5.26', 'Procédure de gestion des incidents', 'Prouve les procédures de réponse documentées (confinement, éradication, reprise).', true, 'document', 1),
  ('A.5.26', 'Registre des incidents', 'Prouve la réponse effective aux incidents avec actions, dates et responsables.', true, 'record', 2),
  ('A.5.26', 'Dossiers d''incidents échantillonnés', 'Prouve la traçabilité des actions de réponse et de clôture.', false, 'record', 3),
  ('A.5.27', 'Rapports de retour d''expérience post-incident', 'Prouve l''analyse des causes et les enseignements tirés des incidents.', true, 'record', 1),
  ('A.5.27', 'Registre des incidents', 'Prouve l''enregistrement des enseignements et actions correctives.', false, 'record', 2),
  ('A.5.27', 'Plan d''actions correctives issues des incidents', 'Prouve la mise en œuvre d''améliorations pour réduire la récurrence.', true, 'record', 3),
  ('A.5.28', 'Procédure de collecte et de préservation des preuves', 'Prouve les règles d''identification, collecte et conservation des preuves numériques.', true, 'document', 1),
  ('A.5.28', 'Registre de chaîne de traçabilité des preuves', 'Prouve l''intégrité et la traçabilité des preuves collectées lors d''incidents.', true, 'record', 2),
  ('A.5.28', 'Procédure de gestion des incidents', 'Prouve l''intégration de la collecte de preuves dans la gestion des incidents.', false, 'document', 3),
  ('A.5.29', 'Plan de continuité d''activité (PCA)', 'Prouve la planification du maintien de la sécurité de l''information en cas de perturbation.', true, 'document', 1),
  ('A.5.29', 'Plan de gestion de crise', 'Prouve les dispositions de gouvernance et de communication en situation de crise.', true, 'document', 2),
  ('A.5.29', 'Analyse d''impact sur l''activité (BIA)', 'Prouve l''identification des exigences de sécurité à maintenir pendant la perturbation.', false, 'document', 3),
  ('A.5.30', 'Plan de continuité d''activité (PCA)', 'Prouve la préparation de la continuité des activités critiques.', true, 'document', 1),
  ('A.5.30', 'Plan de reprise informatique (PRA) et objectifs RTO/RPO', 'Prouve la définition des exigences de reprise des systèmes TIC.', true, 'document', 2),
  ('A.5.30', 'Rapports de tests PCA/PRA', 'Prouve la vérification périodique de la capacité de continuité des TIC.', true, 'record', 3),
  ('A.5.31', 'Registre des exigences légales et réglementaires', 'Prouve l''identification et la mise à jour des exigences légales, réglementaires et contractuelles applicables.', true, 'record', 1),
  ('A.5.31', 'Procédure de veille réglementaire', 'Prouve le processus de suivi des évolutions applicables.', false, 'document', 2),
  ('A.5.31', 'Évaluation de conformité aux exigences applicables', 'Prouve la vérification de la prise en compte de ces exigences.', false, 'record', 3),
  ('A.5.32', 'Politique de protection de la propriété intellectuelle', 'Prouve les règles de respect des licences et droits de propriété intellectuelle.', true, 'policy', 1),
  ('A.5.32', 'Registre des licences logicielles', 'Prouve l''inventaire des licences acquises et leur utilisation conforme.', true, 'record', 2),
  ('A.5.32', 'Procédure de contrôle des logiciels installés', 'Prouve la maîtrise des logiciels non autorisés ou non licenciés.', false, 'document', 3),
  ('A.5.33', 'Politique de conservation et de protection des enregistrements', 'Prouve les durées de conservation et la protection contre perte, altération ou accès non autorisé.', true, 'policy', 1),
  ('A.5.33', 'Calendrier de conservation des enregistrements', 'Prouve les durées par type d''enregistrement conformément aux exigences légales.', true, 'document', 2),
  ('A.5.33', 'Configuration de sauvegarde et d''archivage', 'Prouve la protection technique des enregistrements.', false, 'config', 3),
  ('A.5.34', 'Politique de protection des données à caractère personnel', 'Prouve les règles de protection de la vie privée conformes à la réglementation applicable.', true, 'policy', 1),
  ('A.5.34', 'Registre des traitements de DCP', 'Prouve l''identification des traitements et des finalités des données personnelles.', true, 'record', 2),
  ('A.5.34', 'Désignation du DPO ou correspondant et déclarations à l''autorité', 'Prouve la gouvernance de la protection des données et les formalités réglementaires.', false, 'record', 3),
  ('A.5.35', 'Rapports d''audit interne SMSI', 'Prouve la revue indépendante de l''approche de sécurité par audit interne à intervalles planifiés.', true, 'record', 1),
  ('A.5.35', 'Rapports d''audit externe ou de certification', 'Prouve la revue indépendante par un tiers qualifié.', false, 'record', 2),
  ('A.5.35', 'Programme d''audit', 'Prouve la planification des revues indépendantes.', false, 'document', 3),
  ('A.5.36', 'Rapports de vérification de conformité aux politiques', 'Prouve les contrôles réguliers du respect des politiques et normes par les responsables.', true, 'record', 1),
  ('A.5.36', 'Revues techniques de conformité (durcissement, configurations)', 'Prouve la vérification de la conformité technique des systèmes.', false, 'record', 2),
  ('A.5.36', 'Rapports d''audit interne SMSI', 'Prouve la vérification de conformité dans le cadre de l''audit interne.', false, 'record', 3),
  ('A.5.37', 'Procédures d''exploitation documentées', 'Prouve la documentation des procédures opérationnelles et leur disponibilité pour le personnel concerné.', true, 'document', 1),
  ('A.5.37', 'Registre de gestion documentaire (versions, validation)', 'Prouve la maîtrise des versions et l''approbation des procédures.', false, 'record', 2),
  ('A.6.1', 'Procédure de vérification des antécédents', 'Prouve que des vérifications proportionnées au risque sont définies avant embauche.', true, 'document', 1),
  ('A.6.1', 'Échantillon de dossiers de recrutement avec vérifications', 'Prouve l''application effective des vérifications (casier, références, diplômes) sur des recrutements récents.', true, 'record', 2),
  ('A.6.1', 'Procédures RH (arrivée, mutation, départ)', 'Prouve l''intégration de la sélection dans le processus RH global.', false, 'document', 3),
  ('A.6.2', 'Modèle de contrat de travail avec clauses de sécurité', 'Prouve que les contrats imposent des responsabilités de sécurité de l''information.', true, 'document', 1),
  ('A.6.2', 'Chartes (confidentialité, utilisateur)', 'Prouve l''engagement formel des employés au respect des règles de sécurité.', true, 'document', 2),
  ('A.6.2', 'Contrats signés (échantillon)', 'Prouve que les clauses sont effectivement signées par le personnel.', false, 'record', 3),
  ('A.6.3', 'Plan de sensibilisation et formation', 'Prouve l''existence d''un programme planifié de sensibilisation et de formation.', true, 'document', 1),
  ('A.6.3', 'Registre des participations aux formations', 'Prouve la réalisation effective des sessions et la couverture du personnel.', true, 'record', 2),
  ('A.6.3', 'Supports de formation et résultats d''évaluation', 'Prouve le contenu dispensé et l''efficacité de la sensibilisation.', false, 'document', 3),
  ('A.6.4', 'Procédure disciplinaire sécurité', 'Prouve que les sanctions en cas de violation de la politique de sécurité sont définies et formalisées.', true, 'policy', 1),
  ('A.6.4', 'Règlement intérieur intégrant les sanctions', 'Prouve l''opposabilité des sanctions au personnel.', false, 'document', 2),
  ('A.6.4', 'Registre des cas disciplinaires liés à la sécurité', 'Prouve l''application du processus lors de violations avérées.', false, 'record', 3),
  ('A.6.5', 'Procédures RH (arrivée, mutation, départ)', 'Prouve que les obligations post-emploi et de changement de poste sont traitées.', true, 'document', 1),
  ('A.6.5', 'Checklists de départ signées', 'Prouve la restitution des actifs, le retrait des accès et le rappel des obligations de confidentialité.', true, 'record', 2),
  ('A.6.5', 'Clauses de confidentialité post-emploi', 'Prouve la persistance des obligations après la fin du contrat.', false, 'document', 3),
  ('A.6.6', 'Modèle d''accord de confidentialité (NDA)', 'Prouve l''existence d''un modèle reflétant les besoins de protection de l''information.', true, 'document', 1),
  ('A.6.6', 'NDA signés (employés, tiers)', 'Prouve la signature effective par le personnel et les parties externes.', true, 'record', 2),
  ('A.6.6', 'Chartes (confidentialité, utilisateur)', 'Prouve l''engagement de confidentialité des utilisateurs.', false, 'document', 3),
  ('A.6.7', 'Politique de télétravail et d''accès à distance', 'Prouve que les règles de sécurité du travail à distance sont définies.', true, 'policy', 1),
  ('A.6.7', 'Configuration VPN et authentification forte à distance', 'Prouve la mise en oeuvre technique de la sécurisation des accès distants.', true, 'config', 2),
  ('A.6.7', 'Liste des télétravailleurs autorisés', 'Prouve que le télétravail est autorisé et encadré.', false, 'record', 3),
  ('A.6.8', 'Procédure de signalement des événements de sécurité', 'Prouve que le canal et les modalités de signalement sont définis et connus.', true, 'document', 1),
  ('A.6.8', 'Registre des événements et incidents signalés', 'Prouve que les signalements sont effectivement reçus et traités.', true, 'record', 2),
  ('A.6.8', 'Plan de sensibilisation et formation', 'Prouve que le personnel est formé au signalement.', false, 'document', 3),
  ('A.7.1', 'Plan des zones sécurisées', 'Prouve la définition des périmètres et zones de sécurité physique.', true, 'document', 1),
  ('A.7.1', 'Politique de sécurité de l''information', 'Prouve le cadrage de la sécurité physique au niveau de la direction.', false, 'policy', 2),
  ('A.7.1', 'Rapport de visite des périmètres physiques', 'Prouve l''intégrité des barrières (portes, clôtures, murs) sur site.', false, 'record', 3),
  ('A.7.2', 'Registre des accès physiques', 'Prouve la traçabilité des entrées dans les locaux et zones sensibles.', true, 'record', 1),
  ('A.7.2', 'Liste des habilitations d''accès physique', 'Prouve que les droits d''accès aux locaux sont attribués et revus.', true, 'record', 2),
  ('A.7.2', 'Procédure d''accueil et d''accompagnement des visiteurs', 'Prouve le contrôle des visiteurs et des tiers.', false, 'document', 3),
  ('A.7.3', 'Plan des zones sécurisées', 'Prouve l''identification des bureaux et salles à protéger.', true, 'document', 1),
  ('A.7.3', 'Inventaire des clés et badges des locaux', 'Prouve la maîtrise des moyens de fermeture des bureaux et salles.', false, 'record', 2),
  ('A.7.3', 'Politique du poste de travail et bureau propre', 'Prouve les règles de protection des espaces de travail.', false, 'policy', 3),
  ('A.7.4', 'Cartographie des caméras et dispositifs de surveillance', 'Prouve la couverture de surveillance des zones sensibles.', true, 'document', 1),
  ('A.7.4', 'Procédure de conservation et revue des enregistrements vidéo', 'Prouve la gestion des enregistrements et leur revue.', true, 'policy', 2),
  ('A.7.4', 'Journaux d''alarmes et rapports de levée de doute', 'Prouve la détection et le traitement des intrusions.', false, 'record', 3),
  ('A.7.5', 'Analyse des risques physiques et environnementaux', 'Prouve l''identification des menaces (incendie, inondation, foudre) sur les sites.', true, 'document', 1),
  ('A.7.5', 'Rapports de vérification des équipements anti-incendie', 'Prouve la maintenance des détecteurs, extincteurs et systèmes d''extinction.', true, 'record', 2),
  ('A.7.5', 'Plan d''évacuation et comptes rendus d''exercices', 'Prouve la préparation aux sinistres.', false, 'record', 3),
  ('A.7.6', 'Procédure de travail en zone sécurisée', 'Prouve que les règles applicables en zone sécurisée sont définies.', true, 'policy', 1),
  ('A.7.6', 'Registre des accès physiques', 'Prouve la traçabilité des personnes intervenant en zone sécurisée.', true, 'record', 2),
  ('A.7.6', 'Plan des zones sécurisées', 'Prouve la délimitation des zones concernées.', false, 'document', 3),
  ('A.7.7', 'Politique du poste de travail et bureau propre', 'Prouve la définition des règles de bureau propre et d''écran vide.', true, 'policy', 1),
  ('A.7.7', 'Configuration du verrouillage automatique de session', 'Prouve la mise en oeuvre technique de l''écran vide.', true, 'config', 2),
  ('A.7.7', 'Rapports de contrôles de bureau propre', 'Prouve la vérification effective du respect de la politique.', false, 'record', 3),
  ('A.7.8', 'Inventaire des actifs', 'Prouve l''identification et la localisation des équipements.', true, 'record', 1),
  ('A.7.8', 'Plan d''implantation des équipements et salles techniques', 'Prouve le positionnement sécurisé des équipements sensibles.', true, 'document', 2),
  ('A.7.8', 'Plan des zones sécurisées', 'Prouve que les équipements critiques sont placés en zone protégée.', false, 'document', 3),
  ('A.7.9', 'Politique des équipements mobiles et hors site', 'Prouve que les règles de protection des actifs hors des locaux sont définies.', true, 'policy', 1),
  ('A.7.9', 'Configuration du chiffrement et de l''effacement à distance des postes mobiles', 'Prouve la protection technique des équipements nomades.', true, 'config', 2),
  ('A.7.9', 'Inventaire des actifs', 'Prouve le suivi des équipements sortis des locaux.', false, 'record', 3),
  ('A.7.10', 'Procédure de gestion des supports amovibles', 'Prouve les règles de classification, usage, transport et destruction des supports.', true, 'policy', 1),
  ('A.7.10', 'Configuration de blocage des ports USB et supports amovibles', 'Prouve le contrôle technique de l''usage des supports.', false, 'config', 2),
  ('A.7.10', 'Registre des supports de stockage et de leur mise au rebut', 'Prouve la traçabilité du cycle de vie des supports.', true, 'record', 3),
  ('A.7.11', 'Schéma des alimentations électriques et télécoms (onduleurs, groupe électrogène)', 'Prouve la redondance et la protection contre les coupures.', true, 'document', 1),
  ('A.7.11', 'Rapports de test des onduleurs et du groupe électrogène', 'Prouve le bon fonctionnement des services généraux de secours.', true, 'record', 2),
  ('A.7.11', 'Plan de maintenance des équipements', 'Prouve l''entretien planifié des installations de soutien.', false, 'document', 3),
  ('A.7.12', 'Plan de câblage et schéma de brassage', 'Prouve la cartographie et la protection des câbles réseau et électriques.', true, 'document', 1),
  ('A.7.12', 'Rapport d''inspection des locaux techniques et baies', 'Prouve la protection physique des câbles et des accès aux baies.', false, 'record', 2),
  ('A.7.13', 'Plan de maintenance des équipements', 'Prouve la planification de la maintenance préventive.', true, 'document', 1),
  ('A.7.13', 'Rapports d''intervention et contrats de maintenance', 'Prouve la réalisation de la maintenance préventive et corrective par du personnel autorisé.', true, 'record', 2),
  ('A.7.13', 'Inventaire des actifs', 'Prouve la couverture des équipements dans le plan de maintenance.', false, 'record', 3),
  ('A.7.14', 'Procédure de mise au rebut et de réutilisation du matériel', 'Prouve que l''effacement sécurisé avant rebut ou réutilisation est défini.', true, 'policy', 1),
  ('A.7.14', 'Certificats d''effacement ou de destruction', 'Prouve l''effacement effectif des données avant sortie du matériel.', true, 'record', 2),
  ('A.7.14', 'Inventaire des actifs', 'Prouve le suivi des équipements mis au rebut ou réaffectés.', false, 'record', 3),
  ('A.8.1', 'Politique de sécurité des terminaux (postes et mobiles)', 'Définit les exigences de sécurité applicables aux postes de travail et appareils mobiles (chiffrement, verrouillage, MDM, BYOD).', true, 'policy', 1),
  ('A.8.1', 'Export de la console MDM / gestion des postes', 'Prouve l''application effective des configurations de sécurité sur le parc de terminaux.', true, 'config', 2),
  ('A.8.1', 'Inventaire des actifs', 'Recense les terminaux utilisateurs et leur affectation.', false, 'record', 3),
  ('A.8.2', 'Procédure de gestion des comptes à privilèges', 'Décrit l''attribution, l''approbation, la revue et le retrait des droits privilégiés.', true, 'document', 1),
  ('A.8.2', 'Liste des comptes à privilèges', 'Recense les comptes administrateurs avec leur justification et leur titulaire.', true, 'record', 2),
  ('A.8.2', 'Rapport de revue des droits d''accès', 'Prouve la revue périodique des droits privilégiés.', false, 'record', 3),
  ('A.8.3', 'Politique de contrôle d''accès', 'Établit les règles d''accès fondées sur le besoin d''en connaître.', true, 'policy', 1),
  ('A.8.3', 'Registre des habilitations / matrice des accès', 'Documente les droits d''accès attribués par rôle et par ressource.', true, 'record', 2),
  ('A.8.3', 'Configuration des permissions sur les ressources sensibles', 'Montre la restriction effective des accès aux données sensibles (ACL, partages).', false, 'config', 3),
  ('A.8.4', 'Liste des accès aux dépôts de code source', 'Montre les utilisateurs et droits (lecture/écriture) sur les dépôts de code.', true, 'record', 1),
  ('A.8.4', 'Configuration de protection des branches et du dépôt', 'Prouve les contrôles techniques (revues obligatoires, MFA, branches protégées).', true, 'config', 2),
  ('A.8.4', 'Politique de contrôle d''accès', 'Encadre l''accès au code source et aux outils de développement.', false, 'policy', 3),
  ('A.8.5', 'Politique de gestion des mots de passe / authentification', 'Fixe les exigences de robustesse, de MFA et de gestion des secrets.', true, 'policy', 1),
  ('A.8.5', 'Configuration de l''authentification multifacteur', 'Prouve l''activation du MFA sur les accès critiques et distants.', true, 'config', 2),
  ('A.8.5', 'Paramètres de la politique de mots de passe (annuaire/IdP)', 'Montre les règles techniques appliquées (longueur, verrouillage, complexité).', false, 'config', 3),
  ('A.8.6', 'Plan de capacité', 'Planifie les besoins en ressources (stockage, CPU, bande passante) selon la croissance prévue.', true, 'document', 1),
  ('A.8.6', 'Rapports de suivi de la capacité et des performances', 'Montrent l''utilisation réelle des ressources et les seuils d''alerte.', true, 'record', 2),
  ('A.8.7', 'Politique anti-malware', 'Définit les protections contre les codes malveillants et les responsabilités associées.', true, 'policy', 1),
  ('A.8.7', 'Console antivirus / EDR : couverture et état des mises à jour', 'Prouve le déploiement et la mise à jour des protections sur le parc.', true, 'config', 2),
  ('A.8.7', 'Rapport des détections et traitements de malwares', 'Montre les alertes détectées et leur traitement.', false, 'record', 3),
  ('A.8.8', 'Rapports de gestion des vulnérabilités', 'Prouvent les scans réguliers, la priorisation et le suivi des corrections.', true, 'record', 1),
  ('A.8.8', 'Procédure de gestion des vulnérabilités et des correctifs', 'Décrit la veille, l''évaluation et les délais de correction.', true, 'document', 2),
  ('A.8.8', 'Rapport de conformité des correctifs (patch management)', 'Montre le niveau d''application des correctifs sur les systèmes.', false, 'record', 3),
  ('A.8.9', 'Standards de configuration sécurisée (durcissement)', 'Définissent les configurations de référence pour systèmes, réseaux et applications.', true, 'document', 1),
  ('A.8.9', 'Rapport de conformité aux configurations de référence', 'Prouve la conformité des systèmes aux baselines et les écarts traités.', true, 'record', 2),
  ('A.8.9', 'Procédure de gestion des changements', 'Encadre la modification des configurations.', false, 'document', 3),
  ('A.8.10', 'Procédure de suppression sécurisée des informations', 'Définit les méthodes d''effacement et les durées de conservation applicables.', true, 'document', 1),
  ('A.8.10', 'Certificats / PV de destruction ou d''effacement', 'Prouvent l''effacement effectif de données ou supports.', true, 'record', 2),
  ('A.8.11', 'Politique de masquage et pseudonymisation des données', 'Définit les cas et techniques de masquage des données sensibles.', true, 'policy', 1),
  ('A.8.11', 'Preuve de configuration du masquage (extraits anonymisés)', 'Montre l''application effective du masquage ou de la pseudonymisation.', true, 'config', 2),
  ('A.8.12', 'Politique de prévention des fuites de données', 'Définit les règles de protection contre l''exfiltration d''informations.', true, 'policy', 1),
  ('A.8.12', 'Configuration des outils DLP / contrôles de sortie', 'Prouve les règles DLP actives (messagerie, web, supports amovibles).', true, 'config', 2),
  ('A.8.12', 'Rapport des incidents et alertes DLP', 'Montre la détection et le traitement des tentatives de fuite.', false, 'record', 3),
  ('A.8.13', 'Politique de sauvegarde', 'Définit périmètre, fréquence, rétention et protection des sauvegardes.', true, 'policy', 1),
  ('A.8.13', 'Rapports de tests de restauration', 'Prouvent la capacité à restaurer les données sauvegardées.', true, 'record', 2),
  ('A.8.13', 'Journaux d''exécution des sauvegardes', 'Montrent le succès ou l''échec des sauvegardes planifiées.', false, 'record', 3),
  ('A.8.14', 'Architecture de redondance et de haute disponibilité', 'Décrit les composants redondés et les mécanismes de bascule.', true, 'document', 1),
  ('A.8.14', 'Rapports de tests de bascule (failover)', 'Prouvent le fonctionnement effectif de la redondance.', true, 'record', 2),
  ('A.8.15', 'Journaux d''activité système', 'Preuves de la collecte des événements de sécurité et d''activité.', true, 'record', 1),
  ('A.8.15', 'Journaux d''administration', 'Tracent les actions des administrateurs et opérateurs.', true, 'record', 2),
  ('A.8.15', 'Politique de journalisation et de conservation des logs', 'Définit les événements journalisés, leur protection et durée de rétention.', false, 'policy', 3),
  ('A.8.16', 'Procédure de surveillance et de détection d''anomalies', 'Définit les périmètres surveillés, seuils et circuits d''escalade.', true, 'document', 1),
  ('A.8.16', 'Configuration des outils de supervision / SIEM', 'Prouve les règles de détection et d''alerte actives.', true, 'config', 2),
  ('A.8.16', 'Rapports d''alertes et de revue de surveillance', 'Montrent le traitement des alertes détectées.', false, 'record', 3),
  ('A.8.17', 'Configuration NTP des systèmes', 'Prouve la synchronisation des horloges sur une source de temps de référence.', true, 'config', 1),
  ('A.8.17', 'Document d''architecture de la source de temps', 'Décrit les serveurs de temps de référence utilisés.', false, 'document', 2),
  ('A.8.18', 'Liste des utilitaires privilégiés autorisés', 'Recense les outils système à privilèges et leurs utilisateurs habilités.', true, 'record', 1),
  ('A.8.18', 'Procédure de contrôle des utilitaires privilégiés', 'Définit les restrictions d''usage et la journalisation associée.', true, 'document', 2),
  ('A.8.18', 'Journaux d''administration', 'Tracent l''usage des utilitaires privilégiés.', false, 'record', 3),
  ('A.8.19', 'Procédure d''installation de logiciels', 'Définit les règles et approbations pour installer des logiciels en production.', true, 'document', 1),
  ('A.8.19', 'Liste des logiciels autorisés (liste blanche)', 'Recense les logiciels approuvés sur les systèmes opérationnels.', true, 'record', 2),
  ('A.8.19', 'Procédure de gestion des changements', 'Encadre les déploiements sur les systèmes opérationnels.', false, 'document', 3),
  ('A.8.20', 'Schéma d''architecture réseau', 'Décrit la topologie réseau et les dispositifs de protection.', true, 'document', 1),
  ('A.8.20', 'Configuration des pare-feu et équipements réseau', 'Prouve les règles de filtrage et de protection appliquées.', true, 'config', 2),
  ('A.8.20', 'Rapport de revue des règles de filtrage', 'Montre la revue périodique des règles pare-feu.', false, 'record', 3),
  ('A.8.21', 'Contrats et SLA des services réseau', 'Définissent niveaux de service et exigences de sécurité des fournisseurs réseau.', true, 'document', 1),
  ('A.8.21', 'Rapports de suivi des SLA fournisseurs réseau', 'Prouvent le contrôle des niveaux de service et de sécurité fournis.', false, 'record', 2),
  ('A.8.22', 'Plan de cloisonnement réseau', 'Décrit la segmentation en zones (VLAN, DMZ) et les flux autorisés.', true, 'document', 1),
  ('A.8.22', 'Configuration des VLAN et règles inter-zones', 'Prouve la mise en œuvre effective du cloisonnement.', true, 'config', 2),
  ('A.8.23', 'Politique de filtrage web', 'Définit les catégories de sites bloquées et les règles d''accès à Internet.', true, 'policy', 1),
  ('A.8.23', 'Configuration du proxy / passerelle de filtrage web', 'Prouve le filtrage actif des accès Internet.', true, 'config', 2),
  ('A.8.24', 'Politique de chiffrement', 'Définit les algorithmes, usages et gestion des clés cryptographiques.', true, 'policy', 1),
  ('A.8.24', 'Procédure de gestion des clés cryptographiques', 'Décrit la génération, le stockage, la rotation et la révocation des clés.', true, 'document', 2),
  ('A.8.24', 'Configuration du chiffrement en transit et au repos', 'Prouve l''application effective du chiffrement (TLS, disques, bases).', false, 'config', 3),
  ('A.8.25', 'Procédure de développement sécurisé', 'Définit les règles de sécurité à chaque phase du cycle de développement.', true, 'policy', 1),
  ('A.8.25', 'Preuves d''application du SDLC sécurisé (jalons, revues)', 'Montrent la mise en œuvre des étapes de sécurité sur des projets réels.', false, 'record', 2),
  ('A.8.26', 'Spécifications d''exigences de sécurité applicatives', 'Documentent les exigences de sécurité identifiées pour les applications.', true, 'document', 1),
  ('A.8.26', 'Analyse de risques applicative', 'Justifie les exigences de sécurité retenues pour chaque application.', false, 'record', 2),
  ('A.8.27', 'Principes d''architecture et d''ingénierie sécurisées', 'Formalisent les principes de sécurité dès la conception.', true, 'document', 1),
  ('A.8.27', 'Dossiers d''architecture de sécurité de systèmes', 'Montrent l''application des principes sur des systèmes concrets.', false, 'record', 2),
  ('A.8.28', 'Standard de codage sécurisé', 'Fixe les bonnes pratiques de codage et la prévention des vulnérabilités.', true, 'document', 1),
  ('A.8.28', 'Rapports d''analyse statique / revue de code', 'Prouvent l''application des pratiques de codage sécurisé.', true, 'record', 2),
  ('A.8.28', 'Procédure de développement sécurisé', 'Cadre global des pratiques de développement.', false, 'policy', 3),
  ('A.8.29', 'Plan de tests de sécurité', 'Définit les tests de sécurité à réaliser avant mise en production.', true, 'document', 1),
  ('A.8.29', 'Rapports de tests d''intrusion et de tests de sécurité', 'Prouvent la réalisation des tests et le traitement des constats.', true, 'record', 2),
  ('A.8.29', 'PV de recette incluant la sécurité', 'Atteste l''acceptation formelle avec critères de sécurité.', false, 'record', 3),
  ('A.8.30', 'Contrat avec exigences de sécurité pour le développement externalisé', 'Formalise les obligations de sécurité du prestataire de développement.', true, 'document', 1),
  ('A.8.30', 'Rapports de revue et d''acceptation des livrables externalisés', 'Prouvent le contrôle de la sécurité du code livré par le sous-traitant.', true, 'record', 2),
  ('A.8.31', 'Schéma des environnements dev / test / production', 'Décrit la séparation des environnements.', true, 'document', 1),
  ('A.8.31', 'Matrice d''accès par environnement', 'Montre les droits distincts selon les environnements.', true, 'record', 2),
  ('A.8.31', 'Plan de cloisonnement réseau', 'Prouve l''isolation réseau entre environnements.', false, 'document', 3),
  ('A.8.32', 'Procédure de gestion des changements', 'Définit les étapes de demande, évaluation, approbation et déploiement.', true, 'document', 1),
  ('A.8.32', 'Registre des changements', 'Trace les changements réalisés avec leurs approbations.', true, 'record', 2),
  ('A.8.32', 'Comptes rendus du comité de changements (CAB)', 'Prouvent l''évaluation et la validation des changements significatifs.', false, 'record', 3),
  ('A.8.33', 'Procédure de protection des données de test', 'Définit les règles de sélection, d''anonymisation et de suppression des données de test.', true, 'document', 1),
  ('A.8.33', 'Preuve d''anonymisation des jeux de données de test', 'Montre que les données de test n''exposent pas de données réelles.', false, 'record', 2),
  ('A.8.34', 'Procédure de planification des audits techniques', 'Encadre les tests et audits techniques sur les systèmes en production.', true, 'document', 1),
  ('A.8.34', 'Accords d''audit et périmètres autorisés', 'Prouvent l''autorisation préalable et la limitation du périmètre d''audit.', true, 'record', 2)
) as r(code, name, descr, is_req, kind, ord)
join public.controls c on c.code = r.code
  and c.domain_id in (select id from public.domains where framework_id = '00000000-0000-0000-0000-000000000010')
join public.evidence_items ei on ei.name = r.name and ei.framework_id = '00000000-0000-0000-0000-000000000010'
where not exists (
  select 1 from public.evidence_catalog ec where ec.control_id = c.id and ec.evidence_item_id = ei.id
);
