-- 00284 — Constats-types personnalisés (DUEDIL).
insert into public.finding_templates (scope, control_id, classification, description, risks, recommendations)
select 'platform', c.id, 'minor_nc', t.descr, t.risks, t.recos
from (values
  ('PT.01', 'Les choix technologiques (langages, frameworks, bases de données) ne sont ni documentés ni justifiés, et le cycle de vie des versions utilisées n''est pas suivi.', ARRAY['Difficulté pour l''investisseur à évaluer la pérennité et le recrutement autour de la stack','Risque de technologies obsolètes ou de niche à fort coût de maintenance'], ARRAY['Documenter la stack avec la justification de chaque choix et les versions en vigueur','Établir une matrice de risque (support, communauté, vivier de compétences) par technologie']),
  ('PT.02', 'L''architecture logicielle n''est pas formalisée par des schémas à jour (composants, flux, dépendances) et ne peut être expliquée que oralement par l''équipe.', ARRAY['Compréhension partielle du système lors de l''intégration ou de la reprise par un tiers','Évolutions coûteuses et risquées faute de vision partagée des couplages'], ARRAY['Produire des schémas d''architecture (contexte, composants, déploiement) versionnés avec le code','Consigner les décisions structurantes dans des ADR']),
  ('PT.03', 'Les standards de code, le linting et les revues de code ne sont pas appliqués de façon systématique avant intégration.', ARRAY['Hétérogénéité et baisse de la qualité du code au fil du temps','Défauts et vulnérabilités détectés tardivement en production'], ARRAY['Imposer des revues de code obligatoires via des règles de protection de branche','Mettre en place linter et formateur automatiques dans la CI']),
  ('PT.04', 'La couverture de tests automatisés est faible ou non mesurée, et les parcours critiques ne sont pas protégés par des tests d''intégration ou E2E.', ARRAY['Régressions fréquentes à chaque livraison','Refactorisations risquées et ralenties'], ARRAY['Mesurer la couverture et fixer un seuil minimal sur les modules critiques','Ajouter des tests d''intégration et E2E sur les parcours à forte valeur']),
  ('PT.05', 'Aucune stratégie de branching explicite n''est appliquée et l''historique Git est peu exploitable (commits volumineux, messages non significatifs).', ARRAY['Difficulté à tracer l''origine des changements et à revenir en arrière','Conflits de fusion et livraisons peu prévisibles'], ARRAY['Adopter une stratégie de branching documentée (trunk-based ou GitFlow)','Normaliser les messages de commit et protéger les branches principales']),
  ('PT.06', 'La documentation technique (README, API, procédures d''installation) est absente, incomplète ou obsolète.', ARRAY['Onboarding des nouveaux développeurs long et coûteux','Connaissance concentrée chez quelques personnes'], ARRAY['Rédiger un README d''installation et publier la documentation d''API (OpenAPI/Swagger)','Intégrer la mise à jour de la documentation à la définition de terminé']),
  ('PT.07', 'La capacité de l''architecture à absorber une croissance x10 en utilisateurs et en données n''a pas été évaluée (aucun test de charge ni étude de dimensionnement).', ARRAY['Dégradation du service lors d''une montée en charge','Surcoûts imprévus pour adapter l''architecture après levée de fonds'], ARRAY['Réaliser des tests de charge sur les parcours critiques','Identifier les goulots d''étranglement (base, état partagé, traitements synchrones)']),
  ('PT.08', 'Les performances applicatives (temps de réponse, requêtes lentes) ne sont pas mesurées ni suivies par des indicateurs et seuils définis.', ARRAY['Mauvaise expérience utilisateur non détectée et attrition','Problèmes de performance découverts seulement via les plaintes clients'], ARRAY['Instrumenter les temps de réponse (p95/p99) et les requêtes lentes','Définir des objectifs de performance et les suivre dans un tableau de bord']),
  ('PT.09', 'Aucune roadmap technique formalisée n''est alignée avec la roadmap business, avec ressources et jalons réalistes.', ARRAY['Vision technique floue et priorités arbitrées au fil de l''eau','Engagements business non tenables techniquement'], ARRAY['Formaliser une roadmap technique à 12 mois alignée avec les objectifs business','Y intégrer capacité d''équipe, dépendances et plan de résorption de la dette']),
  ('PT.10', 'La dette technique n''est ni inventoriée ni quantifiée, et aucun plan de résorption ni budget dédié n''existe.', ARRAY['Ralentissement progressif de la vélocité de développement','Coût caché de remise à niveau à intégrer dans la valorisation'], ARRAY['Inventorier et prioriser la dette technique (impact, effort)','Allouer une part fixe de capacité de chaque sprint à sa résorption']),
  ('ET.01', 'L''organisation de l''équipe technique n''est pas formalisée : rôles et responsabilités flous et leadership technique non clairement identifié.', ARRAY['Décisions techniques lentes ou contradictoires','Responsabilités non couvertes (sécurité, exploitation)'], ARRAY['Formaliser un organigramme technique avec les rôles et responsabilités','Désigner un responsable technique clairement identifié']),
  ('ET.02', 'Les compétences critiques (architecture, DevOps, sécurité, données) ne sont pas cartographiées et plusieurs ne sont pas couvertes face à la roadmap.', ARRAY['Roadmap non exécutable avec l''équipe actuelle','Recours imprévu à des prestataires coûteux'], ARRAY['Cartographier les compétences requises versus disponibles','Établir un plan de recrutement ou de formation sur les lacunes']),
  ('ET.03', 'Le risque lié aux personnes clés n''est ni identifié ni mitigé : la connaissance critique n''est pas documentée et aucun suppléant n''est désigné.', ARRAY['Paralysie de l''activité en cas de départ du CTO ou du lead développeur','Perte de savoir-faire non récupérable'], ARRAY['Identifier les personnes clés et les périmètres de connaissance exclusifs','Documenter les systèmes critiques et organiser du partage de connaissance']),
  ('ET.04', 'Le processus de recrutement technique n''est pas structuré (pas de test technique standardisé, ni de parcours d''onboarding formalisé).', ARRAY['Recrutements inadaptés et délais d''intégration longs','Difficulté à faire grandir l''équipe au rythme du plan de croissance'], ARRAY['Définir un processus de recrutement avec grille d''évaluation et test technique','Formaliser un parcours d''onboarding à 30/60/90 jours']),
  ('ET.05', 'Le développement ne suit pas de méthodologie structurée : rituels (planification, daily, rétrospective) absents ou irréguliers, et aucun indicateur de vélocité n''est suivi.', ARRAY['Livraisons imprévisibles et délais non tenus','Faible visibilité sur l''avancement pour la direction et les investisseurs'], ARRAY['Adopter un cadre agile avec sprints et rituels réguliers','Suivre des indicateurs de flux (vélocité, lead time) et les revoir en rétrospective']),
  ('ET.06', 'Les déploiements ne sont pas pleinement automatisés : la chaîne CI/CD est partielle et comporte des étapes manuelles.', ARRAY['Erreurs humaines lors des mises en production','Cycles de livraison lents'], ARRAY['Automatiser build, tests et déploiement dans un pipeline unique','Supprimer les étapes manuelles et tracer chaque déploiement']),
  ('ET.07', 'La gestion des incidents de production n''est pas formalisée : pas de processus de qualification, d''astreinte ni de post-mortem.', ARRAY['Temps de résolution long et incidents répétés','Charge reposant sur quelques personnes sans cadre'], ARRAY['Définir un processus d''incident (sévérités, escalade, communication)','Organiser une astreinte tournante et réaliser des post-mortems']),
  ('ET.08', 'La part du code produite par des freelances ou prestataires externes n''est pas connue, et le contrôle de leurs livraisons n''est pas structuré.', ARRAY['Qualité et maintenabilité hétérogènes du code livré','Perte de connaissance au départ des prestataires'], ARRAY['Recenser les contributions externes par module','Imposer revue de code et documentation sur toute livraison externe']),
  ('SD.01', 'Aucune politique de sécurité formalisée n''existe, même minimale, et les responsabilités de sécurité ne sont pas assignées.', ARRAY['Pratiques de sécurité disparates et non vérifiables','Exigences de clients ou d''investisseurs non satisfaites'], ARRAY['Rédiger une politique de sécurité proportionnée à la taille de l''entreprise','Désigner un responsable sécurité et la diffuser à l''équipe']),
  ('SD.02', 'Le contrôle des accès aux systèmes critiques est insuffisant : MFA non généralisé, revue des droits absente et comptes partagés ou non révoqués.', ARRAY['Compromission de comptes donnant accès à la production et au code','Accès résiduels d''anciens collaborateurs'], ARRAY['Activer le MFA sur tous les outils sensibles (cloud, Git, messagerie)','Mettre en place une revue périodique des accès et un processus de révocation au départ']),
  ('SD.03', 'Le chiffrement des données sensibles est incomplet : certaines données ou sauvegardes ne sont pas chiffrées au repos ou en transit.', ARRAY['Exposition de données en cas de vol de support ou d''interception','Non-conformité aux exigences contractuelles et réglementaires'], ARRAY['Imposer TLS sur tous les flux et chiffrer au repos les bases et sauvegardes','Utiliser un hachage adapté pour les mots de passe et une gestion centralisée des clés']),
  ('SD.04', 'Le dispositif RGPD est incomplet : registre des traitements absent ou non à jour, consentements non tracés et DPO non désigné alors que requis.', ARRAY['Sanctions de l''autorité de contrôle','Passif de conformité à provisionner dans la transaction'], ARRAY['Établir et tenir à jour le registre des traitements','Désigner un DPO ou référent et mettre en place la gestion des consentements']),
  ('SD.05', 'Le stockage des données personnelles clients n''est pas suffisamment sécurisé et les accès à ces données ne sont pas systématiquement journalisés.', ARRAY['Accès abusifs non détectés','Impossibilité de démontrer qui a consulté quelles données lors d''un incident'], ARRAY['Restreindre les accès aux données clients selon le besoin d''en connaître','Journaliser et revoir périodiquement les accès aux données personnelles']),
  ('SD.06', 'Aucun test de sécurité indépendant (pentest, scan de vulnérabilités) n''a été réalisé récemment sur l''application et l''infrastructure.', ARRAY['Vulnérabilités exploitables non identifiées','Absence de preuve de sécurité exigible par les clients grands comptes'], ARRAY['Faire réaliser un test d''intrusion par un tiers indépendant','Intégrer un scan automatisé de vulnérabilités et de dépendances dans la CI']),
  ('SD.07', 'L''historique des incidents de sécurité n''est pas consigné et aucun retour d''expérience formalisé n''est disponible.', ARRAY['Incidents passés non détectés ou non traités à l''origine d''un passif caché','Récidive faute d''enseignements tirés'], ARRAY['Constituer un registre des incidents de sécurité avec causes et actions correctives','Réaliser une revue rétrospective des incidents des 24 derniers mois']),
  ('SD.08', 'Les sauvegardes ne sont pas pleinement automatisées et aucun test de restauration n''a été réalisé, de sorte que les objectifs de RPO et RTO sont inconnus.', ARRAY['Perte de données irrécupérable en cas d''incident','Durée de reprise inconnue et potentiellement longue'], ARRAY['Automatiser les sauvegardes avec rétention et copie hors site','Tester la restauration régulièrement et documenter RPO et RTO']),
  ('SD.09', 'Il n''existe pas de plan de réponse aux incidents de sécurité formalisé, ni de liste de contacts d''urgence ou de procédure de notification.', ARRAY['Réaction désordonnée et tardive en cas de cyberattaque','Non-respect du délai de notification de 72 heures prévu par le RGPD'], ARRAY['Rédiger un plan de réponse avec rôles, contacts et procédure de notification','Tester le plan par un exercice de simulation annuel']),
  ('IO.01', 'L''hébergement de production (fournisseur, région, type) n''est pas documenté et le choix n''est pas justifié au regard des exigences de souveraineté et de pérennité.', ARRAY['Non-conformité de localisation des données','Dépendance non maîtrisée envers un fournisseur'], ARRAY['Documenter l''hébergement (provider, régions, services utilisés)','Justifier le choix au regard des contraintes réglementaires et de réversibilité']),
  ('IO.02', 'Les coûts d''infrastructure ne sont ni suivis ni ventilés par service, et leur évolution avec la croissance n''est pas modélisée.', ARRAY['Dérive des coûts cloud et marge brute dégradée','Business plan fondé sur des hypothèses de coûts non vérifiées'], ARRAY['Mettre en place un suivi mensuel des coûts par service et environnement','Modéliser le coût d''infrastructure par scénario de croissance']),
  ('IO.03', 'La supervision de la production est lacunaire : peu de métriques, pas d''alertes automatiques et incidents détectés par les utilisateurs.', ARRAY['Pannes détectées tardivement et durée d''indisponibilité allongée','Diagnostic difficile faute de logs centralisés'], ARRAY['Déployer monitoring, centralisation des logs et alertes sur les indicateurs clés','Définir des seuils d''alerte et un canal de notification de l''équipe']),
  ('IO.04', 'La disponibilité réelle n''est pas mesurée, aucun SLA, même interne, n''est défini et l''historique des indisponibilités n''est pas disponible.', ARRAY['Engagements contractuels de disponibilité non vérifiables','Fiabilité perçue non démontrable à l''investisseur'], ARRAY['Mesurer l''uptime avec un outil de supervision externe','Définir des objectifs de disponibilité (SLO/SLA) et publier l''historique']),
  ('IO.05', 'Les déploiements sont peu fréquents et manuels, sans procédure de rollback testée.', ARRAY['Mises en production risquées avec batch de changements volumineux','Temps de rétablissement long en cas de régression'], ARRAY['Automatiser les déploiements et les rendre fréquents et incrémentaux','Définir et tester une procédure de rollback']),
  ('IO.06', 'Les environnements dev, staging et production ne sont pas clairement séparés ni cohérents entre eux, avec des tests réalisés sur des configurations différentes de la production.', ARRAY['Bugs découverts uniquement en production','Risque d''altération ou de fuite de données de production'], ARRAY['Séparer strictement les environnements et les rendre reproductibles (infrastructure as code)','Interdire l''usage de données réelles hors production sans anonymisation']),
  ('IO.07', 'L''infrastructure n''est pas conçue pour une mise à l''échelle horizontale (pas d''autoscaling, instances dimensionnées manuellement) et n''a pas été validée à x10.', ARRAY['Saturation lors des pics de charge','Intervention manuelle coûteuse pour absorber la croissance'], ARRAY['Mettre en place l''autoscaling et rendre les services sans état','Valider la capacité par un test de charge à x10']),
  ('IO.08', 'Aucun plan de reprise d''activité n''est formalisé pour une perte du fournisseur cloud principal ou d''une région, et aucun test de bascule n''a été effectué.', ARRAY['Interruption prolongée du service en cas de sinistre majeur','Engagements de continuité envers les clients non tenables'], ARRAY['Rédiger un PRA avec objectifs RTO/RPO par service critique','Tester annuellement la bascule sur un site ou une région secondaire']),
  ('PI.01', 'La propriété de l''intégralité du code source n''est pas démontrée : des zones grises subsistent sur l''origine de certains modules et dépôts.', ARRAY['Contestation de la titularité des droits sur le code','Valeur de l''actif logiciel remise en cause lors de la transaction'], ARRAY['Cartographier l''origine du code par module et par contributeur','Régulariser les droits manquants par des cessions écrites']),
  ('PI.02', 'Les contrats de travail et pactes d''associés n''incluent pas systématiquement de clause de cession de propriété intellectuelle pour les fondateurs et employés.', ARRAY['Revendication de droits par d''anciens salariés ou fondateurs','Chaîne de titularité incomplète'], ARRAY['Auditer les contrats existants et signer des avenants de cession de PI','Intégrer une clause de cession dans tous les nouveaux contrats']),
  ('PI.03', 'Les licences des bibliothèques open source embarquées ne sont pas inventoriées ni vérifiées, et aucun outil d''analyse de composition logicielle n''est utilisé.', ARRAY['Non-conformité de licences non détectée','Obligations de redistribution ou d''attribution non respectées'], ARRAY['Générer une nomenclature logicielle (SBOM) et inventorier les licences','Intégrer un outil d''analyse de licences dans la CI']),
  ('PI.04', 'Les dépendances à des tiers critiques (API, SDK, services cloud) ne sont pas inventoriées et le risque de lock-in n''est pas évalué ni accompagné d''un plan de substitution.', ARRAY['Interruption du produit en cas de défaillance ou de changement tarifaire d''un fournisseur','Coût de migration élevé et non anticipé'], ARRAY['Recenser les fournisseurs critiques avec leur criticité et leurs alternatives','Isoler les intégrations derrière des couches d''abstraction et prévoir une stratégie de sortie']),
  ('PI.05', 'Aucun dépôt de marque ni de brevet n''a été effectué pour protéger les actifs distinctifs (nom, logo, innovations techniques).', ARRAY['Appropriation du nom ou de l''innovation par des concurrents','Valorisation réduite des actifs immatériels'], ARRAY['Faire réaliser une étude d''antériorité et déposer les marques principales','Évaluer la brevetabilité ou le secret des innovations clés']),
  ('PI.06', 'Les contrats avec les prestataires et freelances n''incluent pas systématiquement de cession de PI ni de clauses de confidentialité.', ARRAY['Code développé par des externes dont l''entreprise n''est pas propriétaire','Fuite d''informations confidentielles'], ARRAY['Réviser les contrats existants et obtenir des cessions rétroactives','Standardiser un contrat type avec cession de droits et confidentialité']),
  ('PI.07', 'Les réglementations sectorielles applicables au produit (fintech, santé, éducation, données) n''ont pas été identifiées de manière formelle et leur respect n''est pas démontré.', ARRAY['Sanctions ou interdiction d''exercer en cas de non-conformité','Coûts de mise en conformité imprévus'], ARRAY['Réaliser une cartographie des réglementations applicables par marché','Établir un plan de mise en conformité avec responsables et échéances'])
) as t(code, descr, risks, recos)
join public.controls c on c.code = t.code and c.domain_id in (select id from public.domains where framework_id = '00000000-0000-0000-0000-000000000015')
where not exists (select 1 from public.finding_templates ft where ft.control_id = c.id and ft.scope = 'platform' and ft.classification = 'minor_nc');

insert into public.finding_templates (scope, control_id, classification, description, risks, recommendations)
select 'platform', c.id, 'major_nc', t.descr, t.risks, t.recos
from (values
  ('PT.02', 'L''architecture est fortement couplée et non documentée (monolithe sans modularité ni frontières claires), rendant toute évolution majeure incertaine.', ARRAY['Refonte coûteuse nécessaire pour tenir la roadmap','Dépendance critique envers les personnes détenant la connaissance du système','Régressions fréquentes à chaque évolution'], ARRAY['Cartographier l''existant et identifier les couplages bloquants','Définir une architecture cible modulaire et un plan de migration incrémental']),
  ('PT.03', 'Aucune revue de code ni outil de qualité statique n''est en place : le code est poussé sans contrôle par pair.', ARRAY['Dette technique et bugs accumulés de façon incontrôlée','Vulnérabilités introduites sans détection','Qualité dépendante des individus'], ARRAY['Instaurer immédiatement la revue par pair avec approbation obligatoire','Intégrer une analyse statique (SonarQube ou équivalent) avec seuils bloquants']),
  ('PT.04', 'Il n''existe quasiment aucun test automatisé : la validation des livraisons repose sur des vérifications manuelles.', ARRAY['Bugs récurrents en production et perte de confiance des clients','Impossibilité de refactorer ou de faire évoluer sereinement le produit','Coût élevé de remédiation post-acquisition'], ARRAY['Introduire des tests unitaires et d''intégration sur le coeur métier en priorité','Rendre l''exécution des tests obligatoire dans la CI avant fusion']),
  ('PT.07', 'L''architecture présente des limites structurelles de scalabilité (état en mémoire, base unique non partitionnable, traitements synchrones) incompatibles avec la croissance prévue.', ARRAY['Refonte majeure nécessaire avant d''atteindre les objectifs de croissance','Indisponibilités lors des pics d''usage'], ARRAY['Établir un plan de refonte ciblé sur les composants limitants','Valider la cible par des tests de charge à x10']),
  ('PT.10', 'La dette technique est massive et hors de contrôle (code legacy, dépendances obsolètes, contournements), sans plan de remédiation.', ARRAY['Blocage de l''évolution du produit et vélocité en chute','Investissement de remise à niveau majeur non budgété','Risque accru de défaillances et de failles de sécurité'], ARRAY['Réaliser un audit chiffré de la dette et le prendre en compte dans le plan d''investissement','Définir un plan de résorption pluriannuel avec jalons mesurables']),
  ('ET.03', 'Le bus factor est de 1 : un seul individu maîtrise l''architecture, les déploiements et les accès critiques, sans documentation ni relais.', ARRAY['Interruption totale du développement et de l''exploitation en cas de départ','Poids de négociation défavorable lors de la transaction','Perte de continuité des accès et secrets'], ARRAY['Mettre en place un transfert de connaissance et un binôme sur chaque composant critique','Prévoir des clauses de rétention et de non-concurrence pour les personnes clés']),
  ('ET.06', 'Il n''existe aucune chaîne d''intégration et de déploiement continus : les livraisons sont réalisées manuellement sur les serveurs.', ARRAY['Mises en production risquées, non reproductibles et non tracées','Forte dépendance aux personnes détenant les accès','Impossibilité de livrer fréquemment'], ARRAY['Mettre en place une CI exécutant build, tests et analyses à chaque commit','Déployer un pipeline CD avec environnements et approbation avant production']),
  ('SD.02', 'Les accès à la production et aux secrets reposent sur des comptes partagés ou des mots de passe faibles, sans MFA ni traçabilité.', ARRAY['Risque élevé d''intrusion et d''exfiltration de données','Impossibilité d''imputer les actions réalisées en production'], ARRAY['Remplacer les comptes partagés par des comptes nominatifs avec MFA obligatoire','Centraliser les secrets dans un coffre-fort et appliquer le moindre privilège']),
  ('SD.03', 'Des données sensibles (mots de passe, données clients) sont stockées ou transmises en clair, sans chiffrement ni hachage approprié.', ARRAY['Fuite de données exploitable directement en cas de brèche','Sanctions réglementaires et atteinte à la réputation'], ARRAY['Corriger en priorité le stockage des mots de passe et activer le chiffrement des données sensibles','Auditer l''ensemble des flux pour supprimer les transmissions non chiffrées']),
  ('SD.04', 'L''entreprise traite des données personnelles sans cadre RGPD effectif (aucun registre, base légale non documentée, droits des personnes non gérés).', ARRAY['Exposition à des amendes pouvant atteindre 4 % du chiffre d''affaires','Blocage de contrats avec des clients exigeant la conformité'], ARRAY['Lancer un audit de conformité RGPD et un plan de remédiation daté','Mettre en place les procédures d''exercice des droits et de notification des violations']),
  ('SD.06', 'Aucun test de sécurité n''a jamais été effectué, alors que le produit est exposé sur Internet et manipule des données clients.', ARRAY['Vulnérabilités critiques potentiellement présentes et exploitables','Risque de brèche avec impact financier et réputationnel majeur'], ARRAY['Planifier un pentest externe avant ou immédiatement après la transaction','Corriger les vulnérabilités selon leur criticité avec un suivi de remédiation']),
  ('SD.08', 'Aucune sauvegarde fiable des données de production n''est en place, ou elle n''a jamais été validée par une restauration.', ARRAY['Perte définitive de données clients en cas de panne ou de ransomware','Impact existentiel sur la continuité de l''activité'], ARRAY['Mettre en place immédiatement des sauvegardes automatiques chiffrées et externalisées','Réaliser un test de restauration complet et en consigner les résultats']),
  ('IO.03', 'Aucun monitoring ni alerting n''existe sur la production : la disponibilité n''est connue que via les remontées des clients.', ARRAY['Pannes prolongées non détectées','Impossibilité de mesurer la fiabilité réelle du service'], ARRAY['Mettre en place sans délai une supervision de disponibilité et d''erreurs avec alertes','Centraliser les journaux applicatifs et d''infrastructure']),
  ('IO.06', 'Les développeurs testent directement sur l''environnement de production, faute d''environnement de recette distinct.', ARRAY['Incidents de production causés par les tests','Corruption ou exposition de données clients'], ARRAY['Créer sans délai un environnement de staging isolé et représentatif','Verrouiller les accès de développement à la production']),
  ('IO.08', 'L''infrastructure repose sur un point de défaillance unique (une seule instance ou région) sans plan de reprise ni redondance.', ARRAY['Arrêt total du produit en cas d''incident majeur du fournisseur','Perte de données et de chiffre d''affaires non maîtrisée'], ARRAY['Introduire de la redondance sur les composants critiques','Définir et tester un PRA avec sauvegardes hors région']),
  ('PI.01', 'Une part significative du code a été produite sans titre de cession établissant que l''entreprise en est propriétaire.', ARRAY['Revendication des droits par des tiers','Blocage de la transaction ou décote de valorisation'], ARRAY['Obtenir des cessions de droits rétroactives de tous les contributeurs concernés','Inscrire la garantie de titularité dans le dossier de transaction']),
  ('PI.02', 'Les fondateurs n''ont pas cédé formellement à l''entreprise la propriété intellectuelle développée avant ou hors contrat.', ARRAY['Actif principal juridiquement détenu à titre personnel','Risque de litige en cas de départ ou de désaccord'], ARRAY['Faire signer des actes de cession de PI par chaque fondateur avant la transaction','Intégrer ces cessions aux garanties d''actif et de passif']),
  ('PI.03', 'Des composants sous licence copyleft forte (GPL/AGPL) sont intégrés au produit propriétaire sans analyse de compatibilité.', ARRAY['Obligation de divulguer le code source du produit','Litiges de propriété intellectuelle et mise en conformité coûteuse'], ARRAY['Identifier les composants copyleft et évaluer leur impact avec un conseil juridique','Remplacer ou isoler les composants non conformes']),
  ('PI.06', 'Du code essentiel a été développé par des freelances sans contrat écrit ni cession de droits.', ARRAY['Titularité contestable sur des modules clés du produit','Dépendance envers les prestataires pour toute évolution'], ARRAY['Identifier les prestataires concernés et régulariser par des cessions écrites','Conditionner tout paiement ultérieur à la signature d''une cession de droits'])
) as t(code, descr, risks, recos)
join public.controls c on c.code = t.code and c.domain_id in (select id from public.domains where framework_id = '00000000-0000-0000-0000-000000000015')
where not exists (select 1 from public.finding_templates ft where ft.control_id = c.id and ft.scope = 'platform' and ft.classification = 'major_nc');
