-- 00281 — Constats-types personnalisés (NIST).
insert into public.finding_templates (scope, control_id, classification, description, risks, recommendations)
select 'platform', c.id, 'minor_nc', t.descr, t.risks, t.recos
from (values
  ('GV.OC', 'Le contexte organisationnel (missions, parties prenantes, obligations légales et contractuelles) n''est pas documenté ni relié aux décisions de gestion des risques cyber.', ARRAY['Décisions de sécurité déconnectées des enjeux métier','Obligations réglementaires non identifiées ni suivies'], ARRAY['Documenter missions, parties prenantes et exigences légales applicables','Relier ce contexte aux critères de gestion des risques cyber']),
  ('GV.RM', 'Aucune stratégie de gestion des risques cyber formalisée ne définit l''appétence, la tolérance au risque ni les priorités validées par la direction.', ARRAY['Arbitrages et investissements de sécurité incohérents','Acceptation de risques inacceptables sans validation','Absence de référentiel pour prioriser les actions'], ARRAY['Définir et faire valider l''appétence et la tolérance au risque','Établir une stratégie de gestion des risques intégrée à la gestion des risques d''entreprise','Réviser la stratégie au moins annuellement']),
  ('GV.RR', 'Les rôles, responsabilités et autorités en cybersécurité ne sont ni formalisés ni communiqués, et aucun responsable sécurité n''est clairement mandaté.', ARRAY['Responsabilités diluées lors des incidents','Actions de sécurité sans propriétaire ni budget'], ARRAY['Formaliser et communiquer une matrice des rôles et responsabilités','Nommer un RSSI doté de l''autorité et des ressources nécessaires']),
  ('GV.PO', 'Les politiques de cybersécurité sont absentes, obsolètes ou non approuvées, communiquées et appliquées de façon incohérente.', ARRAY['Pratiques de sécurité hétérogènes selon les équipes','Impossibilité d''opposer des règles au personnel et aux tiers'], ARRAY['Rédiger et faire approuver la politique de sécurité et ses déclinaisons','Diffuser les politiques et en réviser le contenu annuellement']),
  ('GV.OV', 'Aucune supervision de la stratégie de cybersécurité n''est exercée : pas de revue de direction, d''indicateurs ni de remontée de résultats.', ARRAY['Dérive non détectée de la posture de sécurité','Direction non informée de l''exposition réelle'], ARRAY['Instaurer des revues de direction périodiques de la cybersécurité','Définir des indicateurs de performance et de risque suivis en comité']),
  ('GV.SC', 'Les risques de la chaîne d''approvisionnement ne sont pas gérés : fournisseurs critiques non identifiés, exigences de sécurité absentes des contrats et sans évaluation.', ARRAY['Compromission via un prestataire ou un composant tiers','Perte de service due à un fournisseur défaillant','Fuite de données chez un sous-traitant'], ARRAY['Inventorier et classifier les fournisseurs selon leur criticité','Intégrer des clauses de sécurité dans les contrats et évaluer les fournisseurs critiques']),
  ('ID.AM', 'L''inventaire des actifs (matériels, logiciels, données, systèmes, flux) est incomplet, non maintenu et sans propriétaires désignés.', ARRAY['Actifs non protégés car ignorés','Shadow IT et systèmes obsolètes exposés','Analyse de risques fondée sur des données erronées'], ARRAY['Établir un inventaire exhaustif avec propriétaire et criticité','Automatiser la découverte et la mise à jour de l''inventaire']),
  ('ID.RA', 'Les risques cyber ne sont pas identifiés, analysés ni priorisés selon une méthode documentée ; vulnérabilités et menaces ne sont pas exploitées.', ARRAY['Risques majeurs non traités','Ressources allouées sans lien avec l''exposition réelle','Exploitation de vulnérabilités connues'], ARRAY['Adopter une méthode d''analyse de risques et réaliser une appréciation complète','Maintenir un registre des risques avec plans de traitement priorisés','Intégrer veille menaces et gestion des vulnérabilités']),
  ('ID.IM', 'Aucun processus d''amélioration ne capitalise sur les évaluations, audits, incidents et exercices ; les actions correctives ne sont pas suivies.', ARRAY['Reproduction des mêmes défaillances','Écarts d''audit non résolus'], ARRAY['Mettre en place un plan d''actions correctives suivi avec échéances','Réaliser des exercices périodiques et en consigner les retours d''expérience']),
  ('PR.AA', 'La gestion des identités et des accès est insuffisante : comptes non revus, privilèges excessifs, authentification multifacteur absente, comptes partagés ou orphelins.', ARRAY['Compromission de comptes et élévation de privilèges','Accès non autorisés aux données sensibles','Absence de traçabilité des actions'], ARRAY['Déployer l''authentification multifacteur, en priorité sur comptes privilégiés et accès distants','Appliquer le moindre privilège et revoir les droits périodiquement','Gérer le cycle de vie des comptes (arrivées, mobilités, départs)']),
  ('PR.AT', 'Le personnel n''est pas sensibilisé ni formé régulièrement à la cybersécurité ; les profils à privilèges n''ont pas de formation spécifique.', ARRAY['Succès des attaques d''hameçonnage et d''ingénierie sociale','Erreurs de manipulation causant des fuites'], ARRAY['Mettre en place un programme annuel de sensibilisation avec suivi de participation','Prévoir des formations ciblées pour administrateurs et dirigeants']),
  ('PR.DS', 'Les données ne sont pas classifiées ni protégées : absence de chiffrement au repos et en transit, de contrôle des fuites et de sauvegardes protégées.', ARRAY['Divulgation ou vol de données sensibles','Non-conformité réglementaire sur les données personnelles','Perte ou altération d''intégrité des données'], ARRAY['Définir un schéma de classification des données','Chiffrer les données sensibles au repos et en transit','Mettre en place des mesures de prévention des fuites de données']),
  ('PR.PS', 'Les plateformes ne sont pas sécurisées : absence de configurations de référence durcies, gestion des correctifs irrégulière et logiciels non maintenus.', ARRAY['Exploitation de vulnérabilités non corrigées','Dérive de configuration et surface d''attaque élargie'], ARRAY['Définir et appliquer des référentiels de configuration sécurisée','Instaurer un processus de gestion des correctifs avec délais selon la criticité']),
  ('PR.IR', 'L''architecture ne garantit pas la résilience : segmentation réseau insuffisante, absence de redondance et de capacité de montée en charge pour les systèmes critiques.', ARRAY['Propagation latérale d''une compromission','Interruption de services critiques sur panne unique'], ARRAY['Segmenter les réseaux et isoler les systèmes critiques','Mettre en place redondance et surveillance de capacité des services essentiels']),
  ('DE.CM', 'La surveillance continue est inexistante ou partielle : journaux non centralisés, réseaux, postes et services tiers non supervisés, sans SOC ni SIEM.', ARRAY['Compromission non détectée pendant des mois','Absence de preuves pour les investigations','Dwell time prolongé des attaquants'], ARRAY['Centraliser les journaux dans un SIEM avec rétention adaptée','Superviser réseau, postes, comptes privilégiés et prestataires','Définir les cas d''usage de détection prioritaires']),
  ('DE.AE', 'Les événements ne sont pas analysés : pas de corrélation, de qualification des alertes ni de seuils d''incident définis, et la veille sur les menaces n''est pas exploitée.', ARRAY['Alertes ignorées ou traitées tardivement','Incidents non qualifiés ni escaladés'], ARRAY['Définir critères de qualification et d''escalade des événements','Mettre en place corrélation des événements et renseignement sur les menaces']),
  ('RS.MA', 'Aucun plan de réponse aux incidents formalisé et testé ; processus de déclaration, de priorisation et de pilotage de crise non définis.', ARRAY['Réaction désordonnée et tardive aux incidents','Impact amplifié sur l''activité et la réputation','Non-respect des délais de notification'], ARRAY['Élaborer et approuver un plan de réponse aux incidents avec rôles et procédures','Tester le plan par des exercices de crise annuels','Mettre en place un registre et un processus de triage des incidents']),
  ('RS.AN', 'Les incidents ne font pas l''objet d''analyses structurées : pas de recherche de cause racine, de conservation des preuves ni de capacité forensique.', ARRAY['Cause racine non traitée et récidive','Preuves inexploitables juridiquement','Impact réel sous-estimé'], ARRAY['Définir une procédure d''investigation et de préservation des preuves','Formaliser l''analyse de cause racine pour chaque incident significatif']),
  ('RS.CO', 'Aucune procédure ne coordonne la communication d''incident avec parties prenantes internes, autorités, clients et partenaires.', ARRAY['Notifications réglementaires tardives ou omises','Perte de confiance des clients et partenaires'], ARRAY['Établir un plan de communication de crise avec contacts et modèles','Définir les obligations de notification aux autorités et clients']),
  ('RS.MI', 'Les mesures de confinement et d''atténuation ne sont pas prédéfinies : pas de procédures d''isolement, d''éradication ni de traitement des vulnérabilités exploitées.', ARRAY['Propagation de l''incident à d''autres systèmes','Persistance de l''attaquant dans le SI'], ARRAY['Rédiger des playbooks de confinement et d''éradication par type d''incident','Traiter ou accepter formellement les vulnérabilités exploitées lors d''incidents']),
  ('RC.RP', 'Aucun plan de rétablissement testé n''assure la restauration des services : RTO/RPO non définis, sauvegardes non testées, pas de priorisation des systèmes critiques.', ARRAY['Arrêt prolongé de l''activité','Perte définitive de données','Restauration improvisée de systèmes compromis'], ARRAY['Définir RTO/RPO et prioriser les services critiques','Mettre en place sauvegardes isolées et tester régulièrement les restaurations','Élaborer et tester un plan de continuité et de reprise d''activité']),
  ('RC.CO', 'La communication pendant et après le rétablissement n''est pas coordonnée : pas de porte-parole, de messages préparés ni de retour d''information aux parties prenantes.', ARRAY['Informations contradictoires diffusées','Atteinte à la réputation après l''incident'], ARRAY['Désigner un porte-parole et préparer des messages de communication de reprise','Informer les parties prenantes de l''avancement et de la clôture du rétablissement'])
) as t(code, descr, risks, recos)
join public.controls c on c.code = t.code and c.domain_id in (select id from public.domains where framework_id = '00000000-0000-0000-0000-000000000011')
where not exists (select 1 from public.finding_templates ft where ft.control_id = c.id and ft.scope = 'platform' and ft.classification = 'minor_nc');

insert into public.finding_templates (scope, control_id, classification, description, risks, recommendations)
select 'platform', c.id, 'major_nc', t.descr, t.risks, t.recos
from (values
  ('GV.RM', 'Aucune stratégie de gestion des risques cyber formalisée ne définit l''appétence, la tolérance au risque ni les priorités validées par la direction.', ARRAY['Arbitrages et investissements de sécurité incohérents','Acceptation de risques inacceptables sans validation','Absence de référentiel pour prioriser les actions'], ARRAY['Définir et faire valider l''appétence et la tolérance au risque','Établir une stratégie de gestion des risques intégrée à la gestion des risques d''entreprise','Réviser la stratégie au moins annuellement']),
  ('ID.RA', 'Les risques cyber ne sont pas identifiés, analysés ni priorisés selon une méthode documentée ; vulnérabilités et menaces ne sont pas exploitées.', ARRAY['Risques majeurs non traités','Ressources allouées sans lien avec l''exposition réelle','Exploitation de vulnérabilités connues'], ARRAY['Adopter une méthode d''analyse de risques et réaliser une appréciation complète','Maintenir un registre des risques avec plans de traitement priorisés','Intégrer veille menaces et gestion des vulnérabilités']),
  ('PR.AA', 'La gestion des identités et des accès est insuffisante : comptes non revus, privilèges excessifs, authentification multifacteur absente, comptes partagés ou orphelins.', ARRAY['Compromission de comptes et élévation de privilèges','Accès non autorisés aux données sensibles','Absence de traçabilité des actions'], ARRAY['Déployer l''authentification multifacteur, en priorité sur comptes privilégiés et accès distants','Appliquer le moindre privilège et revoir les droits périodiquement','Gérer le cycle de vie des comptes (arrivées, mobilités, départs)']),
  ('DE.CM', 'La surveillance continue est inexistante ou partielle : journaux non centralisés, réseaux, postes et services tiers non supervisés, sans SOC ni SIEM.', ARRAY['Compromission non détectée pendant des mois','Absence de preuves pour les investigations','Dwell time prolongé des attaquants'], ARRAY['Centraliser les journaux dans un SIEM avec rétention adaptée','Superviser réseau, postes, comptes privilégiés et prestataires','Définir les cas d''usage de détection prioritaires']),
  ('DE.AE', 'Les événements ne sont pas analysés : pas de corrélation, de qualification des alertes ni de seuils d''incident définis, et la veille sur les menaces n''est pas exploitée.', ARRAY['Alertes ignorées ou traitées tardivement','Incidents non qualifiés ni escaladés'], ARRAY['Définir critères de qualification et d''escalade des événements','Mettre en place corrélation des événements et renseignement sur les menaces']),
  ('RS.MA', 'Aucun plan de réponse aux incidents formalisé et testé ; processus de déclaration, de priorisation et de pilotage de crise non définis.', ARRAY['Réaction désordonnée et tardive aux incidents','Impact amplifié sur l''activité et la réputation','Non-respect des délais de notification'], ARRAY['Élaborer et approuver un plan de réponse aux incidents avec rôles et procédures','Tester le plan par des exercices de crise annuels','Mettre en place un registre et un processus de triage des incidents']),
  ('RC.RP', 'Aucun plan de rétablissement testé n''assure la restauration des services : RTO/RPO non définis, sauvegardes non testées, pas de priorisation des systèmes critiques.', ARRAY['Arrêt prolongé de l''activité','Perte définitive de données','Restauration improvisée de systèmes compromis'], ARRAY['Définir RTO/RPO et prioriser les services critiques','Mettre en place sauvegardes isolées et tester régulièrement les restaurations','Élaborer et tester un plan de continuité et de reprise d''activité'])
) as t(code, descr, risks, recos)
join public.controls c on c.code = t.code and c.domain_id in (select id from public.domains where framework_id = '00000000-0000-0000-0000-000000000011')
where not exists (select 1 from public.finding_templates ft where ft.control_id = c.id and ft.scope = 'platform' and ft.classification = 'major_nc');
