-- 00282 — Contenu des preuves attendues (NIST, modèle mutualisé).
insert into public.evidence_items (framework_id, name, description, kind)
select '00000000-0000-0000-0000-000000000011', t.name, t.descr, t.kind from (values
  ('Cartographie du contexte et des parties prenantes', 'Démontre que la mission, les parties prenantes et leurs attentes cyber sont identifiées et documentées.', 'document'),
  ('Registre des exigences légales, réglementaires et contractuelles', 'Prouve que les obligations applicables en cybersécurité sont recensées et suivies.', 'record'),
  ('Cartographie des services critiques et dépendances', 'Montre que les services et dépendances essentiels aux objectifs de l''organisation sont identifiés.', 'document'),
  ('Politique de gestion des risques cyber', 'Prouve que la stratégie de gestion des risques cyber est formalisée et approuvée.', 'policy'),
  ('Déclaration d''appétence et de tolérance au risque', 'Atteste que les seuils d''acceptation du risque sont définis par la direction.', 'document'),
  ('Registre des risques', 'Démontre que les risques sont consignés, traités et suivis selon la stratégie.', 'record'),
  ('Organigramme sécurité et matrice RACI cyber', 'Prouve que les rôles et responsabilités cyber sont définis et attribués.', 'document'),
  ('Lettres de mission RSSI et responsables sécurité', 'Atteste de la nomination formelle et des autorités des responsables cyber.', 'record'),
  ('Compte rendu du comité de pilotage sécurité', 'Montre l''implication effective de la direction dans la gouvernance cyber.', 'record'),
  ('Politique de sécurité de l''information', 'Prouve qu''une politique cyber est approuvée par la direction et communiquée.', 'policy'),
  ('Registre de diffusion et d''acquittement des politiques', 'Atteste que les politiques sont communiquées et lues par le personnel.', 'record'),
  ('Historique de revue et de versionnage des politiques', 'Montre que les politiques sont revues périodiquement et mises à jour.', 'record'),
  ('Tableau de bord des indicateurs de cybersécurité', 'Prouve que la performance de la stratégie cyber est mesurée et remontée à la direction.', 'record'),
  ('Revue de direction du dispositif cyber', 'Atteste de l''examen périodique de la stratégie et des décisions d''ajustement.', 'record'),
  ('Rapports d''audit interne et plan d''actions correctives', 'Montre que les écarts sont suivis et corrigés.', 'document'),
  ('Politique de gestion des risques fournisseurs', 'Prouve que les exigences cyber de la chaîne d''approvisionnement sont définies.', 'policy'),
  ('Inventaire et classification des fournisseurs critiques', 'Atteste que les tiers critiques sont identifiés et évalués.', 'record'),
  ('Clauses de sécurité contractuelles types', 'Montre que les contrats imposent des exigences cyber aux fournisseurs.', 'document'),
  ('Évaluations de sécurité des fournisseurs', 'Démontre le suivi périodique du niveau de sécurité des fournisseurs.', 'record'),
  ('Inventaire des actifs', 'Prouve que matériels, logiciels, données et systèmes sont recensés et à jour.', 'record'),
  ('Cartographie des flux de données et des réseaux', 'Atteste que les flux et interconnexions sont documentés.', 'document'),
  ('Classification des actifs et des données', 'Montre que les actifs sont priorisés selon leur criticité.', 'document'),
  ('Rapport d''analyse de risques', 'Atteste de l''application d''une méthodologie d''analyse documentée.', 'document'),
  ('Rapports de scans de vulnérabilités et veille sur les menaces', 'Montre l''identification continue des vulnérabilités et menaces.', 'record'),
  ('Plan d''amélioration continue de la sécurité', 'Prouve que les améliorations issues des évaluations sont planifiées et suivies.', 'document'),
  ('Rapports de tests d''intrusion et d''audits', 'Atteste de la réalisation d''évaluations indépendantes périodiques.', 'document'),
  ('Retours d''expérience des exercices et incidents', 'Montre que les leçons apprises alimentent les améliorations.', 'record'),
  ('Politique de contrôle d''accès', 'Prouve que les règles d''accès et de moindre privilège sont définies.', 'policy'),
  ('Revue périodique des droits d''accès', 'Atteste que les comptes et privilèges sont revus et nettoyés.', 'record'),
  ('Configuration de l''authentification multifacteur', 'Montre que l''authentification forte est appliquée aux accès sensibles.', 'config'),
  ('Programme de sensibilisation', 'Prouve qu''un programme de sensibilisation cyber est défini et déployé.', 'document'),
  ('Registres de présence et résultats des formations', 'Atteste de la participation effective du personnel aux formations.', 'record'),
  ('Plan de formation des profils à privilèges', 'Montre que les rôles techniques reçoivent une formation spécialisée.', 'document'),
  ('Politique de chiffrement et de protection des données', 'Prouve que la protection des données au repos et en transit est cadrée.', 'policy'),
  ('Configuration du chiffrement des données et des sauvegardes', 'Atteste de l''application technique du chiffrement.', 'config'),
  ('Politique de sauvegarde et rapports de restauration', 'Montre que les données sont sauvegardées et restaurables.', 'record'),
  ('Règles de prévention des fuites de données', 'Démontre le contrôle des sorties de données sensibles.', 'config'),
  ('Standards de configuration sécurisée (durcissement)', 'Prouve que des référentiels de durcissement sont définis pour les plateformes.', 'document'),
  ('Procédure et suivi de gestion des correctifs', 'Atteste que les correctifs sont appliqués dans des délais définis.', 'record'),
  ('Politique de développement sécurisé', 'Montre que la sécurité est intégrée au cycle de développement logiciel.', 'policy'),
  ('Schéma d''architecture réseau et de segmentation', 'Prouve que l''architecture protège les actifs par segmentation et zones de confiance.', 'document'),
  ('Règles de pare-feu et de filtrage', 'Atteste de la configuration effective des contrôles périmétriques.', 'config'),
  ('Plan de continuité et de reprise', 'Montre la résilience et la redondance de l''infrastructure.', 'document'),
  ('Journaux et supervision', 'Prouve que les actifs, réseaux et accès sont journalisés et surveillés.', 'config'),
  ('Configuration des outils de détection (EDR, IDS/IPS)', 'Atteste du déploiement d''outils de détection d''intrusion sur le périmètre.', 'config'),
  ('Rapports de supervision des fournisseurs et accès externes', 'Montre la surveillance des activités des tiers.', 'record'),
  ('Règles de corrélation et cas d''usage du SIEM', 'Prouve que les événements sont corrélés pour détecter les anomalies.', 'config'),
  ('Procédure de qualification des événements de sécurité', 'Atteste d''une méthode de tri et de qualification des alertes.', 'document'),
  ('Registre des alertes analysées et seuils d''incident', 'Montre l''analyse effective des événements et les critères d''escalade.', 'record'),
  ('Plan de réponse aux incidents', 'Prouve que la réponse aux incidents est planifiée avec rôles et étapes.', 'document'),
  ('Registre des incidents de sécurité', 'Atteste du traitement et du suivi des incidents jusqu''à clôture.', 'record'),
  ('Rapports d''exercices de gestion de crise', 'Montre que le plan est testé.', 'record'),
  ('Rapports d''analyse post-incident', 'Prouve que les causes et l''impact des incidents sont investigués.', 'document'),
  ('Procédure de collecte et préservation des preuves forensiques', 'Atteste que les preuves numériques sont conservées de manière exploitable.', 'document'),
  ('Matrice de catégorisation et de priorisation des incidents', 'Montre que les incidents sont classés selon leur gravité.', 'document'),
  ('Plan de communication de crise et annuaire d''escalade', 'Prouve que les contacts internes et externes sont définis pour les incidents.', 'document'),
  ('Modèles et preuves de notification aux autorités et clients', 'Atteste du respect des obligations de notification d''incident.', 'record'),
  ('Accords de partage d''information sur les menaces', 'Montre la coordination avec CERT et pairs sectoriels.', 'document'),
  ('Playbooks de confinement et d''éradication', 'Prouve que des procédures d''endiguement des incidents sont définies.', 'document'),
  ('Journal des actions de confinement réalisées', 'Atteste des mesures prises pour limiter l''expansion d''incidents réels.', 'record'),
  ('Registre des vulnérabilités exploitées et mesures correctives', 'Montre le traitement des failles à l''origine des incidents.', 'record'),
  ('Rapports de tests de restauration et de reprise', 'Atteste que les capacités de rétablissement sont testées.', 'record'),
  ('Rapport de clôture et retour d''expérience de rétablissement', 'Montre la validation de la restauration et les leçons tirées.', 'document'),
  ('Plan de communication de rétablissement', 'Prouve que la communication aux parties prenantes durant la reprise est prévue.', 'document'),
  ('Communications émises lors des reprises d''activité', 'Atteste de l''information effective des parties prenantes et du public.', 'record')
) as t(name, descr, kind)
where not exists (select 1 from public.evidence_items ei where ei.framework_id = '00000000-0000-0000-0000-000000000011' and ei.name = t.name);

insert into public.evidence_catalog (control_id, evidence_item_id, name, description, is_required, kind, sort_order)
select c.id, ei.id, r.name, r.descr, r.is_req, r.kind, r.ord from (values
  ('GV.OC', 'Cartographie du contexte et des parties prenantes', 'Démontre que la mission, les parties prenantes et leurs attentes cyber sont identifiées et documentées.', true, 'document', 1),
  ('GV.OC', 'Registre des exigences légales, réglementaires et contractuelles', 'Prouve que les obligations applicables en cybersécurité sont recensées et suivies.', true, 'record', 2),
  ('GV.OC', 'Cartographie des services critiques et dépendances', 'Montre que les services et dépendances essentiels aux objectifs de l''organisation sont identifiés.', false, 'document', 3),
  ('GV.RM', 'Politique de gestion des risques cyber', 'Prouve que la stratégie de gestion des risques cyber est formalisée et approuvée.', true, 'policy', 1),
  ('GV.RM', 'Déclaration d''appétence et de tolérance au risque', 'Atteste que les seuils d''acceptation du risque sont définis par la direction.', true, 'document', 2),
  ('GV.RM', 'Registre des risques', 'Démontre que les risques sont consignés, traités et suivis selon la stratégie.', false, 'record', 3),
  ('GV.RR', 'Organigramme sécurité et matrice RACI cyber', 'Prouve que les rôles et responsabilités cyber sont définis et attribués.', true, 'document', 1),
  ('GV.RR', 'Lettres de mission RSSI et responsables sécurité', 'Atteste de la nomination formelle et des autorités des responsables cyber.', true, 'record', 2),
  ('GV.RR', 'Compte rendu du comité de pilotage sécurité', 'Montre l''implication effective de la direction dans la gouvernance cyber.', false, 'record', 3),
  ('GV.PO', 'Politique de sécurité de l''information', 'Prouve qu''une politique cyber est approuvée par la direction et communiquée.', true, 'policy', 1),
  ('GV.PO', 'Registre de diffusion et d''acquittement des politiques', 'Atteste que les politiques sont communiquées et lues par le personnel.', true, 'record', 2),
  ('GV.PO', 'Historique de revue et de versionnage des politiques', 'Montre que les politiques sont revues périodiquement et mises à jour.', false, 'record', 3),
  ('GV.OV', 'Tableau de bord des indicateurs de cybersécurité', 'Prouve que la performance de la stratégie cyber est mesurée et remontée à la direction.', true, 'record', 1),
  ('GV.OV', 'Revue de direction du dispositif cyber', 'Atteste de l''examen périodique de la stratégie et des décisions d''ajustement.', true, 'record', 2),
  ('GV.OV', 'Rapports d''audit interne et plan d''actions correctives', 'Montre que les écarts sont suivis et corrigés.', false, 'document', 3),
  ('GV.SC', 'Politique de gestion des risques fournisseurs', 'Prouve que les exigences cyber de la chaîne d''approvisionnement sont définies.', true, 'policy', 1),
  ('GV.SC', 'Inventaire et classification des fournisseurs critiques', 'Atteste que les tiers critiques sont identifiés et évalués.', true, 'record', 2),
  ('GV.SC', 'Clauses de sécurité contractuelles types', 'Montre que les contrats imposent des exigences cyber aux fournisseurs.', false, 'document', 3),
  ('GV.SC', 'Évaluations de sécurité des fournisseurs', 'Démontre le suivi périodique du niveau de sécurité des fournisseurs.', false, 'record', 4),
  ('ID.AM', 'Inventaire des actifs', 'Prouve que matériels, logiciels, données et systèmes sont recensés et à jour.', true, 'record', 1),
  ('ID.AM', 'Cartographie des flux de données et des réseaux', 'Atteste que les flux et interconnexions sont documentés.', true, 'document', 2),
  ('ID.AM', 'Classification des actifs et des données', 'Montre que les actifs sont priorisés selon leur criticité.', false, 'document', 3),
  ('ID.RA', 'Registre des risques', 'Prouve que les risques sont identifiés, analysés et priorisés.', true, 'record', 1),
  ('ID.RA', 'Rapport d''analyse de risques', 'Atteste de l''application d''une méthodologie d''analyse documentée.', true, 'document', 2),
  ('ID.RA', 'Rapports de scans de vulnérabilités et veille sur les menaces', 'Montre l''identification continue des vulnérabilités et menaces.', false, 'record', 3),
  ('ID.IM', 'Plan d''amélioration continue de la sécurité', 'Prouve que les améliorations issues des évaluations sont planifiées et suivies.', true, 'document', 1),
  ('ID.IM', 'Rapports de tests d''intrusion et d''audits', 'Atteste de la réalisation d''évaluations indépendantes périodiques.', true, 'document', 2),
  ('ID.IM', 'Retours d''expérience des exercices et incidents', 'Montre que les leçons apprises alimentent les améliorations.', false, 'record', 3),
  ('PR.AA', 'Politique de contrôle d''accès', 'Prouve que les règles d''accès et de moindre privilège sont définies.', true, 'policy', 1),
  ('PR.AA', 'Revue périodique des droits d''accès', 'Atteste que les comptes et privilèges sont revus et nettoyés.', true, 'record', 2),
  ('PR.AA', 'Configuration de l''authentification multifacteur', 'Montre que l''authentification forte est appliquée aux accès sensibles.', false, 'config', 3),
  ('PR.AT', 'Programme de sensibilisation', 'Prouve qu''un programme de sensibilisation cyber est défini et déployé.', true, 'document', 1),
  ('PR.AT', 'Registres de présence et résultats des formations', 'Atteste de la participation effective du personnel aux formations.', true, 'record', 2),
  ('PR.AT', 'Plan de formation des profils à privilèges', 'Montre que les rôles techniques reçoivent une formation spécialisée.', false, 'document', 3),
  ('PR.DS', 'Politique de chiffrement et de protection des données', 'Prouve que la protection des données au repos et en transit est cadrée.', true, 'policy', 1),
  ('PR.DS', 'Configuration du chiffrement des données et des sauvegardes', 'Atteste de l''application technique du chiffrement.', true, 'config', 2),
  ('PR.DS', 'Politique de sauvegarde et rapports de restauration', 'Montre que les données sont sauvegardées et restaurables.', false, 'record', 3),
  ('PR.DS', 'Règles de prévention des fuites de données', 'Démontre le contrôle des sorties de données sensibles.', false, 'config', 4),
  ('PR.PS', 'Standards de configuration sécurisée (durcissement)', 'Prouve que des référentiels de durcissement sont définis pour les plateformes.', true, 'document', 1),
  ('PR.PS', 'Procédure et suivi de gestion des correctifs', 'Atteste que les correctifs sont appliqués dans des délais définis.', true, 'record', 2),
  ('PR.PS', 'Politique de développement sécurisé', 'Montre que la sécurité est intégrée au cycle de développement logiciel.', false, 'policy', 3),
  ('PR.IR', 'Schéma d''architecture réseau et de segmentation', 'Prouve que l''architecture protège les actifs par segmentation et zones de confiance.', true, 'document', 1),
  ('PR.IR', 'Règles de pare-feu et de filtrage', 'Atteste de la configuration effective des contrôles périmétriques.', true, 'config', 2),
  ('PR.IR', 'Plan de continuité et de reprise', 'Montre la résilience et la redondance de l''infrastructure.', false, 'document', 3),
  ('DE.CM', 'Journaux et supervision', 'Prouve que les actifs, réseaux et accès sont journalisés et surveillés.', true, 'config', 1),
  ('DE.CM', 'Configuration des outils de détection (EDR, IDS/IPS)', 'Atteste du déploiement d''outils de détection d''intrusion sur le périmètre.', true, 'config', 2),
  ('DE.CM', 'Rapports de supervision des fournisseurs et accès externes', 'Montre la surveillance des activités des tiers.', false, 'record', 3),
  ('DE.AE', 'Règles de corrélation et cas d''usage du SIEM', 'Prouve que les événements sont corrélés pour détecter les anomalies.', true, 'config', 1),
  ('DE.AE', 'Procédure de qualification des événements de sécurité', 'Atteste d''une méthode de tri et de qualification des alertes.', true, 'document', 2),
  ('DE.AE', 'Registre des alertes analysées et seuils d''incident', 'Montre l''analyse effective des événements et les critères d''escalade.', false, 'record', 3),
  ('RS.MA', 'Plan de réponse aux incidents', 'Prouve que la réponse aux incidents est planifiée avec rôles et étapes.', true, 'document', 1),
  ('RS.MA', 'Registre des incidents de sécurité', 'Atteste du traitement et du suivi des incidents jusqu''à clôture.', true, 'record', 2),
  ('RS.MA', 'Rapports d''exercices de gestion de crise', 'Montre que le plan est testé.', false, 'record', 3),
  ('RS.AN', 'Rapports d''analyse post-incident', 'Prouve que les causes et l''impact des incidents sont investigués.', true, 'document', 1),
  ('RS.AN', 'Procédure de collecte et préservation des preuves forensiques', 'Atteste que les preuves numériques sont conservées de manière exploitable.', true, 'document', 2),
  ('RS.AN', 'Matrice de catégorisation et de priorisation des incidents', 'Montre que les incidents sont classés selon leur gravité.', false, 'document', 3),
  ('RS.CO', 'Plan de communication de crise et annuaire d''escalade', 'Prouve que les contacts internes et externes sont définis pour les incidents.', true, 'document', 1),
  ('RS.CO', 'Modèles et preuves de notification aux autorités et clients', 'Atteste du respect des obligations de notification d''incident.', true, 'record', 2),
  ('RS.CO', 'Accords de partage d''information sur les menaces', 'Montre la coordination avec CERT et pairs sectoriels.', false, 'document', 3),
  ('RS.MI', 'Playbooks de confinement et d''éradication', 'Prouve que des procédures d''endiguement des incidents sont définies.', true, 'document', 1),
  ('RS.MI', 'Journal des actions de confinement réalisées', 'Atteste des mesures prises pour limiter l''expansion d''incidents réels.', true, 'record', 2),
  ('RS.MI', 'Registre des vulnérabilités exploitées et mesures correctives', 'Montre le traitement des failles à l''origine des incidents.', false, 'record', 3),
  ('RC.RP', 'Plan de continuité et de reprise', 'Prouve que la restauration des services critiques est planifiée avec RTO/RPO.', true, 'document', 1),
  ('RC.RP', 'Rapports de tests de restauration et de reprise', 'Atteste que les capacités de rétablissement sont testées.', true, 'record', 2),
  ('RC.RP', 'Rapport de clôture et retour d''expérience de rétablissement', 'Montre la validation de la restauration et les leçons tirées.', false, 'document', 3),
  ('RC.CO', 'Plan de communication de rétablissement', 'Prouve que la communication aux parties prenantes durant la reprise est prévue.', true, 'document', 1),
  ('RC.CO', 'Communications émises lors des reprises d''activité', 'Atteste de l''information effective des parties prenantes et du public.', true, 'record', 2)
) as r(code, name, descr, is_req, kind, ord)
join public.controls c on c.code = r.code and c.domain_id in (select id from public.domains where framework_id = '00000000-0000-0000-0000-000000000011')
join public.evidence_items ei on ei.name = r.name and ei.framework_id = '00000000-0000-0000-0000-000000000011'
where not exists (select 1 from public.evidence_catalog ec where ec.control_id = c.id and ec.evidence_item_id = ei.id);
