-- 00288 — Contenu des preuves attendues (AUDIT, modèle mutualisé).
insert into public.evidence_items (framework_id, name, description, kind)
select '00000000-0000-0000-0000-000000000014', t.name, t.descr, t.kind from (values
  ('Cadre de gouvernance SI', 'Prouve l''existence d''un cadre de gouvernance SI approuvé par la direction.', 'policy'),
  ('Preuve de communication du cadre de gouvernance', 'Prouve la diffusion du cadre aux parties prenantes.', 'record'),
  ('Document d''alignement stratégique SI/métier', 'Prouve la correspondance entre objectifs métier et initiatives SI.', 'document'),
  ('Budget et plan stratégique SI', 'Prouve que les investissements SI suivent les priorités métier.', 'document'),
  ('Charte du comité de pilotage SI', 'Prouve le mandat, la composition et la fréquence du comité.', 'document'),
  ('Procès-verbaux des comités de pilotage SI', 'Prouve la tenue régulière des réunions et les décisions prises.', 'record'),
  ('Calendrier et feuilles de présence des comités', 'Prouve l''assiduité et la régularité.', 'record'),
  ('Matrice RACI SI', 'Prouve l''attribution des rôles et responsabilités SI.', 'document'),
  ('Fiches de poste des fonctions SI clés', 'Prouve la formalisation des responsabilités individuelles.', 'document'),
  ('Organigramme de la DSI', 'Prouve la structure et les périmètres de la DSI.', 'document'),
  ('Description des périmètres de responsabilité de la DSI', 'Prouve la répartition des responsabilités par équipe.', 'document'),
  ('Rapports de suivi budgétaire SI et analyse des écarts', 'Prouve le suivi périodique et l''analyse des écarts.', 'record'),
  ('Tableau de bord et indicateurs SI', 'Prouve la mesure de la performance SI.', 'record'),
  ('Comptes rendus de reporting SI à la direction', 'Prouve la communication régulière à la direction.', 'record'),
  ('Cartographie des compétences SI', 'Prouve l''identification des compétences et des écarts.', 'document'),
  ('Plan de formation SI', 'Prouve la planification des formations.', 'document'),
  ('Attestations de formation SI', 'Prouve la réalisation des formations.', 'record'),
  ('Procédure de gestion des relations métier', 'Prouve la formalisation de la relation IT/métier.', 'document'),
  ('Comptes rendus de réunions IT/métier', 'Prouve les échanges réguliers avec les parties prenantes.', 'record'),
  ('Enquêtes de satisfaction des utilisateurs métier', 'Prouve le recueil du retour des métiers.', 'record'),
  ('Politique et exigences qualité SI', 'Prouve la définition des exigences de qualité.', 'policy'),
  ('Rapports de suivi qualité SI', 'Prouve le suivi de la qualité et des actions correctives.', 'record'),
  ('Registre des exigences légales et réglementaires SI', 'Prouve l''identification des obligations applicables.', 'record'),
  ('Rapports de veille et de conformité réglementaire', 'Prouve le suivi de la conformité.', 'record'),
  ('Rapports de contrôle interne / audit', 'Prouve les contrôles de conformité réalisés.', 'record'),
  ('Programme d''audit interne SI', 'Prouve la planification des audits SI.', 'document'),
  ('Plan d''actions correctives et suivi d''amélioration continue', 'Prouve le traitement des constats.', 'record'),
  ('Déclaration d''appétence au risque IT', 'Prouve la définition des seuils de risque acceptable.', 'policy'),
  ('Décision de validation par la direction', 'Prouve l''approbation par la direction.', 'record'),
  ('Méthodologie d''analyse de risques SI', 'Prouve la formalisation de la méthode.', 'document'),
  ('Registre des risques IT', 'Prouve l''application de la méthodologie.', 'record'),
  ('Rapport d''analyse de risques SI', 'Prouve une analyse réalisée.', 'record'),
  ('Cartographie des risques SI (matrice)', 'Prouve la représentation et la priorisation des risques.', 'document'),
  ('Historique des mises à jour de la cartographie', 'Prouve la mise à jour régulière.', 'record'),
  ('Plans de traitement des risques SI', 'Prouve la définition d''actions par risque.', 'document'),
  ('Suivi d''avancement des plans de traitement', 'Prouve l''exécution des traitements.', 'record'),
  ('Procédure de veille sur les menaces et vulnérabilités', 'Prouve le processus de veille.', 'document'),
  ('Bulletins de veille et alertes CERT analysés', 'Prouve la collecte et l''analyse des informations.', 'record'),
  ('Rapports de scan de vulnérabilités', 'Prouve l''identification des vulnérabilités.', 'record'),
  ('Comptes rendus de revue périodique des risques', 'Prouve la revue régulière des risques.', 'record'),
  ('Plans de traitement mis à jour', 'Prouve l''actualisation des traitements.', 'record'),
  ('Politique de gestion des risques de l''organisation', 'Prouve le dispositif global de gestion des risques.', 'policy'),
  ('Cartographie des risques groupe incluant les risques SI', 'Prouve l''intégration des risques SI.', 'document'),
  ('Schéma directeur SI', 'Prouve la définition de la trajectoire SI.', 'document'),
  ('Validation du schéma directeur par la direction', 'Prouve l''approbation.', 'record'),
  ('Documentation d''architecture d''entreprise', 'Prouve la documentation des couches métier, applicative, technique et données.', 'document'),
  ('Cartographie des applications et du SI', 'Prouve la couche applicative.', 'document'),
  ('Historique de mise à jour de l''inventaire applicatif', 'Prouve la maintenance à jour.', 'record'),
  ('Schémas d''architecture réseau', 'Prouve la documentation du réseau et des zones de sécurité.', 'document'),
  ('Documentation de l''infrastructure', 'Prouve l''inventaire des composants d''infrastructure.', 'document'),
  ('Règles de segmentation et de filtrage réseau', 'Prouve la mise en oeuvre des zones.', 'config'),
  ('Principes d''architecture sécurisée', 'Prouve la définition du security by design.', 'policy'),
  ('Politique de sécurité SI', 'Prouve les exigences de sécurité applicables.', 'policy'),
  ('Revues d''architecture sécurité de projets', 'Prouve l''application des principes.', 'record'),
  ('Procédure de veille technologique', 'Prouve l''existence du processus de veille.', 'document'),
  ('Rapports de veille technologique et propositions d''innovation', 'Prouve l''identification d''opportunités.', 'record'),
  ('Plan de transformation digitale', 'Prouve la définition de la trajectoire de transformation.', 'document'),
  ('Suivi d''avancement de la transformation digitale', 'Prouve le suivi du plan.', 'record'),
  ('Portefeuille de projets et services', 'Prouve l''inventaire des projets et services.', 'document'),
  ('Critères de priorisation des projets', 'Prouve la méthode de priorisation.', 'document'),
  ('Comptes rendus d''arbitrage du portefeuille', 'Prouve les décisions de priorisation.', 'record'),
  ('Politique de gestion des données', 'Prouve la formalisation et l''approbation de la politique.', 'policy'),
  ('Rôles de gouvernance des données', 'Prouve la désignation de responsables des données.', 'document'),
  ('Politique de classification des informations', 'Prouve les niveaux de sensibilité définis.', 'policy'),
  ('Inventaire des informations classifiées', 'Prouve l''application de la classification.', 'record'),
  ('Règles de marquage et de manipulation', 'Prouve le traitement selon la classification.', 'document'),
  ('Inventaire des actifs informationnels', 'Prouve l''inventaire des actifs matériels, logiciels et données.', 'record'),
  ('Attribution des propriétaires d''actifs', 'Prouve la responsabilité sur les actifs.', 'record'),
  ('Registre des traitements de données personnelles', 'Prouve la tenue du registre (art. 30 RGPD).', 'record'),
  ('Procédure de mise à jour du registre', 'Prouve sa maintenance.', 'document'),
  ('Procédure d''analyse d''impact (AIPD)', 'Prouve la méthode et les critères de déclenchement.', 'document'),
  ('AIPD réalisées', 'Prouve la réalisation d''analyses pour les traitements à risque.', 'record'),
  ('Liste des traitements soumis à AIPD', 'Prouve l''identification des traitements à risque.', 'record'),
  ('Procédure d''exercice des droits des personnes', 'Prouve le processus de traitement des demandes.', 'document'),
  ('Registre des demandes d''exercice de droits', 'Prouve le traitement dans les délais.', 'record'),
  ('Mentions d''information et canal de contact', 'Prouve l''information des personnes.', 'document'),
  ('Politique de conservation, archivage et suppression', 'Prouve les durées de conservation définies.', 'policy'),
  ('Procès-verbaux de destruction et suppressions sécurisées', 'Prouve l''application des suppressions.', 'record'),
  ('Paramétrage des purges automatiques', 'Prouve la mise en oeuvre technique.', 'config'),
  ('Cartographie des flux et transferts de données', 'Prouve l''identification des transferts.', 'document'),
  ('Clauses contractuelles et garanties de transfert', 'Prouve l''encadrement juridique des transferts.', 'document'),
  ('Configuration du chiffrement des échanges', 'Prouve la sécurisation technique des transferts.', 'config'),
  ('Inventaire des enregistrements réglementaires', 'Prouve l''identification des enregistrements à protéger.', 'record'),
  ('Configuration de sauvegarde et d''intégrité des enregistrements', 'Prouve la protection contre perte et altération.', 'config'),
  ('Rapports de test de restauration', 'Prouve la restaurabilité des enregistrements.', 'record'),
  ('Inventaire des licences logicielles', 'Prouve le suivi des licences acquises et déployées.', 'record'),
  ('Rapports de conformité des licences', 'Prouve la concordance licences/installations.', 'record'),
  ('Politique de propriété intellectuelle', 'Prouve la protection de la propriété intellectuelle.', 'policy'),
  ('Catalogue de services SI', 'Prouve la formalisation des services IT.', 'document'),
  ('Preuve d''accessibilité du catalogue', 'Prouve sa mise à disposition aux utilisateurs.', 'record'),
  ('Contrats et SLA fournisseurs', 'Prouve les SLA contractualisés.', 'document'),
  ('Rapports de suivi des niveaux de service', 'Prouve le suivi des SLA des services critiques.', 'record'),
  ('Procédure du Service Desk', 'Prouve le point de contact unique et le processus.', 'document'),
  ('Procédures d''exploitation', 'Prouve le traitement des demandes et incidents.', 'document'),
  ('Extraction des tickets d''incidents et demandes', 'Prouve le fonctionnement effectif du centre de services.', 'record'),
  ('Runbooks et fiches d''exploitation des systèmes critiques', 'Instructions opérationnelles détaillées par système', 'document'),
  ('Historique de révision des procédures', 'Preuve de maintenance et d''approbation périodique des procédures', 'record'),
  ('Procédure de gestion des incidents IT', 'Processus de qualification, priorisation, escalade et clôture des incidents', 'policy'),
  ('Extrait du registre des incidents (outil de ticketing)', 'Incidents réellement traités avec horodatage, priorité et résolution', 'record'),
  ('Rapport mensuel des incidents et respect des délais', 'Suivi des délais de prise en charge et de résolution', 'record'),
  ('Procédure de gestion des problèmes', 'Méthode d''analyse des causes racines des incidents récurrents', 'policy'),
  ('Registre des problèmes et analyses de causes racines', 'Problèmes ouverts/clos avec cause identifiée et action corrective', 'record'),
  ('Revue des incidents récurrents', 'Preuve de l''identification des incidents répétitifs et de leur traitement', 'record'),
  ('Procédure de gestion des changements', 'Processus de demande, évaluation, approbation et mise en œuvre des changements', 'policy'),
  ('Extrait du registre des changements (RFC)', 'Changements tracés avec approbation, impact et plan de retour arrière', 'record'),
  ('Classification des changements (standard, normal, urgent)', 'Règles de catégorisation et circuits d''approbation associés', 'document'),
  ('Charte du comité de changements (CAB)', 'Composition, rôle et fréquence du CAB', 'document'),
  ('Comptes rendus et ordres du jour du CAB', 'Décisions d''approbation ou de refus des changements significatifs', 'record'),
  ('Liste des changements approuvés par le CAB', 'Lien entre changements déployés et validation préalable', 'record'),
  ('Procédure de mise en production', 'Étapes de planification, tests, validation et déploiement', 'policy'),
  ('Plan et calendrier des mises en production', 'Planification des releases et fenêtres de déploiement', 'document'),
  ('PV de recette et tests avant production', 'Preuve des tests et de l''acceptation avant déploiement', 'record'),
  ('Journal des déploiements', 'Traçabilité des mises en production réalisées', 'record'),
  ('Inventaire des actifs IT', 'Liste à jour du matériel et des logiciels avec propriétaire et statut', 'record'),
  ('Procédure de gestion du cycle de vie des actifs', 'Règles d''acquisition, affectation, maintenance et retrait', 'policy'),
  ('Plan de renouvellement du parc et fin de support', 'Anticipation de l''obsolescence des actifs', 'document'),
  ('Extrait de la CMDB', 'Éléments de configuration et leurs relations enregistrés', 'record'),
  ('Procédure de gestion de la configuration', 'Règles de mise à jour et de contrôle de la CMDB', 'policy'),
  ('Politique de sauvegarde', 'Fréquence, rétention et périmètre des sauvegardes définis', 'policy'),
  ('Configuration des jobs de sauvegarde', 'Paramétrage réel des sauvegardes planifiées', 'config'),
  ('Rapports d''exécution des sauvegardes', 'Succès/échec des sauvegardes sur une période', 'record'),
  ('Procédure de restauration', 'Étapes documentées pour restaurer données et systèmes', 'policy'),
  ('Rapports de tests de restauration', 'Résultats datés des restaurations testées et écarts constatés', 'record'),
  ('Planning des tests de restauration', 'Périodicité définie des tests', 'document'),
  ('Rapport de disponibilité des services', 'Taux de disponibilité mesuré par service critique', 'record'),
  ('Accords de niveau de service internes (SLA/OLA)', 'Niveaux de disponibilité convenus avec les métiers', 'document'),
  ('Rapports de supervision de la capacité', 'Taux d''utilisation CPU, mémoire, stockage et bande passante', 'record'),
  ('Plan de capacité et de dimensionnement', 'Prévisions de besoins futurs et dimensionnement', 'document'),
  ('Configuration des seuils d''alerte de supervision', 'Alertes de saturation paramétrées sur les ressources', 'config'),
  ('Architecture de haute disponibilité', 'Schémas de redondance des systèmes critiques', 'document'),
  ('Configuration des clusters et du basculement', 'Paramétrage réel de la redondance et du failover', 'config'),
  ('Rapports de tests de basculement', 'Preuve du fonctionnement des mécanismes de redondance', 'record'),
  ('Plan de continuité informatique', 'PCA formalisé couvrant les services critiques', 'document'),
  ('Analyse d''impact sur l''activité (BIA)', 'Identification des services critiques, RTO et RPO', 'document'),
  ('Plan de reprise d''activité IT (PRA)', 'Procédures de reprise des systèmes critiques', 'document'),
  ('Procédures de reprise par système critique', 'Instructions détaillées de redémarrage et reconstruction', 'document'),
  ('Documentation du site de secours', 'Description de l''infrastructure de repli', 'document'),
  ('Rapports de tests PCA/PRA', 'Résultats des exercices de continuité et de reprise', 'record'),
  ('Planning annuel des tests PCA/PRA', 'Périodicité des exercices définie', 'document'),
  ('Plan d''actions correctives post-test', 'Suivi des écarts relevés lors des tests', 'record'),
  ('Méthodologie de gestion de projets SI', 'Cadre formalisé (cycle de vie, jalons, livrables) appliqué aux projets', 'policy'),
  ('Dossiers de projets SI (échantillon)', 'Application effective de la méthodologie sur des projets réels', 'record'),
  ('Politique de développement sécurisé', 'Exigences de sécurité intégrées au cycle de développement', 'policy'),
  ('Rapports de revue de code et tests de sécurité', 'Preuve de tests sécurité (SAST/DAST, revue de code)', 'record'),
  ('Exigences de sécurité des projets (échantillon)', 'Prise en compte de la sécurité dès la conception', 'document'),
  ('Schéma d''architecture des environnements', 'Isolation des environnements dev, test et production', 'document'),
  ('Configuration de la séparation réseau et des accès', 'Règles de segmentation entre environnements', 'config'),
  ('Matrice des accès par environnement', 'Droits distincts des développeurs sur la production', 'record'),
  ('Preuve de diffusion de la politique', 'Communication aux collaborateurs (accusés, intranet)', 'record'),
  ('Historique de révision de la politique', 'Revue périodique et versions approuvées', 'record'),
  ('Organigramme de la sécurité', 'Structure et rattachement de la fonction sécurité', 'document'),
  ('Lettre de nomination du RSSI et fiche de poste', 'Désignation formelle et responsabilités du RSSI', 'document'),
  ('Procédure de gestion des incidents de sécurité', 'Détection, escalade et réponse aux incidents de sécurité', 'policy'),
  ('Registre des incidents de sécurité', 'Incidents de sécurité traités et leçons apprises', 'record'),
  ('Configuration de la supervision de sécurité (SIEM/alertes)', 'Dispositif de détection des événements de sécurité', 'config'),
  ('Procédure de notification des violations de données', 'Délais, autorités et personnes à notifier', 'policy'),
  ('Modèles de notification (autorité et personnes concernées)', 'Gabarits prêts à l''emploi', 'document'),
  ('Registre des violations de données', 'Violations enregistrées et notifications effectuées', 'record'),
  ('Politique de sécurité des fournisseurs', 'Exigences de sécurité imposées aux tiers', 'policy'),
  ('Évaluations de sécurité des fournisseurs', 'Questionnaires ou audits de fournisseurs critiques', 'record'),
  ('Cartographie de la chaîne d''approvisionnement numérique', 'Fournisseurs et composants critiques identifiés', 'document'),
  ('Analyse des risques supply chain', 'Risques évalués et mesures de traitement', 'record'),
  ('Politique d''usage des services cloud', 'Règles d''adoption et de sécurité du cloud', 'policy'),
  ('Évaluations de sécurité des fournisseurs cloud', 'Certifications et analyses de risques des prestataires cloud', 'record'),
  ('Rapports de suivi des services cloud', 'Suivi de la sécurité et configuration du cloud', 'record'),
  ('Procédure de vérification des antécédents', 'Règles et périmètre des vérifications avant embauche', 'policy'),
  ('Preuves de vérifications (échantillon de dossiers)', 'Contrôles effectivement réalisés sur des recrutements récents', 'record'),
  ('Programme annuel de sensibilisation sécurité', 'Plan de formation et de sensibilisation', 'document'),
  ('Listes de présence et attestations de formation', 'Participation effective des collaborateurs', 'record'),
  ('Résultats de campagnes de sensibilisation (ex. hameçonnage)', 'Efficacité du programme mesurée', 'record'),
  ('Procédure de départ et de mutation', 'Révocation des accès et restitution des actifs', 'policy'),
  ('Checklists de départ renseignées (échantillon)', 'Application effective de la procédure', 'record'),
  ('Extrait des comptes désactivés vs départs RH', 'Rapprochement des départs et des révocations d''accès', 'record'),
  ('Modèle d''accord de confidentialité (NDA)', 'Clauses types de confidentialité', 'document'),
  ('NDA signés (échantillon collaborateurs et prestataires)', 'Signature effective des accords', 'record'),
  ('Politique de télétravail et d''accès distant', 'Règles de sécurité du travail à distance', 'policy'),
  ('Configuration VPN et accès distant', 'Paramétrage sécurisé des accès distants', 'config'),
  ('Charte de sécurité signée par les télétravailleurs', 'Engagement des utilisateurs', 'record'),
  ('Politique de sécurité physique', 'Règles de contrôle des accès physiques', 'policy'),
  ('Liste des accès autorisés aux zones sensibles', 'Droits d''accès physique revus', 'record'),
  ('Journaux d''accès et registre des visiteurs', 'Traçabilité des entrées en zones sensibles', 'record'),
  ('Rapports de maintenance incendie, onduleurs et climatisation', 'Entretien des dispositifs de protection environnementale', 'record'),
  ('Plans et descriptif des protections de la salle serveur', 'Dispositifs incendie, électrique et climatique installés', 'document'),
  ('Rapports de tests des onduleurs et groupe électrogène', 'Fonctionnement vérifié', 'record'),
  ('Procédure de mise au rebut sécurisée', 'Méthodes d''effacement et de destruction des supports', 'policy'),
  ('Certificats d''effacement ou de destruction', 'Preuve d''effacement sécurisé du matériel retiré', 'record'),
  ('Registre des équipements mis au rebut', 'Traçabilité des actifs sortis du parc', 'record'),
  ('Politique de contrôle d''accès', 'Règles de gestion des accès logiques', 'policy'),
  ('Matrice des droits d''accès', 'Profils et droits par rôle', 'document'),
  ('Rapports de revue périodique des accès', 'Revue et recertification des droits', 'record'),
  ('Inventaire des comptes à privilèges', 'Liste des comptes administrateurs avec propriétaires', 'record'),
  ('Procédure de gestion des accès privilégiés', 'Règles d''octroi et de restriction', 'policy'),
  ('Journaux d''activité des comptes administrateurs', 'Surveillance des actions privilégiées', 'record'),
  ('Politique d''authentification', 'Exigences MFA sur les systèmes critiques', 'policy'),
  ('Configuration MFA des systèmes critiques', 'Paramétrage réel de l''authentification multi-facteurs', 'config'),
  ('Rapport de couverture MFA', 'Proportion de comptes protégés par MFA', 'record'),
  ('Politique de chiffrement', 'Exigences de chiffrement en transit et au repos', 'policy'),
  ('Configuration du chiffrement (TLS, disques, bases)', 'Paramétrage réel du chiffrement', 'config'),
  ('Procédure de gestion des clés cryptographiques', 'Cycle de vie et protection des clés', 'policy'),
  ('Schéma d''architecture réseau', 'Segmentation et zones réseau', 'document'),
  ('Configuration du pare-feu et des règles de filtrage', 'Règles de filtrage réellement appliquées', 'config'),
  ('Rapports de supervision et revue des règles de filtrage', 'Surveillance active et revue périodique', 'record')
) as t(name, descr, kind)
where not exists (select 1 from public.evidence_items ei where ei.framework_id = '00000000-0000-0000-0000-000000000014' and ei.name = t.name);

insert into public.evidence_catalog (control_id, evidence_item_id, name, description, is_required, kind, sort_order)
select c.id, ei.id, r.name, r.descr, r.is_req, r.kind, r.ord from (values
  ('GO.01', 'Cadre de gouvernance SI', 'Prouve l''existence d''un cadre de gouvernance SI approuvé par la direction.', true, 'policy', 1),
  ('GO.01', 'Preuve de communication du cadre de gouvernance', 'Prouve la diffusion du cadre aux parties prenantes.', false, 'record', 2),
  ('GO.02', 'Document d''alignement stratégique SI/métier', 'Prouve la correspondance entre objectifs métier et initiatives SI.', true, 'document', 1),
  ('GO.02', 'Budget et plan stratégique SI', 'Prouve que les investissements SI suivent les priorités métier.', false, 'document', 2),
  ('GO.03', 'Charte du comité de pilotage SI', 'Prouve le mandat, la composition et la fréquence du comité.', true, 'document', 1),
  ('GO.03', 'Procès-verbaux des comités de pilotage SI', 'Prouve la tenue régulière des réunions et les décisions prises.', true, 'record', 2),
  ('GO.03', 'Calendrier et feuilles de présence des comités', 'Prouve l''assiduité et la régularité.', false, 'record', 3),
  ('GO.04', 'Matrice RACI SI', 'Prouve l''attribution des rôles et responsabilités SI.', true, 'document', 1),
  ('GO.04', 'Fiches de poste des fonctions SI clés', 'Prouve la formalisation des responsabilités individuelles.', false, 'document', 2),
  ('GO.04', 'Cadre de gouvernance SI', 'Définit les rôles dans le cadre de gouvernance.', false, 'policy', 3),
  ('GO.05', 'Organigramme de la DSI', 'Prouve la structure et les périmètres de la DSI.', true, 'document', 1),
  ('GO.05', 'Description des périmètres de responsabilité de la DSI', 'Prouve la répartition des responsabilités par équipe.', false, 'document', 2),
  ('GO.06', 'Budget et plan stratégique SI', 'Prouve la définition du budget SI validé.', true, 'document', 1),
  ('GO.06', 'Rapports de suivi budgétaire SI et analyse des écarts', 'Prouve le suivi périodique et l''analyse des écarts.', true, 'record', 2),
  ('GO.07', 'Tableau de bord et indicateurs SI', 'Prouve la mesure de la performance SI.', true, 'record', 1),
  ('GO.07', 'Comptes rendus de reporting SI à la direction', 'Prouve la communication régulière à la direction.', true, 'record', 2),
  ('GO.08', 'Cartographie des compétences SI', 'Prouve l''identification des compétences et des écarts.', true, 'document', 1),
  ('GO.08', 'Plan de formation SI', 'Prouve la planification des formations.', true, 'document', 2),
  ('GO.08', 'Attestations de formation SI', 'Prouve la réalisation des formations.', false, 'record', 3),
  ('GO.09', 'Procédure de gestion des relations métier', 'Prouve la formalisation de la relation IT/métier.', true, 'document', 1),
  ('GO.09', 'Comptes rendus de réunions IT/métier', 'Prouve les échanges réguliers avec les parties prenantes.', true, 'record', 2),
  ('GO.09', 'Enquêtes de satisfaction des utilisateurs métier', 'Prouve le recueil du retour des métiers.', false, 'record', 3),
  ('GO.10', 'Politique et exigences qualité SI', 'Prouve la définition des exigences de qualité.', true, 'policy', 1),
  ('GO.10', 'Rapports de suivi qualité SI', 'Prouve le suivi de la qualité et des actions correctives.', true, 'record', 2),
  ('GO.10', 'Tableau de bord et indicateurs SI', 'Indicateurs qualité suivis.', false, 'record', 3),
  ('GO.11', 'Registre des exigences légales et réglementaires SI', 'Prouve l''identification des obligations applicables.', true, 'record', 1),
  ('GO.11', 'Rapports de veille et de conformité réglementaire', 'Prouve le suivi de la conformité.', true, 'record', 2),
  ('GO.11', 'Rapports de contrôle interne / audit', 'Prouve les contrôles de conformité réalisés.', false, 'record', 3),
  ('GO.12', 'Programme d''audit interne SI', 'Prouve la planification des audits SI.', true, 'document', 1),
  ('GO.12', 'Rapports de contrôle interne / audit', 'Prouve la réalisation des audits.', true, 'record', 2),
  ('GO.12', 'Plan d''actions correctives et suivi d''amélioration continue', 'Prouve le traitement des constats.', true, 'record', 3),
  ('GR.01', 'Déclaration d''appétence au risque IT', 'Prouve la définition des seuils de risque acceptable.', true, 'policy', 1),
  ('GR.01', 'Décision de validation par la direction', 'Prouve l''approbation par la direction.', false, 'record', 2),
  ('GR.02', 'Méthodologie d''analyse de risques SI', 'Prouve la formalisation de la méthode.', true, 'document', 1),
  ('GR.02', 'Registre des risques IT', 'Prouve l''application de la méthodologie.', true, 'record', 2),
  ('GR.02', 'Rapport d''analyse de risques SI', 'Prouve une analyse réalisée.', false, 'record', 3),
  ('GR.03', 'Registre des risques IT', 'Prouve l''identification et l''évaluation des risques.', true, 'record', 1),
  ('GR.03', 'Cartographie des risques SI (matrice)', 'Prouve la représentation et la priorisation des risques.', true, 'document', 2),
  ('GR.03', 'Historique des mises à jour de la cartographie', 'Prouve la mise à jour régulière.', false, 'record', 3),
  ('GR.04', 'Plans de traitement des risques SI', 'Prouve la définition d''actions par risque.', true, 'document', 1),
  ('GR.04', 'Registre des risques IT', 'Prouve le lien risque / traitement.', false, 'record', 2),
  ('GR.04', 'Suivi d''avancement des plans de traitement', 'Prouve l''exécution des traitements.', false, 'record', 3),
  ('GR.05', 'Procédure de veille sur les menaces et vulnérabilités', 'Prouve le processus de veille.', true, 'document', 1),
  ('GR.05', 'Bulletins de veille et alertes CERT analysés', 'Prouve la collecte et l''analyse des informations.', true, 'record', 2),
  ('GR.05', 'Rapports de scan de vulnérabilités', 'Prouve l''identification des vulnérabilités.', false, 'record', 3),
  ('GR.06', 'Comptes rendus de revue périodique des risques', 'Prouve la revue régulière des risques.', true, 'record', 1),
  ('GR.06', 'Registre des risques IT', 'Prouve la mise à jour après revue.', true, 'record', 2),
  ('GR.06', 'Plans de traitement mis à jour', 'Prouve l''actualisation des traitements.', false, 'record', 3),
  ('GR.07', 'Politique de gestion des risques de l''organisation', 'Prouve le dispositif global de gestion des risques.', true, 'policy', 1),
  ('GR.07', 'Cartographie des risques groupe incluant les risques SI', 'Prouve l''intégration des risques SI.', true, 'document', 2),
  ('GR.07', 'Registre des risques IT', 'Prouve la consolidation des risques SI.', false, 'record', 3),
  ('AE.01', 'Schéma directeur SI', 'Prouve la définition de la trajectoire SI.', true, 'document', 1),
  ('AE.01', 'Budget et plan stratégique SI', 'Prouve l''alignement avec la stratégie et le financement.', false, 'document', 2),
  ('AE.01', 'Validation du schéma directeur par la direction', 'Prouve l''approbation.', false, 'record', 3),
  ('AE.02', 'Documentation d''architecture d''entreprise', 'Prouve la documentation des couches métier, applicative, technique et données.', true, 'document', 1),
  ('AE.02', 'Cartographie des applications et du SI', 'Prouve la couche applicative.', false, 'document', 2),
  ('AE.03', 'Cartographie des applications et du SI', 'Prouve l''inventaire applicatif et les interdépendances.', true, 'document', 1),
  ('AE.03', 'Historique de mise à jour de l''inventaire applicatif', 'Prouve la maintenance à jour.', false, 'record', 2),
  ('AE.04', 'Schémas d''architecture réseau', 'Prouve la documentation du réseau et des zones de sécurité.', true, 'document', 1),
  ('AE.04', 'Documentation de l''infrastructure', 'Prouve l''inventaire des composants d''infrastructure.', true, 'document', 2),
  ('AE.04', 'Règles de segmentation et de filtrage réseau', 'Prouve la mise en oeuvre des zones.', false, 'config', 3),
  ('AE.05', 'Principes d''architecture sécurisée', 'Prouve la définition du security by design.', true, 'policy', 1),
  ('AE.05', 'Politique de sécurité SI', 'Prouve les exigences de sécurité applicables.', false, 'policy', 2),
  ('AE.05', 'Revues d''architecture sécurité de projets', 'Prouve l''application des principes.', true, 'record', 3),
  ('AE.06', 'Procédure de veille technologique', 'Prouve l''existence du processus de veille.', true, 'document', 1),
  ('AE.06', 'Rapports de veille technologique et propositions d''innovation', 'Prouve l''identification d''opportunités.', true, 'record', 2),
  ('AE.07', 'Plan de transformation digitale', 'Prouve la définition de la trajectoire de transformation.', true, 'document', 1),
  ('AE.07', 'Suivi d''avancement de la transformation digitale', 'Prouve le suivi du plan.', true, 'record', 2),
  ('AE.07', 'Budget et plan stratégique SI', 'Prouve le financement du plan.', false, 'document', 3),
  ('AE.08', 'Portefeuille de projets et services', 'Prouve l''inventaire des projets et services.', true, 'document', 1),
  ('AE.08', 'Critères de priorisation des projets', 'Prouve la méthode de priorisation.', true, 'document', 2),
  ('AE.08', 'Comptes rendus d''arbitrage du portefeuille', 'Prouve les décisions de priorisation.', false, 'record', 3),
  ('GD.01', 'Politique de gestion des données', 'Prouve la formalisation et l''approbation de la politique.', true, 'policy', 1),
  ('GD.01', 'Rôles de gouvernance des données', 'Prouve la désignation de responsables des données.', false, 'document', 2),
  ('GD.02', 'Politique de classification des informations', 'Prouve les niveaux de sensibilité définis.', true, 'policy', 1),
  ('GD.02', 'Inventaire des informations classifiées', 'Prouve l''application de la classification.', true, 'record', 2),
  ('GD.02', 'Règles de marquage et de manipulation', 'Prouve le traitement selon la classification.', false, 'document', 3),
  ('GD.03', 'Inventaire des actifs informationnels', 'Prouve l''inventaire des actifs matériels, logiciels et données.', true, 'record', 1),
  ('GD.03', 'Cartographie des applications et du SI', 'Prouve l''inventaire des actifs applicatifs.', false, 'document', 2),
  ('GD.03', 'Attribution des propriétaires d''actifs', 'Prouve la responsabilité sur les actifs.', false, 'record', 3),
  ('GD.04', 'Registre des traitements de données personnelles', 'Prouve la tenue du registre (art. 30 RGPD).', true, 'record', 1),
  ('GD.04', 'Procédure de mise à jour du registre', 'Prouve sa maintenance.', false, 'document', 2),
  ('GD.05', 'Procédure d''analyse d''impact (AIPD)', 'Prouve la méthode et les critères de déclenchement.', true, 'document', 1),
  ('GD.05', 'AIPD réalisées', 'Prouve la réalisation d''analyses pour les traitements à risque.', true, 'record', 2),
  ('GD.05', 'Liste des traitements soumis à AIPD', 'Prouve l''identification des traitements à risque.', false, 'record', 3),
  ('GD.06', 'Procédure d''exercice des droits des personnes', 'Prouve le processus de traitement des demandes.', true, 'document', 1),
  ('GD.06', 'Registre des demandes d''exercice de droits', 'Prouve le traitement dans les délais.', true, 'record', 2),
  ('GD.06', 'Mentions d''information et canal de contact', 'Prouve l''information des personnes.', false, 'document', 3),
  ('GD.07', 'Politique de conservation, archivage et suppression', 'Prouve les durées de conservation définies.', true, 'policy', 1),
  ('GD.07', 'Procès-verbaux de destruction et suppressions sécurisées', 'Prouve l''application des suppressions.', true, 'record', 2),
  ('GD.07', 'Paramétrage des purges automatiques', 'Prouve la mise en oeuvre technique.', false, 'config', 3),
  ('GD.08', 'Cartographie des flux et transferts de données', 'Prouve l''identification des transferts.', true, 'document', 1),
  ('GD.08', 'Clauses contractuelles et garanties de transfert', 'Prouve l''encadrement juridique des transferts.', true, 'document', 2),
  ('GD.08', 'Configuration du chiffrement des échanges', 'Prouve la sécurisation technique des transferts.', false, 'config', 3),
  ('GD.09', 'Inventaire des enregistrements réglementaires', 'Prouve l''identification des enregistrements à protéger.', true, 'record', 1),
  ('GD.09', 'Configuration de sauvegarde et d''intégrité des enregistrements', 'Prouve la protection contre perte et altération.', true, 'config', 2),
  ('GD.09', 'Rapports de test de restauration', 'Prouve la restaurabilité des enregistrements.', false, 'record', 3),
  ('GD.10', 'Inventaire des licences logicielles', 'Prouve le suivi des licences acquises et déployées.', true, 'record', 1),
  ('GD.10', 'Rapports de conformité des licences', 'Prouve la concordance licences/installations.', true, 'record', 2),
  ('GD.10', 'Politique de propriété intellectuelle', 'Prouve la protection de la propriété intellectuelle.', false, 'policy', 3),
  ('GS.01', 'Catalogue de services SI', 'Prouve la formalisation des services IT.', true, 'document', 1),
  ('GS.01', 'Preuve d''accessibilité du catalogue', 'Prouve sa mise à disposition aux utilisateurs.', false, 'record', 2),
  ('GS.02', 'Contrats et SLA fournisseurs', 'Prouve les SLA contractualisés.', true, 'document', 1),
  ('GS.02', 'Rapports de suivi des niveaux de service', 'Prouve le suivi des SLA des services critiques.', true, 'record', 2),
  ('GS.02', 'Tableau de bord et indicateurs SI', 'Indicateurs de respect des SLA.', false, 'record', 3),
  ('GS.03', 'Procédure du Service Desk', 'Prouve le point de contact unique et le processus.', true, 'document', 1),
  ('GS.03', 'Procédures d''exploitation', 'Prouve le traitement des demandes et incidents.', false, 'document', 2),
  ('GS.03', 'Extraction des tickets d''incidents et demandes', 'Prouve le fonctionnement effectif du centre de services.', true, 'record', 3),
  ('GS.04', 'Procédures d''exploitation', 'Procédures d''exploitation formalisées, versionnées et à jour', true, 'document', 1),
  ('GS.04', 'Runbooks et fiches d''exploitation des systèmes critiques', 'Instructions opérationnelles détaillées par système', false, 'document', 2),
  ('GS.04', 'Historique de révision des procédures', 'Preuve de maintenance et d''approbation périodique des procédures', false, 'record', 3),
  ('GS.05', 'Procédure de gestion des incidents IT', 'Processus de qualification, priorisation, escalade et clôture des incidents', true, 'policy', 1),
  ('GS.05', 'Extrait du registre des incidents (outil de ticketing)', 'Incidents réellement traités avec horodatage, priorité et résolution', true, 'record', 2),
  ('GS.05', 'Rapport mensuel des incidents et respect des délais', 'Suivi des délais de prise en charge et de résolution', false, 'record', 3),
  ('GS.06', 'Procédure de gestion des problèmes', 'Méthode d''analyse des causes racines des incidents récurrents', true, 'policy', 1),
  ('GS.06', 'Registre des problèmes et analyses de causes racines', 'Problèmes ouverts/clos avec cause identifiée et action corrective', true, 'record', 2),
  ('GS.06', 'Revue des incidents récurrents', 'Preuve de l''identification des incidents répétitifs et de leur traitement', false, 'record', 3),
  ('GS.07', 'Procédure de gestion des changements', 'Processus de demande, évaluation, approbation et mise en œuvre des changements', true, 'policy', 1),
  ('GS.07', 'Extrait du registre des changements (RFC)', 'Changements tracés avec approbation, impact et plan de retour arrière', true, 'record', 2),
  ('GS.07', 'Classification des changements (standard, normal, urgent)', 'Règles de catégorisation et circuits d''approbation associés', false, 'document', 3),
  ('GS.08', 'Charte du comité de changements (CAB)', 'Composition, rôle et fréquence du CAB', true, 'document', 1),
  ('GS.08', 'Comptes rendus et ordres du jour du CAB', 'Décisions d''approbation ou de refus des changements significatifs', true, 'record', 2),
  ('GS.08', 'Liste des changements approuvés par le CAB', 'Lien entre changements déployés et validation préalable', false, 'record', 3),
  ('GS.09', 'Procédure de mise en production', 'Étapes de planification, tests, validation et déploiement', true, 'policy', 1),
  ('GS.09', 'Plan et calendrier des mises en production', 'Planification des releases et fenêtres de déploiement', false, 'document', 2),
  ('GS.09', 'PV de recette et tests avant production', 'Preuve des tests et de l''acceptation avant déploiement', true, 'record', 3),
  ('GS.09', 'Journal des déploiements', 'Traçabilité des mises en production réalisées', false, 'record', 4),
  ('GS.10', 'Inventaire des actifs IT', 'Liste à jour du matériel et des logiciels avec propriétaire et statut', true, 'record', 1),
  ('GS.10', 'Procédure de gestion du cycle de vie des actifs', 'Règles d''acquisition, affectation, maintenance et retrait', true, 'policy', 2),
  ('GS.10', 'Plan de renouvellement du parc et fin de support', 'Anticipation de l''obsolescence des actifs', false, 'document', 3),
  ('GS.11', 'Extrait de la CMDB', 'Éléments de configuration et leurs relations enregistrés', true, 'record', 1),
  ('GS.11', 'Procédure de gestion de la configuration', 'Règles de mise à jour et de contrôle de la CMDB', true, 'policy', 2),
  ('GS.11', 'Cartographie des applications et du SI', 'Vue des applications et dépendances du SI', false, 'document', 3),
  ('GS.12', 'Politique de sauvegarde', 'Fréquence, rétention et périmètre des sauvegardes définis', true, 'policy', 1),
  ('GS.12', 'Configuration des jobs de sauvegarde', 'Paramétrage réel des sauvegardes planifiées', true, 'config', 2),
  ('GS.12', 'Rapports d''exécution des sauvegardes', 'Succès/échec des sauvegardes sur une période', false, 'record', 3),
  ('GS.13', 'Procédure de restauration', 'Étapes documentées pour restaurer données et systèmes', true, 'policy', 1),
  ('GS.13', 'Rapports de tests de restauration', 'Résultats datés des restaurations testées et écarts constatés', true, 'record', 2),
  ('GS.13', 'Planning des tests de restauration', 'Périodicité définie des tests', false, 'document', 3),
  ('GS.14', 'Rapport de disponibilité des services', 'Taux de disponibilité mesuré par service critique', true, 'record', 1),
  ('GS.14', 'Contrats et SLA fournisseurs', 'Niveaux de service convenus avec les fournisseurs', false, 'document', 2),
  ('GS.14', 'Tableau de bord et indicateurs SI', 'Suivi des indicateurs de disponibilité et des écarts vs SLA', true, 'document', 3),
  ('GS.14', 'Accords de niveau de service internes (SLA/OLA)', 'Niveaux de disponibilité convenus avec les métiers', false, 'document', 4),
  ('GS.15', 'Rapports de supervision de la capacité', 'Taux d''utilisation CPU, mémoire, stockage et bande passante', true, 'record', 1),
  ('GS.15', 'Plan de capacité et de dimensionnement', 'Prévisions de besoins futurs et dimensionnement', true, 'document', 2),
  ('GS.15', 'Configuration des seuils d''alerte de supervision', 'Alertes de saturation paramétrées sur les ressources', false, 'config', 3),
  ('GS.16', 'Architecture de haute disponibilité', 'Schémas de redondance des systèmes critiques', true, 'document', 1),
  ('GS.16', 'Configuration des clusters et du basculement', 'Paramétrage réel de la redondance et du failover', true, 'config', 2),
  ('GS.16', 'Rapports de tests de basculement', 'Preuve du fonctionnement des mécanismes de redondance', false, 'record', 3),
  ('GS.17', 'Plan de continuité informatique', 'PCA formalisé couvrant les services critiques', true, 'document', 1),
  ('GS.17', 'Analyse d''impact sur l''activité (BIA)', 'Identification des services critiques, RTO et RPO', true, 'document', 2),
  ('GS.17', 'Registre des risques IT', 'Risques de discontinuité identifiés et traités', false, 'record', 3),
  ('GS.18', 'Plan de reprise d''activité IT (PRA)', 'Procédures de reprise des systèmes critiques', true, 'document', 1),
  ('GS.18', 'Procédures de reprise par système critique', 'Instructions détaillées de redémarrage et reconstruction', false, 'document', 2),
  ('GS.18', 'Documentation du site de secours', 'Description de l''infrastructure de repli', false, 'document', 3),
  ('GS.19', 'Rapports de tests PCA/PRA', 'Résultats des exercices de continuité et de reprise', true, 'record', 1),
  ('GS.19', 'Planning annuel des tests PCA/PRA', 'Périodicité des exercices définie', false, 'document', 2),
  ('GS.19', 'Plan d''actions correctives post-test', 'Suivi des écarts relevés lors des tests', false, 'record', 3),
  ('GS.20', 'Méthodologie de gestion de projets SI', 'Cadre formalisé (cycle de vie, jalons, livrables) appliqué aux projets', true, 'policy', 1),
  ('GS.20', 'Dossiers de projets SI (échantillon)', 'Application effective de la méthodologie sur des projets réels', true, 'record', 2),
  ('GS.20', 'Budget et plan stratégique SI', 'Alignement des projets avec la stratégie et le budget SI', false, 'document', 3),
  ('GS.21', 'Politique de développement sécurisé', 'Exigences de sécurité intégrées au cycle de développement', true, 'policy', 1),
  ('GS.21', 'Rapports de revue de code et tests de sécurité', 'Preuve de tests sécurité (SAST/DAST, revue de code)', true, 'record', 2),
  ('GS.21', 'Exigences de sécurité des projets (échantillon)', 'Prise en compte de la sécurité dès la conception', false, 'document', 3),
  ('GS.22', 'Schéma d''architecture des environnements', 'Isolation des environnements dev, test et production', true, 'document', 1),
  ('GS.22', 'Configuration de la séparation réseau et des accès', 'Règles de segmentation entre environnements', true, 'config', 2),
  ('GS.22', 'Matrice des accès par environnement', 'Droits distincts des développeurs sur la production', false, 'record', 3),
  ('MS.01', 'Politique de sécurité SI', 'Politique formalisée et approuvée par la direction', true, 'policy', 1),
  ('MS.01', 'Preuve de diffusion de la politique', 'Communication aux collaborateurs (accusés, intranet)', true, 'record', 2),
  ('MS.01', 'Historique de révision de la politique', 'Revue périodique et versions approuvées', false, 'record', 3),
  ('MS.02', 'Organigramme de la sécurité', 'Structure et rattachement de la fonction sécurité', true, 'document', 1),
  ('MS.02', 'Lettre de nomination du RSSI et fiche de poste', 'Désignation formelle et responsabilités du RSSI', true, 'document', 2),
  ('MS.02', 'Cadre de gouvernance SI', 'Instances et rôles de gouvernance de la sécurité', false, 'document', 3),
  ('MS.03', 'Procédure de gestion des incidents de sécurité', 'Détection, escalade et réponse aux incidents de sécurité', true, 'policy', 1),
  ('MS.03', 'Registre des incidents de sécurité', 'Incidents de sécurité traités et leçons apprises', true, 'record', 2),
  ('MS.03', 'Configuration de la supervision de sécurité (SIEM/alertes)', 'Dispositif de détection des événements de sécurité', false, 'config', 3),
  ('MS.04', 'Procédure de notification des violations de données', 'Délais, autorités et personnes à notifier', true, 'policy', 1),
  ('MS.04', 'Modèles de notification (autorité et personnes concernées)', 'Gabarits prêts à l''emploi', false, 'document', 2),
  ('MS.04', 'Registre des violations de données', 'Violations enregistrées et notifications effectuées', true, 'record', 3),
  ('MS.05', 'Politique de sécurité des fournisseurs', 'Exigences de sécurité imposées aux tiers', true, 'policy', 1),
  ('MS.05', 'Contrats et SLA fournisseurs', 'Clauses de sécurité contractuelles', true, 'document', 2),
  ('MS.05', 'Évaluations de sécurité des fournisseurs', 'Questionnaires ou audits de fournisseurs critiques', false, 'record', 3),
  ('MS.06', 'Cartographie de la chaîne d''approvisionnement numérique', 'Fournisseurs et composants critiques identifiés', true, 'document', 1),
  ('MS.06', 'Analyse des risques supply chain', 'Risques évalués et mesures de traitement', true, 'record', 2),
  ('MS.06', 'Registre des risques IT', 'Intégration des risques tiers', false, 'record', 3),
  ('MS.07', 'Politique d''usage des services cloud', 'Règles d''adoption et de sécurité du cloud', true, 'policy', 1),
  ('MS.07', 'Évaluations de sécurité des fournisseurs cloud', 'Certifications et analyses de risques des prestataires cloud', true, 'record', 2),
  ('MS.07', 'Rapports de suivi des services cloud', 'Suivi de la sécurité et configuration du cloud', false, 'record', 3),
  ('MS.08', 'Procédure de vérification des antécédents', 'Règles et périmètre des vérifications avant embauche', true, 'policy', 1),
  ('MS.08', 'Preuves de vérifications (échantillon de dossiers)', 'Contrôles effectivement réalisés sur des recrutements récents', true, 'record', 2),
  ('MS.09', 'Programme annuel de sensibilisation sécurité', 'Plan de formation et de sensibilisation', true, 'document', 1),
  ('MS.09', 'Listes de présence et attestations de formation', 'Participation effective des collaborateurs', true, 'record', 2),
  ('MS.09', 'Résultats de campagnes de sensibilisation (ex. hameçonnage)', 'Efficacité du programme mesurée', false, 'record', 3),
  ('MS.10', 'Procédure de départ et de mutation', 'Révocation des accès et restitution des actifs', true, 'policy', 1),
  ('MS.10', 'Checklists de départ renseignées (échantillon)', 'Application effective de la procédure', true, 'record', 2),
  ('MS.10', 'Extrait des comptes désactivés vs départs RH', 'Rapprochement des départs et des révocations d''accès', false, 'record', 3),
  ('MS.11', 'Modèle d''accord de confidentialité (NDA)', 'Clauses types de confidentialité', true, 'document', 1),
  ('MS.11', 'NDA signés (échantillon collaborateurs et prestataires)', 'Signature effective des accords', true, 'record', 2),
  ('MS.12', 'Politique de télétravail et d''accès distant', 'Règles de sécurité du travail à distance', true, 'policy', 1),
  ('MS.12', 'Configuration VPN et accès distant', 'Paramétrage sécurisé des accès distants', true, 'config', 2),
  ('MS.12', 'Charte de sécurité signée par les télétravailleurs', 'Engagement des utilisateurs', false, 'record', 3),
  ('MS.13', 'Politique de sécurité physique', 'Règles de contrôle des accès physiques', true, 'policy', 1),
  ('MS.13', 'Liste des accès autorisés aux zones sensibles', 'Droits d''accès physique revus', true, 'record', 2),
  ('MS.13', 'Journaux d''accès et registre des visiteurs', 'Traçabilité des entrées en zones sensibles', false, 'record', 3),
  ('MS.14', 'Rapports de maintenance incendie, onduleurs et climatisation', 'Entretien des dispositifs de protection environnementale', true, 'record', 1),
  ('MS.14', 'Plans et descriptif des protections de la salle serveur', 'Dispositifs incendie, électrique et climatique installés', true, 'document', 2),
  ('MS.14', 'Rapports de tests des onduleurs et groupe électrogène', 'Fonctionnement vérifié', false, 'record', 3),
  ('MS.15', 'Procédure de mise au rebut sécurisée', 'Méthodes d''effacement et de destruction des supports', true, 'policy', 1),
  ('MS.15', 'Certificats d''effacement ou de destruction', 'Preuve d''effacement sécurisé du matériel retiré', true, 'record', 2),
  ('MS.15', 'Registre des équipements mis au rebut', 'Traçabilité des actifs sortis du parc', false, 'record', 3),
  ('MS.16', 'Politique de contrôle d''accès', 'Règles de gestion des accès logiques', true, 'policy', 1),
  ('MS.16', 'Matrice des droits d''accès', 'Profils et droits par rôle', true, 'document', 2),
  ('MS.16', 'Rapports de revue périodique des accès', 'Revue et recertification des droits', true, 'record', 3),
  ('MS.17', 'Inventaire des comptes à privilèges', 'Liste des comptes administrateurs avec propriétaires', true, 'record', 1),
  ('MS.17', 'Procédure de gestion des accès privilégiés', 'Règles d''octroi et de restriction', false, 'policy', 2),
  ('MS.17', 'Journaux d''activité des comptes administrateurs', 'Surveillance des actions privilégiées', true, 'record', 3),
  ('MS.18', 'Politique d''authentification', 'Exigences MFA sur les systèmes critiques', true, 'policy', 1),
  ('MS.18', 'Configuration MFA des systèmes critiques', 'Paramétrage réel de l''authentification multi-facteurs', true, 'config', 2),
  ('MS.18', 'Rapport de couverture MFA', 'Proportion de comptes protégés par MFA', false, 'record', 3),
  ('MS.19', 'Politique de chiffrement', 'Exigences de chiffrement en transit et au repos', true, 'policy', 1),
  ('MS.19', 'Configuration du chiffrement (TLS, disques, bases)', 'Paramétrage réel du chiffrement', true, 'config', 2),
  ('MS.19', 'Procédure de gestion des clés cryptographiques', 'Cycle de vie et protection des clés', false, 'policy', 3),
  ('MS.20', 'Schéma d''architecture réseau', 'Segmentation et zones réseau', true, 'document', 1),
  ('MS.20', 'Configuration du pare-feu et des règles de filtrage', 'Règles de filtrage réellement appliquées', true, 'config', 2),
  ('MS.20', 'Rapports de supervision et revue des règles de filtrage', 'Surveillance active et revue périodique', false, 'record', 3)
) as r(code, name, descr, is_req, kind, ord)
join public.controls c on c.code = r.code and c.domain_id in (select id from public.domains where framework_id = '00000000-0000-0000-0000-000000000014')
join public.evidence_items ei on ei.name = r.name and ei.framework_id = '00000000-0000-0000-0000-000000000014'
where not exists (select 1 from public.evidence_catalog ec where ec.control_id = c.id and ec.evidence_item_id = ei.id);
