-- 00285 — Contenu des preuves attendues (DUEDIL, modèle mutualisé).
insert into public.evidence_items (framework_id, name, description, kind)
select '00000000-0000-0000-0000-000000000015', t.name, t.descr, t.kind from (values
  ('Documentation d''architecture technique', 'Prouve les technologies retenues et leur justification.', 'document'),
  ('Registre des décisions d''architecture (ADR)', 'Prouve que les choix de stack sont argumentés et tracés.', 'record'),
  ('Inventaire des dépendances et licences', 'Prouve la liste réelle des langages, frameworks et bibliothèques utilisés.', 'record'),
  ('Diagramme des composants et flux de données', 'Prouve la cohérence et l''évolutivité de l''architecture cible.', 'document'),
  ('Guide de standards de code et configuration du linter', 'Prouve l''existence de règles de qualité appliquées automatiquement.', 'config'),
  ('Historique des pull requests avec revues', 'Prouve que les code reviews sont systématiques avant fusion.', 'record'),
  ('Configuration de protection des branches', 'Prouve que la revue est obligatoire techniquement.', 'config'),
  ('Rapports de tests et couverture de code', 'Prouve le niveau de tests automatisés et le taux de couverture mesuré.', 'document'),
  ('Stratégie de tests et résultats récents d''exécution', 'Prouve les types de tests (unitaires, intégration, E2E) et leur exécution régulière.', 'document'),
  ('Extrait de l''historique Git et statistiques de contributions', 'Prouve un historique exploitable et la répartition des contributions.', 'record'),
  ('Stratégie de branching et configuration du dépôt', 'Prouve l''usage d''un modèle de branches défini (GitFlow, trunk-based).', 'config'),
  ('README et guide d''onboarding développeur', 'Prouve qu''un nouveau développeur peut démarrer rapidement.', 'document'),
  ('Documentation des API', 'Prouve que les API sont documentées (Swagger/OpenAPI).', 'document'),
  ('Rapport de tests de charge et de montée en charge', 'Prouve la capacité à absorber une croissance (x10) sans refonte.', 'document'),
  ('Analyse des goulots d''étranglement et plan de croissance', 'Prouve que les limites de scalabilité sont identifiées.', 'document'),
  ('Rapports de mesure de performance (temps de réponse p50/p95/p99)', 'Prouve que les performances sont mesurées et dans les seuils.', 'record'),
  ('Tableau de bord APM ou résultats de tests de charge', 'Prouve le suivi continu des temps de réponse.', 'record'),
  ('Roadmap produit', 'Prouve l''existence d''une vision technique alignée sur le business.', 'document'),
  ('Historique de livraison versus roadmap prévue', 'Prouve le réalisme de l''exécution de la roadmap.', 'record'),
  ('Registre de la dette technique', 'Prouve que la dette technique est identifiée et documentée.', 'document'),
  ('Plan de résorption de la dette technique', 'Prouve qu''un plan et des ressources dédiées existent.', 'document'),
  ('Rapport d''analyse statique de qualité du code', 'Prouve la mesure objective de la dette.', 'record'),
  ('Organigramme technique', 'Prouve la structure de l''équipe et les rôles clés.', 'document'),
  ('Fiches de poste des rôles techniques clés', 'Prouve la clarté des responsabilités et du leadership technique.', 'document'),
  ('Matrice de compétences de l''équipe technique', 'Prouve la couverture des compétences critiques et les trous éventuels.', 'document'),
  ('Plan de formation et montée en compétences', 'Prouve la gestion des lacunes de compétences.', 'document'),
  ('Analyse du risque de dépendance aux personnes clés (bus factor)', 'Prouve que le key-man risk est identifié et mitigé.', 'document'),
  ('Plan de succession et de transfert de connaissances', 'Prouve la continuité en cas de départ d''une personne clé.', 'document'),
  ('Contrats des personnes clés (rétention, préavis)', 'Prouve les mécanismes de rétention.', 'document'),
  ('Processus de recrutement technique et grille d''évaluation', 'Prouve un processus structuré (test technique, entretiens).', 'policy'),
  ('Parcours d''onboarding des nouveaux développeurs', 'Prouve l''intégration efficace des recrues.', 'document'),
  ('Historique des recrutements et délais', 'Prouve la capacité effective à recruter.', 'record'),
  ('Description de la méthodologie de développement', 'Prouve l''usage d''une méthode structurée (Agile/Scrum).', 'policy'),
  ('Historique des sprints, vélocité et rétrospectives', 'Prouve l''application réelle des cérémonies.', 'record'),
  ('Pipeline CI/CD et procédures de déploiement', 'Prouve l''automatisation de l''intégration et du déploiement continus.', 'document'),
  ('Historique d''exécution des pipelines et taux de succès', 'Prouve la fiabilité et la fréquence des déploiements.', 'record'),
  ('Procédure de gestion des incidents de production', 'Prouve l''existence d''un processus de détection et résolution.', 'policy'),
  ('Planning d''astreintes et registre des incidents récents', 'Prouve l''organisation réelle de la réponse aux incidents.', 'record'),
  ('Post-mortems d''incidents', 'Prouve l''apprentissage après incident.', 'document'),
  ('Liste des prestataires et freelances intervenant sur le code', 'Prouve la part du développement externalisé.', 'document'),
  ('Statistiques de contribution externes vs internes au dépôt', 'Prouve la proportion de code écrit par des externes.', 'record'),
  ('Procédure de contrôle du code externe', 'Prouve la revue et l''intégration contrôlées du code externe.', 'policy'),
  ('Politique de sécurité', 'Prouve l''existence d''une politique de sécurité formalisée.', 'document'),
  ('Preuve de diffusion et d''acceptation de la politique', 'Prouve que la politique est communiquée aux équipes.', 'record'),
  ('Revue des droits d''accès aux systèmes critiques', 'Prouve que les accès sont maîtrisés et revus.', 'record'),
  ('Configuration MFA sur les outils sensibles', 'Prouve le déploiement de l''authentification forte.', 'config'),
  ('Procédure d''arrivée et de départ des collaborateurs', 'Prouve la révocation des accès.', 'policy'),
  ('Configuration du chiffrement en transit et au repos', 'Prouve le chiffrement des données sensibles (TLS, stockage, hachage).', 'config'),
  ('Politique de gestion des clés et des secrets', 'Prouve la protection des clés de chiffrement.', 'policy'),
  ('Registre des traitements RGPD', 'Prouve la cartographie des traitements de données personnelles.', 'document'),
  ('Preuve de désignation du DPO et gestion des consentements', 'Prouve la gouvernance RGPD et le recueil des consentements.', 'record'),
  ('Analyses d''impact (AIPD) et contrats de sous-traitance', 'Prouve l''encadrement des traitements à risque.', 'document'),
  ('Cartographie du stockage des données personnelles clients', 'Prouve où et comment les données clients sont stockées.', 'document'),
  ('Journaux d''accès aux données clients', 'Prouve la traçabilité des accès.', 'record'),
  ('Politique de rétention et de suppression des données', 'Prouve la maîtrise du cycle de vie des données.', 'policy'),
  ('Rapport de test d''intrusion récent', 'Prouve un test de sécurité indépendant réalisé par un tiers.', 'document'),
  ('Rapports de scan de vulnérabilités et suivi des corrections', 'Prouve la détection et le traitement des vulnérabilités.', 'record'),
  ('Registre des incidents de sécurité', 'Prouve l''historique complet des incidents de sécurité.', 'record'),
  ('Rapports post-incident et actions correctives', 'Prouve les leçons tirées des brèches.', 'document'),
  ('Notifications de violation de données (le cas échéant)', 'Prouve le respect des obligations de notification.', 'record'),
  ('Politique et configuration des sauvegardes', 'Prouve que des sauvegardes automatiques sont en place.', 'config'),
  ('Rapports de tests de restauration', 'Prouve que les restaurations fonctionnent et leur durée.', 'record'),
  ('Plan de réponse aux incidents de sécurité', 'Prouve l''existence d''un plan avec contacts d''urgence.', 'policy'),
  ('Compte rendu d''exercice ou simulation de crise', 'Prouve que le plan a été testé.', 'record'),
  ('Documentation de l''hébergement (provider, région, type)', 'Prouve le choix et la configuration de l''hébergement de production.', 'document'),
  ('Contrat ou conditions du fournisseur d''hébergement', 'Prouve les engagements et la pérennité du provider.', 'document'),
  ('Factures cloud des 12 derniers mois', 'Prouve les coûts d''infrastructure réels et leur évolution.', 'record'),
  ('Tableau de suivi et prévision des coûts d''infrastructure', 'Prouve la maîtrise et la prévisibilité des coûts.', 'document'),
  ('Configuration du monitoring et des règles d''alerte', 'Prouve la surveillance des systèmes de production.', 'config'),
  ('Historique des alertes et temps de détection', 'Prouve que les anomalies sont détectées avant les utilisateurs.', 'record'),
  ('Historique d''uptime sur 12 mois', 'Prouve la disponibilité réelle mesurée.', 'record'),
  ('Définition du SLA (interne ou client)', 'Prouve les engagements de disponibilité.', 'policy'),
  ('Rapports d''incidents d''indisponibilité', 'Prouve les causes et durées des interruptions.', 'record'),
  ('Historique des déploiements et des rollbacks', 'Prouve la fréquence et la réversibilité des déploiements.', 'record'),
  ('Description des environnements dev, staging et production', 'Prouve la séparation et la cohérence des environnements.', 'document'),
  ('Configuration d''infrastructure as code des environnements', 'Prouve la reproductibilité et la parité des environnements.', 'config'),
  ('Configuration d''autoscaling et architecture d''infrastructure', 'Prouve la capacité de scalabilité horizontale.', 'config'),
  ('Résultats de tests de charge infrastructure', 'Prouve la tenue de charge x10.', 'record'),
  ('Plan de reprise d''activité (PRA)', 'Prouve l''existence d''un PRA couvrant la perte du provider.', 'policy'),
  ('Compte rendu de test du PRA (RTO/RPO)', 'Prouve que le PRA a été testé et ses objectifs atteints.', 'record'),
  ('Attestation de titularité et d''origine du code source', 'Prouve que l''entreprise possède l''intégralité du code.', 'document'),
  ('Analyse des contributeurs au dépôt', 'Prouve l''absence de zones grises sur les contributeurs.', 'record'),
  ('Contrats de cession de droits d''auteur', 'Prouve le transfert de propriété du code.', 'document'),
  ('Contrats de travail avec clause de cession de PI', 'Prouve la cession de PI par les employés.', 'document'),
  ('Pacte d''associés et accords de cession de PI des fondateurs', 'Prouve la cession de PI par les fondateurs.', 'document'),
  ('Rapport d''analyse de conformité des licences (SCA)', 'Prouve l''absence de risque de contamination GPL.', 'record'),
  ('Politique d''usage de l''open source', 'Prouve l''encadrement de l''usage des licences.', 'policy'),
  ('Cartographie des dépendances tierces critiques et risque de lock-in', 'Prouve l''identification des fournisseurs critiques et plans de substitution.', 'document'),
  ('Contrats avec les fournisseurs critiques', 'Prouve les engagements et clauses de réversibilité.', 'document'),
  ('Certificats de dépôt de marques et brevets', 'Prouve la protection juridique de la PI.', 'document'),
  ('Rapport de recherche d''antériorité', 'Prouve la disponibilité des marques et brevets.', 'document'),
  ('Contrats avec les prestataires et freelances techniques', 'Prouve l''inclusion de cession de PI et de confidentialité.', 'document'),
  ('Accords de confidentialité (NDA) signés', 'Prouve les engagements de confidentialité.', 'document'),
  ('Analyse des réglementations sectorielles applicables', 'Prouve l''identification des réglementations applicables au produit.', 'document'),
  ('Preuves de conformité réglementaire (agréments, certifications)', 'Prouve le respect des obligations sectorielles.', 'record')
) as t(name, descr, kind)
where not exists (select 1 from public.evidence_items ei where ei.framework_id = '00000000-0000-0000-0000-000000000015' and ei.name = t.name);

insert into public.evidence_catalog (control_id, evidence_item_id, name, description, is_required, kind, sort_order)
select c.id, ei.id, r.name, r.descr, r.is_req, r.kind, r.ord from (values
  ('PT.01', 'Documentation d''architecture technique', 'Prouve les technologies retenues et leur justification.', true, 'document', 1),
  ('PT.01', 'Registre des décisions d''architecture (ADR)', 'Prouve que les choix de stack sont argumentés et tracés.', false, 'record', 2),
  ('PT.01', 'Inventaire des dépendances et licences', 'Prouve la liste réelle des langages, frameworks et bibliothèques utilisés.', false, 'record', 3),
  ('PT.02', 'Documentation d''architecture technique', 'Prouve l''architecture logicielle avec schémas (composants, flux, données).', true, 'document', 1),
  ('PT.02', 'Diagramme des composants et flux de données', 'Prouve la cohérence et l''évolutivité de l''architecture cible.', false, 'document', 2),
  ('PT.03', 'Guide de standards de code et configuration du linter', 'Prouve l''existence de règles de qualité appliquées automatiquement.', true, 'config', 1),
  ('PT.03', 'Historique des pull requests avec revues', 'Prouve que les code reviews sont systématiques avant fusion.', true, 'record', 2),
  ('PT.03', 'Configuration de protection des branches', 'Prouve que la revue est obligatoire techniquement.', false, 'config', 3),
  ('PT.04', 'Rapports de tests et couverture de code', 'Prouve le niveau de tests automatisés et le taux de couverture mesuré.', true, 'document', 1),
  ('PT.04', 'Stratégie de tests et résultats récents d''exécution', 'Prouve les types de tests (unitaires, intégration, E2E) et leur exécution régulière.', false, 'document', 2),
  ('PT.05', 'Extrait de l''historique Git et statistiques de contributions', 'Prouve un historique exploitable et la répartition des contributions.', true, 'record', 1),
  ('PT.05', 'Stratégie de branching et configuration du dépôt', 'Prouve l''usage d''un modèle de branches défini (GitFlow, trunk-based).', true, 'config', 2),
  ('PT.06', 'README et guide d''onboarding développeur', 'Prouve qu''un nouveau développeur peut démarrer rapidement.', true, 'document', 1),
  ('PT.06', 'Documentation des API', 'Prouve que les API sont documentées (Swagger/OpenAPI).', false, 'document', 2),
  ('PT.06', 'Documentation d''architecture technique', 'Prouve que l''architecture est documentée.', false, 'document', 3),
  ('PT.07', 'Rapport de tests de charge et de montée en charge', 'Prouve la capacité à absorber une croissance (x10) sans refonte.', true, 'document', 1),
  ('PT.07', 'Documentation d''architecture technique', 'Prouve que l''architecture permet le passage à l''échelle.', false, 'document', 2),
  ('PT.07', 'Analyse des goulots d''étranglement et plan de croissance', 'Prouve que les limites de scalabilité sont identifiées.', false, 'document', 3),
  ('PT.08', 'Rapports de mesure de performance (temps de réponse p50/p95/p99)', 'Prouve que les performances sont mesurées et dans les seuils.', true, 'record', 1),
  ('PT.08', 'Tableau de bord APM ou résultats de tests de charge', 'Prouve le suivi continu des temps de réponse.', false, 'record', 2),
  ('PT.09', 'Roadmap produit', 'Prouve l''existence d''une vision technique alignée sur le business.', true, 'document', 1),
  ('PT.09', 'Historique de livraison versus roadmap prévue', 'Prouve le réalisme de l''exécution de la roadmap.', false, 'record', 2),
  ('PT.10', 'Registre de la dette technique', 'Prouve que la dette technique est identifiée et documentée.', true, 'document', 1),
  ('PT.10', 'Plan de résorption de la dette technique', 'Prouve qu''un plan et des ressources dédiées existent.', true, 'document', 2),
  ('PT.10', 'Rapport d''analyse statique de qualité du code', 'Prouve la mesure objective de la dette.', false, 'record', 3),
  ('ET.01', 'Organigramme technique', 'Prouve la structure de l''équipe et les rôles clés.', true, 'document', 1),
  ('ET.01', 'Fiches de poste des rôles techniques clés', 'Prouve la clarté des responsabilités et du leadership technique.', false, 'document', 2),
  ('ET.02', 'Matrice de compétences de l''équipe technique', 'Prouve la couverture des compétences critiques et les trous éventuels.', true, 'document', 1),
  ('ET.02', 'Organigramme technique', 'Prouve les profils en place.', false, 'document', 2),
  ('ET.02', 'Plan de formation et montée en compétences', 'Prouve la gestion des lacunes de compétences.', false, 'document', 3),
  ('ET.03', 'Analyse du risque de dépendance aux personnes clés (bus factor)', 'Prouve que le key-man risk est identifié et mitigé.', true, 'document', 1),
  ('ET.03', 'Plan de succession et de transfert de connaissances', 'Prouve la continuité en cas de départ d''une personne clé.', true, 'document', 2),
  ('ET.03', 'Contrats des personnes clés (rétention, préavis)', 'Prouve les mécanismes de rétention.', false, 'document', 3),
  ('ET.04', 'Processus de recrutement technique et grille d''évaluation', 'Prouve un processus structuré (test technique, entretiens).', true, 'policy', 1),
  ('ET.04', 'Parcours d''onboarding des nouveaux développeurs', 'Prouve l''intégration efficace des recrues.', false, 'document', 2),
  ('ET.04', 'Historique des recrutements et délais', 'Prouve la capacité effective à recruter.', false, 'record', 3),
  ('ET.05', 'Description de la méthodologie de développement', 'Prouve l''usage d''une méthode structurée (Agile/Scrum).', true, 'policy', 1),
  ('ET.05', 'Historique des sprints, vélocité et rétrospectives', 'Prouve l''application réelle des cérémonies.', true, 'record', 2),
  ('ET.06', 'Pipeline CI/CD et procédures de déploiement', 'Prouve l''automatisation de l''intégration et du déploiement continus.', true, 'document', 1),
  ('ET.06', 'Historique d''exécution des pipelines et taux de succès', 'Prouve la fiabilité et la fréquence des déploiements.', false, 'record', 2),
  ('ET.07', 'Procédure de gestion des incidents de production', 'Prouve l''existence d''un processus de détection et résolution.', true, 'policy', 1),
  ('ET.07', 'Planning d''astreintes et registre des incidents récents', 'Prouve l''organisation réelle de la réponse aux incidents.', true, 'record', 2),
  ('ET.07', 'Post-mortems d''incidents', 'Prouve l''apprentissage après incident.', false, 'document', 3),
  ('ET.08', 'Liste des prestataires et freelances intervenant sur le code', 'Prouve la part du développement externalisé.', true, 'document', 1),
  ('ET.08', 'Statistiques de contribution externes vs internes au dépôt', 'Prouve la proportion de code écrit par des externes.', true, 'record', 2),
  ('ET.08', 'Procédure de contrôle du code externe', 'Prouve la revue et l''intégration contrôlées du code externe.', false, 'policy', 3),
  ('SD.01', 'Politique de sécurité', 'Prouve l''existence d''une politique de sécurité formalisée.', true, 'document', 1),
  ('SD.01', 'Preuve de diffusion et d''acceptation de la politique', 'Prouve que la politique est communiquée aux équipes.', false, 'record', 2),
  ('SD.02', 'Revue des droits d''accès aux systèmes critiques', 'Prouve que les accès sont maîtrisés et revus.', true, 'record', 1),
  ('SD.02', 'Configuration MFA sur les outils sensibles', 'Prouve le déploiement de l''authentification forte.', true, 'config', 2),
  ('SD.02', 'Procédure d''arrivée et de départ des collaborateurs', 'Prouve la révocation des accès.', false, 'policy', 3),
  ('SD.03', 'Configuration du chiffrement en transit et au repos', 'Prouve le chiffrement des données sensibles (TLS, stockage, hachage).', true, 'config', 1),
  ('SD.03', 'Politique de gestion des clés et des secrets', 'Prouve la protection des clés de chiffrement.', false, 'policy', 2),
  ('SD.04', 'Registre des traitements RGPD', 'Prouve la cartographie des traitements de données personnelles.', true, 'document', 1),
  ('SD.04', 'Preuve de désignation du DPO et gestion des consentements', 'Prouve la gouvernance RGPD et le recueil des consentements.', true, 'record', 2),
  ('SD.04', 'Analyses d''impact (AIPD) et contrats de sous-traitance', 'Prouve l''encadrement des traitements à risque.', false, 'document', 3),
  ('SD.05', 'Cartographie du stockage des données personnelles clients', 'Prouve où et comment les données clients sont stockées.', true, 'document', 1),
  ('SD.05', 'Journaux d''accès aux données clients', 'Prouve la traçabilité des accès.', true, 'record', 2),
  ('SD.05', 'Politique de rétention et de suppression des données', 'Prouve la maîtrise du cycle de vie des données.', false, 'policy', 3),
  ('SD.06', 'Rapport de test d''intrusion récent', 'Prouve un test de sécurité indépendant réalisé par un tiers.', true, 'document', 1),
  ('SD.06', 'Rapports de scan de vulnérabilités et suivi des corrections', 'Prouve la détection et le traitement des vulnérabilités.', true, 'record', 2),
  ('SD.06', 'Inventaire des dépendances et licences', 'Prouve le suivi des vulnérabilités des dépendances.', false, 'record', 3),
  ('SD.07', 'Registre des incidents de sécurité', 'Prouve l''historique complet des incidents de sécurité.', true, 'record', 1),
  ('SD.07', 'Rapports post-incident et actions correctives', 'Prouve les leçons tirées des brèches.', true, 'document', 2),
  ('SD.07', 'Notifications de violation de données (le cas échéant)', 'Prouve le respect des obligations de notification.', false, 'record', 3),
  ('SD.08', 'Politique et configuration des sauvegardes', 'Prouve que des sauvegardes automatiques sont en place.', true, 'config', 1),
  ('SD.08', 'Rapports de tests de restauration', 'Prouve que les restaurations fonctionnent et leur durée.', true, 'record', 2),
  ('SD.09', 'Plan de réponse aux incidents de sécurité', 'Prouve l''existence d''un plan avec contacts d''urgence.', true, 'policy', 1),
  ('SD.09', 'Compte rendu d''exercice ou simulation de crise', 'Prouve que le plan a été testé.', false, 'record', 2),
  ('IO.01', 'Documentation de l''hébergement (provider, région, type)', 'Prouve le choix et la configuration de l''hébergement de production.', true, 'document', 1),
  ('IO.01', 'Documentation d''architecture technique', 'Prouve l''implantation de l''infrastructure.', false, 'document', 2),
  ('IO.01', 'Contrat ou conditions du fournisseur d''hébergement', 'Prouve les engagements et la pérennité du provider.', false, 'document', 3),
  ('IO.02', 'Factures cloud des 12 derniers mois', 'Prouve les coûts d''infrastructure réels et leur évolution.', true, 'record', 1),
  ('IO.02', 'Tableau de suivi et prévision des coûts d''infrastructure', 'Prouve la maîtrise et la prévisibilité des coûts.', true, 'document', 2),
  ('IO.03', 'Configuration du monitoring et des règles d''alerte', 'Prouve la surveillance des systèmes de production.', true, 'config', 1),
  ('IO.03', 'Historique des alertes et temps de détection', 'Prouve que les anomalies sont détectées avant les utilisateurs.', false, 'record', 2),
  ('IO.04', 'Historique d''uptime sur 12 mois', 'Prouve la disponibilité réelle mesurée.', true, 'record', 1),
  ('IO.04', 'Définition du SLA (interne ou client)', 'Prouve les engagements de disponibilité.', true, 'policy', 2),
  ('IO.04', 'Rapports d''incidents d''indisponibilité', 'Prouve les causes et durées des interruptions.', false, 'record', 3),
  ('IO.05', 'Pipeline CI/CD et procédures de déploiement', 'Prouve les déploiements automatisés et la procédure de rollback.', true, 'document', 1),
  ('IO.05', 'Historique des déploiements et des rollbacks', 'Prouve la fréquence et la réversibilité des déploiements.', false, 'record', 2),
  ('IO.06', 'Description des environnements dev, staging et production', 'Prouve la séparation et la cohérence des environnements.', true, 'document', 1),
  ('IO.06', 'Configuration d''infrastructure as code des environnements', 'Prouve la reproductibilité et la parité des environnements.', false, 'config', 2),
  ('IO.07', 'Configuration d''autoscaling et architecture d''infrastructure', 'Prouve la capacité de scalabilité horizontale.', true, 'config', 1),
  ('IO.07', 'Résultats de tests de charge infrastructure', 'Prouve la tenue de charge x10.', true, 'record', 2),
  ('IO.07', 'Documentation d''architecture technique', 'Prouve la conception scalable de l''infrastructure.', false, 'document', 3),
  ('IO.08', 'Plan de reprise d''activité (PRA)', 'Prouve l''existence d''un PRA couvrant la perte du provider.', true, 'policy', 1),
  ('IO.08', 'Compte rendu de test du PRA (RTO/RPO)', 'Prouve que le PRA a été testé et ses objectifs atteints.', true, 'record', 2),
  ('PI.01', 'Attestation de titularité et d''origine du code source', 'Prouve que l''entreprise possède l''intégralité du code.', true, 'document', 1),
  ('PI.01', 'Analyse des contributeurs au dépôt', 'Prouve l''absence de zones grises sur les contributeurs.', true, 'record', 2),
  ('PI.01', 'Contrats de cession de droits d''auteur', 'Prouve le transfert de propriété du code.', false, 'document', 3),
  ('PI.02', 'Contrats de travail avec clause de cession de PI', 'Prouve la cession de PI par les employés.', true, 'document', 1),
  ('PI.02', 'Pacte d''associés et accords de cession de PI des fondateurs', 'Prouve la cession de PI par les fondateurs.', true, 'document', 2),
  ('PI.03', 'Inventaire des dépendances et licences', 'Prouve l''identification des licences open-source et leur compatibilité.', true, 'document', 1),
  ('PI.03', 'Rapport d''analyse de conformité des licences (SCA)', 'Prouve l''absence de risque de contamination GPL.', true, 'record', 2),
  ('PI.03', 'Politique d''usage de l''open source', 'Prouve l''encadrement de l''usage des licences.', false, 'policy', 3),
  ('PI.04', 'Cartographie des dépendances tierces critiques et risque de lock-in', 'Prouve l''identification des fournisseurs critiques et plans de substitution.', true, 'document', 1),
  ('PI.04', 'Inventaire des dépendances et licences', 'Prouve la liste des SDK et services tiers utilisés.', false, 'document', 2),
  ('PI.04', 'Contrats avec les fournisseurs critiques', 'Prouve les engagements et clauses de réversibilité.', false, 'document', 3),
  ('PI.05', 'Certificats de dépôt de marques et brevets', 'Prouve la protection juridique de la PI.', true, 'document', 1),
  ('PI.05', 'Rapport de recherche d''antériorité', 'Prouve la disponibilité des marques et brevets.', false, 'document', 2),
  ('PI.06', 'Contrats avec les prestataires et freelances techniques', 'Prouve l''inclusion de cession de PI et de confidentialité.', true, 'document', 1),
  ('PI.06', 'Accords de confidentialité (NDA) signés', 'Prouve les engagements de confidentialité.', false, 'document', 2),
  ('PI.07', 'Analyse des réglementations sectorielles applicables', 'Prouve l''identification des réglementations applicables au produit.', true, 'document', 1),
  ('PI.07', 'Preuves de conformité réglementaire (agréments, certifications)', 'Prouve le respect des obligations sectorielles.', true, 'record', 2)
) as r(code, name, descr, is_req, kind, ord)
join public.controls c on c.code = r.code and c.domain_id in (select id from public.domains where framework_id = '00000000-0000-0000-0000-000000000015')
join public.evidence_items ei on ei.name = r.name and ei.framework_id = '00000000-0000-0000-0000-000000000015'
where not exists (select 1 from public.evidence_catalog ec where ec.control_id = c.id and ec.evidence_item_id = ei.id);
